import { test, expect } from '@playwright/test';
import { openMore } from './helpers';
for(const width of [320,390,768,1024,1440,1920]) test(`advanced money tools remain accessible at ${width}px`,async({page})=>{
 await page.setViewportSize({width,height:844}); await page.goto('/?preview=simple');
 for(const name of ['View money flow','Review check-in history','View month-end review','Notes & Reminders','Spending insights']) { await openMore(page,name); expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true); await expect(page.getByRole('button',{name:'Back to Advanced'})).toBeVisible(); }
 await openMore(page,'Tracker settings'); expect(await page.getByRole('dialog').evaluate(el=>el.scrollWidth<=el.clientWidth+1)).toBe(true); await page.keyboard.press('Escape'); await page.getByRole('button',{name:'Advanced',exact:true}).filter({visible:true}).click(); await page.getByText('Payment details & automatic bills',{exact:true}).click(); await page.locator('.funding-list article').first().getByRole('button',{name:'Assign funding'}).click(); expect(await page.getByRole('dialog').evaluate(el=>el.scrollWidth<=el.clientWidth+1)).toBe(true); await page.keyboard.press('Escape');
});
test('income sources, settings, automatic bill details and month notes stay in Advanced',async({page})=>{
 await page.goto('/'); await openMore(page,'View money flow'); await page.getByRole('button',{name:'Add income source',exact:true}).click(); let form=page.getByRole('dialog'); await form.locator('#source-name').fill('Client invoices'); await form.locator('#source-scope').selectOption('Business'); await form.locator('#source-category').selectOption('Business income'); await form.locator('#source-account').selectOption('chase-savings'); await form.getByRole('button',{name:'Save income source'}).click(); await expect(form).toBeHidden();
 await openMore(page,'Tracker settings'); form=page.getByRole('dialog'); await form.locator('#reminder-time').fill('19:00'); await form.locator('#small-threshold').fill('5'); await form.getByRole('button',{name:'Save settings'}).click();
 await page.getByRole('button',{name:'Advanced',exact:true}).click(); await page.getByText('Payment details & automatic bills',{exact:true}).click(); const rent=page.locator('.funding-list article').filter({has:page.getByRole('heading',{name:'Rent',exact:true})}); await rent.getByRole('button',{name:'Assign funding'}).click(); form=page.getByRole('dialog'); await form.locator('#funding-account').selectOption('chase-savings'); await form.locator('#funding-day').fill('5'); await form.locator('#funding-autopay').selectOption('true'); await form.getByRole('button',{name:'Save funding'}).click(); await expect(rent).toContainText('Autopay: Yes');
 const saved=await page.evaluate(()=>JSON.parse(localStorage.getItem('cash-flow-tracker-v1')!)); expect(saved.incomeSources.find((s:any)=>s.name==='Client invoices').scope).toBe('Business'); expect(saved.settings[0].smallPurchaseThresholdCents).toBe(500); expect(saved.expenseFunding[0].paymentAccountId).toBe('chase-savings'); expect(saved.transactions).toHaveLength(0);
 await openMore(page,'View money flow'); await page.getByRole('button',{name:'Add entry',exact:true}).filter({visible:true}).click(); await page.getByRole('dialog').getByRole('button',{name:'Got paid',exact:true}).click(); await page.getByLabel('From whom').fill('Client invoices'); await expect(page.getByLabel('Paid into')).toHaveValue('chase-savings'); await page.keyboard.press('Escape');
});
