import { test, expect, type Page } from '@playwright/test';
import { initialState } from '../../shared/seed';
async function open(page: Page) { await page.goto('/'); await expect(page.getByRole('heading', {name:'Home',exact:true})).toBeVisible(); }
async function add(page: Page, amount: string, name: string) { await page.getByRole('button',{name:'Add entry',exact:true}).filter({visible:true}).click(); const form=page.getByRole('dialog'); await form.getByLabel('Amount',{exact:true}).fill(amount); await form.getByRole('combobox',{name:'What for'}).fill('Grocery'); await page.keyboard.press('Tab'); await form.getByRole('button',{name:'More options'}).click(); await form.getByLabel('Store (optional)').fill(name); await form.getByRole('button',{name:'Save',exact:true}).click(); await expect(form).toBeHidden(); }
test('two tabs preserve each other’s entries and edits reject a stale revision', async ({page,context})=>{
 await open(page); const second=await context.newPage(); await open(second); await add(page,'.10','First tab'); await expect(second.locator('.entry-row')).toContainText('First tab'); await add(second,'.20','Second tab'); await expect(page.locator('.entry-row')).toHaveCount(2);
 await page.locator('.entry-row').filter({hasText:'First tab'}).click(); await second.locator('.entry-row').filter({hasText:'First tab'}).click(); await second.getByLabel('Amount',{exact:true}).fill('.30'); await second.getByRole('button',{name:'Save changes',exact:true}).click(); await page.getByLabel('Amount',{exact:true}).fill('.40'); await page.getByRole('button',{name:'Save changes',exact:true}).click(); await expect(page.getByRole('alert')).toContainText('changed'); await expect(page.getByLabel('Amount',{exact:true})).toHaveValue('0.40');
});
test('desktop keyboard amount, purpose, account, save and quick examples are deterministic', async({page})=>{
 await open(page); for(const text of ['5 grocery heb','$37.74 gas','.05 other']) { await page.getByRole('button',{name:'Add entry',exact:true}).filter({visible:true}).click(); await page.getByLabel('Quick entry',{exact:true}).fill(text); await page.getByLabel('Quick entry',{exact:true}).press('Enter'); await page.getByRole('button',{name:'Save',exact:true}).click(); await expect(page.getByRole('dialog')).toBeHidden(); }
 const state=await page.evaluate(()=>JSON.parse(localStorage.getItem('cash-flow-tracker-v1')!)); expect(state.transactions.map((t:any)=>t.amountCents)).toEqual([500,3774,5]); expect(state.transactions[0].merchant).toBe('heb');
 await page.getByRole('button',{name:'Add entry',exact:true}).filter({visible:true}).click(); await expect(page.getByLabel('Amount',{exact:true})).toBeFocused(); await page.keyboard.type('5.5'); await page.keyboard.press('Tab'); await expect(page.getByRole('combobox',{name:'What for'})).toBeFocused(); await page.keyboard.type('gro'); await page.keyboard.press('Tab'); await expect(page.getByLabel('Paid from')).toBeFocused(); await page.keyboard.press('Tab'); await expect(page.getByRole('button',{name:'Save',exact:true})).toBeFocused(); await page.keyboard.press('Enter'); await expect(page.getByRole('dialog')).toBeHidden();
});
test('add, rename and hide an account preserves saved history',async({page})=>{
 await open(page); await page.getByRole('button',{name:'Accounts',exact:true}).click(); await page.getByRole('button',{name:'Add account',exact:true}).click(); const form=page.getByRole('dialog'); await form.getByLabel('Name',{exact:true}).fill('Everyday savings'); await form.getByLabel('Last four digits').fill('1234'); await form.getByRole('combobox',{name:'Type',exact:true}).selectOption('Savings'); await form.getByRole('button',{name:'Save',exact:true}).click(); const row=page.locator('.account-row').filter({hasText:'Everyday savings'}); await row.locator('summary').click(); await row.getByRole('button',{name:'Edit account'}).click(); await page.getByRole('checkbox',{name:/Hide account/}).check(); await page.getByRole('button',{name:'Save',exact:true}).click(); await expect(row).toHaveCount(0); const state=await page.evaluate(()=>JSON.parse(localStorage.getItem('cash-flow-tracker-v1')!)); expect(state.accounts).toHaveLength(6); expect(state.accounts.at(-1).hidden).toBe(true); expect(state.audit).toHaveLength(2);
});
