import {test, expect, type Page} from '@playwright/test';
import {initialState} from '../../shared/seed';
import {localDate, validateTransaction} from '../../shared/model';
import {localMinute} from '../../shared/allocation';
import {contrastAudit} from './water-contrast';
async function nav(page:Page,name:string){const target=page.getByRole('button',{name,exact:true}).filter({visible:true});if(['My spending','Money in & out','Daily checks','Monthly review','Notes & reminders'].includes(name)&&!await target.count())await page.getByText('Advanced',{exact:true}).click();await target.click();}
async function audit(page:Page){await page.waitForTimeout(200); expect((await contrastAudit(page)).failures).toEqual([]); expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true); const dialog=page.getByRole('dialog'); if(await dialog.count()) expect(await dialog.evaluate(el=>el.scrollWidth<=el.clientWidth+1)).toBe(true);}
for(const mode of ['dark','light']) for(const {width,scale} of [{width:320,scale:1},{width:320,scale:2},{width:768,scale:1}]) test(`${mode} expanded details and editors fit ${width}px at ${scale*100}% text`,async({page})=>{
 await page.setViewportSize({width,height:844}); await page.addInitScript(mode=>localStorage.setItem('cash-flow-appearance',mode),mode); await page.goto('/?preview=simple'); await expect(page.getByRole('heading',{name:'Home',exact:true})).toBeVisible(); await page.evaluate(scale=>document.documentElement.style.fontSize=`${scale*100}%`,scale);
 await nav(page,'Plan'); const housing=page.locator('.budget-group').filter({hasText:'Housing'}); await housing.locator(':scope > summary').click(); const rent=housing.locator('.budget-item').filter({has:page.getByText('Rent',{exact:true})}); await rent.locator('summary').click(); await audit(page); await rent.getByRole('button',{name:'Edit',exact:true}).click(); await audit(page); await page.getByRole('button',{name:'Close dialog'}).click(); await page.getByText('Money coming in',{exact:true}).click(); await page.getByRole('button',{name:/Money I expect/}).click(); await audit(page); await page.getByRole('button',{name:'Close dialog'}).click();
 await nav(page,'My money'); const account=page.locator('.account-row').first(); await account.locator('summary').click(); await audit(page); await account.getByRole('button',{name:'Edit account'}).click(); await audit(page); await page.getByRole('button',{name:'Close dialog'}).click(); await account.getByRole('button',{name:'Check my bank',exact:true}).click(); await page.getByLabel('Balance in your bank app',{exact:true}).fill('100'); await audit(page); await page.getByRole('button',{name:'Close dialog'}).click();
 await nav(page,'More'); await nav(page,'My spending'); await page.getByText('Spending patterns & charts',{exact:true}).click(); await page.getByText('Things to review',{exact:true}).click(); await audit(page);
});
test('clearing a bill due day and payment default keeps the old records and opens an empty purchase amount',async({page})=>{
 const source=initialState(), rentId=source.budgets.find(b=>b.label==='Rent')!.id; source.expenseFunding=[{id:'legacy-rent',budgetId:rentId,month:'*',paymentAccountId:source.accounts[0].id,amountCents:121000,dueDay:3,autopay:true,revision:1,updatedAt:'2026-09-01T00:00:00Z'}];
 await page.addInitScript(s=>{if(!localStorage.getItem('cash-flow-tracker-v1')) localStorage.setItem('cash-flow-tracker-v1',JSON.stringify(s));},source); await page.goto('/'); await nav(page,'Plan'); const housing=page.locator('.budget-group').filter({hasText:'Housing'}); await housing.locator(':scope > summary').click(); const rent=housing.locator('.budget-item').filter({has:page.getByText('Rent',{exact:true})}); await rent.locator('summary').click(); await rent.getByRole('button',{name:'Edit',exact:true}).click(); await page.getByLabel('Due day (optional)').fill(''); await page.getByLabel('Paid from').selectOption(''); await nav(page,'Save'); await expect(page.getByRole('dialog')).toBeHidden(); await expect(rent).not.toContainText('Due'); await rent.getByRole('button',{name:'Add spending'}).click(); await expect(page.getByLabel('Amount',{exact:true})).toHaveValue(''); await page.getByRole('button',{name:'Close dialog'}).click();
 await nav(page,'More'); await page.getByText('Advanced',{exact:true}).click(); await page.getByText('Bill settings',{exact:true}).click(); const row=page.locator('.funding-list article').filter({has:page.getByRole('heading',{name:'Rent',exact:true})}); await expect(row).toContainText('No due day'); await row.getByRole('button',{name:'Edit bill settings'}).click(); await nav(page,'Edit amount, account and due day in Plan'); await expect(page.getByLabel('Due day (optional)')).toHaveValue(''); const stored=await page.evaluate(()=>JSON.parse(localStorage.getItem('cash-flow-tracker-v1')!)); expect(stored.expenseFunding).toEqual(source.expenseFunding); expect(stored.transactions).toHaveLength(0);
});

test('an older entry remains editable after its settled account is hidden',async({page})=>{
 const state=initialState(), account=state.accounts[0], now=localMinute(); account.balanceCents=0; account.balanceAsOf=now; account.hidden=true; account.balanceIncludedTransactionIds='["old-entry"]';
 state.transactions=[validateTransaction({id:'old-entry',type:'Expense',amountCents:5,date:localDate(),time:now.slice(11),merchant:'Older purchase',category:'Food',subcategory:'Grocery',accountId:account.id,toAccountId:'',scope:'Personal',classification:'Need',description:'',notes:''},state)];
 await page.addInitScript(s=>{if(!localStorage.getItem('cash-flow-tracker-v1')) localStorage.setItem('cash-flow-tracker-v1',JSON.stringify(s));},state); await page.goto('/'); await nav(page,'History'); await page.locator('.entry-row').filter({hasText:'Older purchase'}).click(); await expect(page.getByLabel('Paid from')).toHaveValue(account.id); await page.getByLabel('Amount',{exact:true}).fill('.10'); await nav(page,'Save changes'); await expect(page.getByRole('dialog')).toBeHidden(); const saved=await page.evaluate(()=>JSON.parse(localStorage.getItem('cash-flow-tracker-v1')!)); expect(saved.transactions[0].amountCents).toBe(10); expect(saved.transactions[0].accountId).toBe(account.id); expect(saved.accounts[0].hidden).toBe(true);
});
