import { navigateTest } from './helpers';
import { test, expect } from '@playwright/test';
import { waterPreviewState } from '../../shared/waterPreview';
async function history(page:any){ await page.getByRole('button', {name:'Advanced',exact:true}).filter({visible:true}).click(); await page.getByText('More tools', {exact:true}).click(); await page.getByText('Past changes & other tools',{exact:true}).click(); const account=page.locator('.advanced-account').first(); await account.locator(':scope > summary').click(); return account; }
test('advanced observations keep immutable history without changing starting balances',async({page})=>{
 const source=waterPreviewState(); await page.addInitScript(s=>{if(!localStorage.getItem('cash-flow-tracker-v1')) localStorage.setItem('cash-flow-tracker-v1',JSON.stringify(s));},source); await page.goto('/'); let account=await history(page); await account.getByRole('button',{name:'Check a past balance'}).click(); await page.locator('#actual-balance').fill('100'); await page.locator('#comparison-note').fill('Review missing entry'); await page.getByRole('button',{name:'Save comparison'}).click(); await account.getByText('Balance details (1)',{exact:true}).click(); await expect(account).toContainText('Off by'); const state=await page.evaluate(()=>JSON.parse(localStorage.getItem('cash-flow-tracker-v1')!)); expect(state.accounts).toEqual(source.accounts); expect(state.transactions).toEqual(source.transactions); expect(state.balanceReconciliations).toHaveLength(1);
 await page.reload(); account=await history(page); await account.getByText('Balance details (1)',{exact:true}).click(); await expect(account).toContainText('Off by');
});
test('adding a missing entry updates the check before an explicit bank correction',async({page})=>{
 await page.goto('/?preview=simple'); await navigateTest(page, 'My money'); await page.getByRole('button',{name:'Check my bank',exact:true}).filter({visible:true}).click(); await page.getByLabel('Balance in your bank app',{exact:true}).fill('100'); await page.getByRole('button',{name:'Add missing entry'}).click(); await page.getByLabel('Amount',{exact:true}).fill('1'); await page.getByRole('combobox',{name:'What for'}).fill('Other'); await page.keyboard.press('Tab'); await page.getByRole('button',{name:'Save',exact:true}).click(); await expect(page.getByRole('dialog',{name:'Check my bank'})).toBeVisible(); await expect(page.getByRole('dialog').locator('.bank-app-balance')).not.toContainText('Not set');
});
