import { navigateTest } from './helpers';
import { test, expect, type Page } from '@playwright/test';
import { mkdir } from 'node:fs/promises';
import { initialState } from '../../shared/seed';
import { waterPreviewState } from './reviewFixture';
import { localDate } from '../../shared/model';
import { contrastAudit } from './water-contrast';
async function nav(page: any, name: string) { await navigateTest(page, name); }
async function open(page: Page, demo = false) { await page.addInitScript(state => { if (!localStorage.getItem('cash-flow-tracker-v1')) localStorage.setItem('cash-flow-tracker-v1', JSON.stringify(state)); }, demo ? waterPreviewState() : initialState()); await page.goto('/'); await expect(page.getByRole('heading', { name: 'Home', exact: true })).toBeVisible(); }
async function add(page: Page, amount: string, type = 'I spent', destination = '') { await nav(page, 'Add entry'); const dialog = page.getByRole('dialog'); await dialog.getByRole('button', { name: type, exact: true }).click(); await dialog.getByLabel('Amount', { exact: true }).fill(amount); if (type === 'I spent') { await dialog.getByRole('combobox', { name: 'What for' }).fill('gro'); await page.keyboard.press('Enter'); } if (type === 'I got paid') await dialog.getByLabel('From whom').fill('Payday'); if (destination) await dialog.getByLabel('To account').selectOption(destination); return dialog; }
test('quick purchase, income, card payment, duplicate tap, undo, edit and remove preserve cents', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 }); await open(page);
  const start = Date.now(); let dialog = await add(page, '.01'); await dialog.getByRole('button', { name: 'Save', exact: true }).dblclick(); await expect(dialog).toBeHidden(); expect(Date.now() - start).toBeLessThan(10000);
  let stored = await page.evaluate(() => JSON.parse(localStorage.getItem('cash-flow-tracker-v1')!)); expect(stored.transactions).toHaveLength(1); expect(stored.transactions[0].amountCents).toBe(1);
  await page.getByRole('button', { name: 'Undo', exact: true }).click(); expect(await page.evaluate(() => JSON.parse(localStorage.getItem('cash-flow-tracker-v1')!).transactions)).toHaveLength(0);
  dialog = await add(page, '$5'); await dialog.getByRole('button', { name: 'Save', exact: true }).click(); await expect(dialog).toBeHidden();
  dialog = await add(page, '100', 'I got paid'); await dialog.getByRole('button', { name: 'Save', exact: true }).click(); await expect(dialog).toBeHidden();
  dialog = await add(page, '20', 'Move money', 'capital-one-savor'); await dialog.getByRole('button', { name: 'Pay card', exact: true }).click(); await expect(dialog).toBeHidden();
  await nav(page, 'History'); await expect(page.locator('.simple-metric').first()).toContainText('$5.00'); await expect(page.locator('.simple-metric').nth(1)).toContainText('$100.00');
  await page.locator('.entry-row').filter({ hasText: 'Grocery' }).click(); await page.getByLabel('Amount', { exact: true }).fill('5.5'); await page.getByRole('button', { name: 'Save changes', exact: true }).click(); await page.reload();
  stored = await page.evaluate(() => JSON.parse(localStorage.getItem('cash-flow-tracker-v1')!)); expect(stored.transactions).toHaveLength(3); expect(stored.transactions.find((t: any) => t.type === 'Expense').amountCents).toBe(550);
  await nav(page, 'History'); await page.locator('.entry-row').filter({ hasText: 'Grocery' }).click(); await page.getByRole('button', { name: 'Remove entry', exact: true }).click(); await page.getByRole('button', { name: 'Remove entry', exact: true }).click(); await expect(page.getByRole('dialog')).toBeHidden();
  stored = await page.evaluate(() => JSON.parse(localStorage.getItem('cash-flow-tracker-v1')!)); expect(stored.transactions).toHaveLength(2); expect(stored.audit.at(-1).before.amountCents).toBe(550);
});
test('spending totals open the matching entries; budget and accounts expand only on demand', async ({ page }) => {
  await open(page, true); await nav(page, 'More'); await nav(page, 'My spending');
  for (const label of ['Spent today', 'Spent this week', 'Spent this month']) { await page.getByRole('button', { name: new RegExp(label) }).click(); await expect(page.getByRole('dialog')).toContainText('Groceries'); await expect(page.getByRole('dialog')).not.toContainText('Payday'); await page.keyboard.press('Escape'); }
  await page.getByRole('button',{name:/Spent today/}).click(); await page.getByRole('dialog').locator('.entry-row').filter({hasText:'Groceries'}).click(); await page.getByLabel('Amount',{exact:true}).fill('1'); await page.getByRole('button',{name:'Save changes',exact:true}).click(); await expect(page.getByRole('dialog')).toBeHidden();
  await nav(page, 'Plan'); const group = page.locator('.budget-group').filter({ hasText: 'Housing' }); await expect(group).not.toHaveAttribute('open', ''); await group.locator(':scope > summary').click(); const rent = group.locator('.budget-item').filter({ hasText: 'Rent Insurance' }); await rent.locator('summary').click(); await expect(rent.getByRole('button', { name: 'Edit', exact: true })).toBeVisible();
  await nav(page, 'My money'); const account = page.locator('.account-row').first(); await expect(account).not.toHaveAttribute('open', ''); await account.locator('summary').click(); await expect(account.getByRole('button', { name: 'Check my bank', exact: true })).toBeVisible(); await account.locator('summary').click(); await expect(account.getByRole('button', { name: 'Check my bank', exact: true })).toBeHidden();
});
test('budget editing, future months, due day, one bill payment and scoped cash', async ({ page }) => {
  await open(page, true); await nav(page, 'Plan'); const housing = page.locator('.budget-group').filter({ hasText: 'Housing' }); await housing.locator(':scope > summary').click(); const rent = housing.locator('.budget-item').filter({ has: page.getByText('Rent', { exact: true }) }); await rent.locator('summary').click(); await rent.getByRole('button', { name: 'Edit', exact: true }).click(); const dialog = page.getByRole('dialog'); await dialog.getByLabel('Monthly amount').fill('1200'); await dialog.getByText('Bill details',{exact:true}).click(); await dialog.getByLabel('Due day (optional)').fill('5'); await dialog.getByLabel('Paid from').selectOption('capital-one-checking'); await dialog.getByRole('button', { name: 'Save', exact: true }).click(); await expect(dialog).toBeHidden();
  await rent.getByRole('button', { name: 'Pay bill', exact: true }).click(); await expect(page.getByRole('dialog').getByLabel('Amount', { exact: true })).toHaveValue('1200.00'); await page.getByLabel('Amount',{exact:true}).fill('100'); await page.getByRole('button',{name:'Save',exact:true}).click(); await expect(page.getByRole('dialog')).toBeHidden(); await rent.getByRole('button',{name:'Pay bill',exact:true}).click(); await expect(page.getByLabel('Amount',{exact:true})).toHaveValue('1100.00'); await page.getByRole('button', { name: 'Save', exact: true }).dblclick(); await expect(page.getByRole('dialog')).toBeHidden(); await expect(rent).toContainText('Paid'); await expect(rent.getByRole('button', { name: 'Pay bill', exact: true })).toHaveCount(0);
  await nav(page, 'Next month'); await expect(page.locator('.simple-metric').filter({ hasText: 'Plan to spend' }).first()).toContainText('$2,559.30'); await nav(page, 'Previous month'); await nav(page, 'Previous month'); await expect(page.locator('.simple-metric').filter({ hasText: 'Plan to spend' }).first()).toContainText('$2,569.30');
  await nav(page, 'Home'); const personal = await page.locator('.cash-number').innerText(); await nav(page, 'Business'); expect(await page.locator('.cash-number').innerText()).not.toBe(personal); await nav(page, 'My money'); await expect(page.getByRole('button', { name: 'Business', exact: true })).toHaveAttribute('aria-pressed', 'true'); await page.reload(); await expect(page.getByRole('button', { name: 'Business', exact: true })).toHaveAttribute('aria-pressed', 'true');
});
test('bank check adds missing balances, matches, fixes differences and marks the day done', async ({ page }) => {
  await open(page); await nav(page, 'My money'); await page.getByRole('button', { name: 'Check my bank', exact: true }).filter({ visible: true }).click();
  for (const amount of ['100', '200', '0']) { await page.getByLabel('Balance in your bank app', { exact: true }).or(page.getByLabel('Amount owed in your bank app', { exact: true })).fill(amount); await page.getByRole('button', { name: 'Save bank balance', exact: true }).click(); }
  await expect(page.getByRole('dialog')).toContainText('Done today'); await page.getByRole('button', { name: 'Done', exact: true }).click(); await nav(page, 'Home'); await expect(page.locator('.bank-strip')).toContainText('Done today'); await expect(page.locator('.cash-number')).toContainText('$300.00');
  await page.locator('.bank-strip').click(); await page.getByLabel('Balance in your bank app', { exact: true }).fill('99'); await expect(page.getByRole('dialog')).toContainText('Off by $1.00'); await page.getByRole('button', { name: 'Bank is right, fix balance' }).click(); await page.getByRole('button', { name: 'Done', exact: true }).click(); await expect(page.locator('.cash-number')).toContainText('$299.00');
});
for (const mode of ['water']) for (const width of [320, 390, 768, 1440]) test(`${mode} ${width}: five tabs, readable compact views and screenshot review`, async ({ page }) => {
  await page.setViewportSize({ width, height: 960 }); await page.addInitScript(mode => localStorage.setItem('cash-flow-appearance', mode), mode); await open(page, true); await mkdir('.local/simple/screenshots', { recursive: true });
  for (const name of ['Home', 'Income', 'Expenses', 'Cash flow', 'Advanced']) { await nav(page, name); expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1)).toBe(true); expect(await page.locator('.simple-metrics > *').filter({ visible: true }).count()).toBeLessThanOrEqual(3); await page.waitForTimeout(200); const contrast = await contrastAudit(page); expect(contrast.failures, name).toEqual([]); if (width === 390 || width === 1440) await page.screenshot({ path: `.local/simple/screenshots/${name}-${mode}-${width}.png`, fullPage: true }); }
  await nav(page, 'Add entry'); await expect(page.getByLabel('Amount', { exact: true })).toBeFocused(); expect(await page.evaluate(() => document.getAnimations().map(a => ({ type: a.constructor.name, target: (a.effect as KeyframeEffect)?.target?.getAttribute('class') })))).toEqual([]); expect((await contrastAudit(page)).failures).toEqual([]); if (width === 390 || width === 1440) await page.getByRole('dialog').screenshot({ path: `.local/simple/screenshots/Add-${mode}-${width}.png` });
});
test('reduced motion disables everything, appearance persists, and preview never accesses cloud data', async ({ page }) => {
  const requests: string[] = []; page.on('request', request => { if (new URL(request.url()).pathname.startsWith('/api')) requests.push(request.url()); });
  await page.emulateMedia({ reducedMotion: 'reduce' }); await page.goto('/?preview=simple'); await expect(page.getByRole('heading', { name: 'Home', exact: true })).toBeVisible(); expect(await page.evaluate(() => document.getAnimations().map(a => ({ type: a.constructor.name, target: (a.effect as KeyframeEffect)?.target?.getAttribute('class') })))).toEqual([]); await nav(page, 'Plan'); expect(await page.evaluate(() => document.getAnimations().map(a => ({ type: a.constructor.name, target: (a.effect as KeyframeEffect)?.target?.getAttribute('class') })))).toEqual([]); await nav(page, 'More'); await expect(page.getByRole('button', { name: 'Light', exact: true })).toHaveCount(0); await page.reload(); await expect(page.locator('html')).toHaveAttribute('data-theme', 'water'); expect(requests).toEqual([]);
});
