import test from 'node:test';
import assert from 'node:assert/strict';
import { initialState } from '../shared/seed';
import { summarize, scopedTransactions, validateTransaction, type State } from '../shared/model';
import { balanceBreakdown, currentBalance } from '../shared/allocation';
import { extendState } from '../shared/actions';
import { reconciliationFingerprint, reconciliationStatus, validateReconciliation } from '../shared/reconciliation';
const at = '2026-10-03T23:59';
function fixture() { const s = initialState(); s.accounts = s.accounts.map(a => ({ ...a, balanceCents: a.type === 'Credit card' ? 20000 : 100000, balanceAsOf: '2026-10-01T00:00', balanceUpdatedAt: '2026-10-01T00:00:00Z', balanceIncludedTransactionIds: '[]' })); return s; }
function add(s: State, type: 'Income' | 'Expense' | 'Transfer', accountId: string, amountCents: number, toAccountId = '', scope: 'Personal' | 'Business' = 'Personal') {
  const t = validateTransaction({ id: `entry-${s.transactions.length}`, date: '2026-10-03', time: '10:00', type, accountId, amountCents, toAccountId, scope, category: type === 'Income' ? 'Employment' : 'Food', subcategory: '', merchant: 'Accounting test', description: '', classification: type === 'Expense' ? 'Need' : '', notes: '' }, s); s.transactions.push(t); return t;
}
const balance = (s: State, id: string) => currentBalance(s, s.accounts.find(a => a.id === id)!, at);
function input(s: State, actual = 100000, accountId = 'capital-one-checking', id = 'comparison-1') { const account = s.accounts.find(a => a.id === accountId)!; return { id, accountId, asOf: at, actualBalanceCents: actual, note: '', ledgerFingerprint: reconciliationFingerprint(s, account, at) }; }

test('INCOME increases its destination account and reported income in exact cents', () => { const s = fixture(); add(s, 'Income', 'capital-one-checking', 130000); assert.equal(balance(s, 'capital-one-checking'), 230000); assert.deepEqual(summarize(s.transactions), { income: 130000, expenses: 0, net: 130000, needs: 0, wants: 0 }); });
test('EXPENSE decreases a cash or debit account and increases reported expenses', () => { const s = fixture(); add(s, 'Expense', 'capital-one-checking', 10); assert.equal(balance(s, 'capital-one-checking'), 99990); assert.equal(summarize(s.transactions).expenses, 10); assert.equal(summarize(s.transactions).net, -10); });
test('CREDIT CARD PURCHASE increases debt and expenses without reducing cash', () => { const s = fixture(); add(s, 'Expense', 'capital-one-savor', 5000); assert.equal(balance(s, 'capital-one-savor'), 25000); assert.equal(balance(s, 'capital-one-checking'), 100000); assert.equal(summarize(s.transactions).expenses, 5000); });
test('CREDIT CARD PAYMENT reduces cash and debt without a second expense', () => { const s = fixture(); add(s, 'Expense', 'capital-one-savor', 5000); const reported = summarize(s.transactions); add(s, 'Transfer', 'capital-one-checking', 8000, 'capital-one-savor'); assert.equal(balance(s, 'capital-one-checking'), 92000); assert.equal(balance(s, 'capital-one-savor'), 17000); assert.deepEqual(summarize(s.transactions), reported); const card = balanceBreakdown(s, s.accounts[2], at); assert.equal(card.openingCents! + card.outflows - card.inflows, card.calculatedCents); });
test('TRANSFER moves equal amounts between accounts and leaves reported totals unchanged', () => { const s = fixture(); const reported = summarize(s.transactions), before = balance(s, 'capital-one-checking')! + balance(s, 'chase-savings')!; add(s, 'Transfer', 'capital-one-checking', 30000, 'chase-savings'); assert.equal(balance(s, 'capital-one-checking'), 70000); assert.equal(balance(s, 'chase-savings'), 130000); assert.equal(balance(s, 'capital-one-checking')! + balance(s, 'chase-savings')!, before); assert.deepEqual(summarize(s.transactions), reported); });
test('PERSONAL VS BUSINESS classification stays independent of source and destination ownership', () => { const s = fixture(); add(s, 'Expense', 'chase-savings', 5000); add(s, 'Income', 'capital-one-checking', 130000, '', 'Business'); assert.equal(balance(s, 'chase-savings'), 95000); assert.equal(balance(s, 'capital-one-checking'), 230000); assert.equal(summarize(scopedTransactions(s, '2026-10', 'Personal')).expenses, 5000); assert.equal(summarize(scopedTransactions(s, '2026-10', 'Business')).income, 130000); assert.equal(s.accounts[3].scope, 'Business'); });
test('BALANCE RECONCILIATION captures opening plus in minus out and flags actual differences without adjusting data', () => { const s = fixture(); add(s, 'Income', 'capital-one-checking', 20000); add(s, 'Expense', 'capital-one-checking', 3000); add(s, 'Transfer', 'capital-one-checking', 5000, 'chase-savings'); const original = structuredClone(s); const r = validateReconciliation({ ...input(s, 111900), calculatedBalanceCents: 111900, differenceCents: 0 }, s, at); assert.equal(r.openingBalanceCents, 100000); assert.equal(r.moneyInCents, 20000); assert.equal(r.moneyOutCents, 8000); assert.equal(r.calculatedBalanceCents, 112000); assert.equal(r.differenceCents, -100); assert.equal(reconciliationStatus(s, r), 'Discrepancy — review needed'); assert.deepEqual(s, original); assert.equal(balance(s, 'capital-one-checking'), 112000); });
test('matching, negative, and unknown opening balances are distinguished without fabricating balances', () => { const s = fixture(); const matched = validateReconciliation(input(s), s, at); assert.equal(reconciliationStatus(s, matched), 'Balances match'); const credit = validateReconciliation(input(s, -500, 'capital-one-savor'), s, at); assert.equal(credit.actualBalanceCents, -500); assert.equal(credit.accountType, 'Credit card'); assert.equal(credit.differenceCents, -20500); const unknown = initialState(); const observation = validateReconciliation(input(unknown, 25000), unknown, at); assert.equal(observation.calculatedBalanceCents, null); assert.equal(observation.differenceCents, null); assert.equal(reconciliationStatus(unknown, observation), 'Opening balance needed'); assert.equal(unknown.accounts[0].balanceCents, null); });
test('saved comparisons are immutable, become stale on relevant ledger changes, and cannot overwrite history', () => { const s = fixture(); const t = add(s, 'Expense', 'capital-one-checking', 1000); const r = validateReconciliation(input(s, 99000), s, at); s.balanceReconciliations.push(r); const original = structuredClone(r); t.amountCents = 2000; assert.equal(reconciliationStatus(s, r), 'Ledger changed; compare again'); assert.deepEqual(r, original); assert.throws(() => validateReconciliation(input(s), s, at), /already saved/); const second = validateReconciliation(input(s, 98000, 'capital-one-checking', 'comparison-2'), s, at); s.balanceReconciliations.push(second); assert.equal(reconciliationStatus(s, second), 'Balances match'); assert.equal(s.balanceReconciliations.length, 2); s.accounts[0].type = 'Savings'; assert.equal(reconciliationStatus(s, second), 'Ledger changed; compare again'); assert.equal(second.accountType, 'Checking'); s.accounts[0].balanceCents = 200000; assert.equal(reconciliationStatus(s, second), 'Ledger changed; compare again'); });
test('unrelated and future entries do not invalidate an earlier account comparison', () => { const s = fixture(); const r = validateReconciliation(input(s), s, at); add(s, 'Expense', 'chase-savings', 10); const t = add(s, 'Expense', 'capital-one-checking', 10); t.date = '2026-10-04'; assert.equal(reconciliationStatus(s, r), 'Balances match'); t.date = '2026-10-03'; assert.equal(reconciliationStatus(s, r), 'Ledger changed; compare again'); });
test('comparisons reject stale captures, invalid money, future dates and dates before the opening', () => { const s = fixture(), v = input(s); add(s, 'Expense', 'capital-one-checking', 10); assert.throws(() => validateReconciliation(v, s, at), /changed/); for (const amount of [NaN, 0.5, '100', 100000000000]) assert.throws(() => validateReconciliation({ ...input(s), actualBalanceCents: amount }, s, at), /whole cents/); assert.throws(() => validateReconciliation({ ...input(s), asOf: '2026-10-04T00:00' }, s, at), /no later/); assert.throws(() => validateReconciliation({ ...input(s), asOf: '2026-09-30T23:59' }, s, at), /on or after/); });
test('legacy state migration adds only an empty comparison collection and preserves original financial records', () => { const s = fixture(); add(s, 'Expense', 'capital-one-checking', 10); const { balanceReconciliations: _, ...old } = s; const migrated = extendState(old); assert.deepEqual(migrated.balanceReconciliations, []); for (const key of Object.keys(old) as (keyof typeof old)[]) assert.equal(migrated[key], old[key]); assert.throws(() => extendState({ ...old, balanceReconciliations: {} }), /could not be read/); });

test('comparison size includes its serialized audit record so large evidence cannot overflow one cell', () => { const s = fixture(); while (reconciliationFingerprint(s, s.accounts[0], at).length < 42000) add(s, 'Expense', 'capital-one-checking', 10); const v = { ...input(s), note: 'n'.repeat(2000) }; assert.ok(v.ledgerFingerprint.length < 45000); assert.throws(() => validateReconciliation(v, s, at), /too many movements/); assert.equal(s.balanceReconciliations.length, 0); });
