import { localDate } from './model.js';
export interface FinancialAxiom { topic: string; axiom: string; lesson: string; question: string; source?: string; }
// Original educational principles, fixed locally so no financial history is sent to a model.
const principles: [string, string, string, string, string?][] = [
  ['Cash flow', 'Profit is a result; cash flow determines whether obligations can be paid on time.', 'Revenue and expenses can be recognized before cash changes hands. Compare the timing of collections and payments, alongside profit, when deciding how much capital is available.', 'Which upcoming payment depends on money that has not arrived yet?', 'https://www.sba.gov/counseling/manage-your-business/'],
  ['Ownership', 'Ownership combines a claim on future value with responsibility for losses.', 'An ownership interest may provide distributions or appreciate, but neither is guaranteed. Evaluate the rights, obligations, costs, and cash demands attached to what you own.', 'What do I own that can produce value without requiring a matching increase in my working hours?'],
  ['Assets versus liabilities', 'An asset has economic value, while a liability is an obligation you must settle.', 'Not every asset produces income, and an asset can still create ongoing expenses. Assess both its value and its effect on cash flow rather than treating every purchase as an investment.', 'Which asset I own has carrying costs that exceed the cash it generates?'],
  ['Capital allocation', 'Each dollar committed to one use is unavailable for another use.', 'Compare alternatives by expected benefit, timing, risk, and how easily the commitment can be reversed. Keeping cash available is also an allocation decision when future needs are uncertain.', 'What are the two best competing uses for my next available dollar?'],
  ['Opportunity cost', 'The true cost of a choice includes the best alternative you give up.', 'A purchase uses money that could fund another goal or remain liquid. Opportunity cost is not every possible alternative added together; it is the value of the best realistic alternative forgone.', 'What specific alternative would I give up by making my next discretionary purchase?'],
  ['Leverage', 'Borrowed capital can amplify losses as well as gains.', 'Debt payments remain due even when an asset or business underperforms. Test whether available cash can cover those payments under an unfavorable outcome before using borrowed funds.', 'Could my cash flow still support this debt if expected income fell?'],
  ['Recurring revenue', 'Recurring revenue becomes dependable only when customers continue paying.', 'Repeat billing alone does not establish durable revenue. Retention, collection reliability, customer concentration, and the cost of delivering the service all affect its quality.', 'What would make customers continue paying for a service I could own?'],
  ['Profit', 'Revenue becomes profit only after the relevant costs are accounted for.', 'Sales volume alone does not describe business performance. Include the costs needed to make and support those sales, and distinguish gross profit from profit after operating costs.', 'Which cost is easiest for me to overlook when I assess a revenue opportunity?'],
  ['Margin', 'A sale must contribute enough to support the costs behind the business.', 'Contribution margin is revenue less variable costs; gross margin and net margin measure different layers of profitability. Contribution must also cover fixed costs before the business breaks even.', 'How much of each additional sale remains after its variable costs?', 'https://legacy.sba.gov/business-guide/plan-your-business/calculate-your-startup-costs/break-even-point'],
  ['Liquidity', 'An asset is useful for a near-term obligation only if it can become cash in time.', 'Selling an asset may take time or require accepting a lower price. Match upcoming cash needs with funds that can be accessed reliably rather than relying on an uncertain sale.', 'Which obligation could become difficult if I could not sell an asset quickly?', 'https://www.finra.org/investors/investing/investing-basics/risk'],
  ['Risk', 'A decision should be evaluated by its possible losses as well as its expected return.', 'Expected outcomes are estimates, not guarantees. Consider the size of an unfavorable result, its likelihood, and whether you can absorb it without disrupting essential obligations.', 'What unfavorable outcome could I not comfortably absorb in my current finances?', 'https://www.finra.org/investors/investing/investing-basics/risk'],
  ['Debt', 'The cost of debt includes interest, fees, and the cash committed to repayment.', 'Compare borrowing terms and repayment schedules, not only the advertised rate or monthly payment. A smaller payment can extend the term and increase the total cost.', 'What is the total cost and remaining repayment commitment of my most expensive debt?'],
  ['Return on capital', 'An opportunity must be judged against the capital it ties up and the risk it creates.', 'A dollar profit means little without knowing how much money was committed and for how long. Compare opportunities on a consistent basis and account for fees, cash timing, and uncertainty.', 'How much capital would an opportunity require before it produces spendable cash?'],
  ['Compounding', 'Returns can build on prior returns when they remain invested.', 'Compounding depends on actual returns, costs, and time; it does not guarantee growth. Reinvestment can also compound losses when the underlying activity loses money.', 'Where can retained earnings support productive growth without taking risks I cannot absorb?', 'https://www.investor.gov/introduction-investing'],
  ['Pricing', 'A price must be supported by customer value and the economics of delivery.', 'A higher price can improve contribution per sale but may reduce demand. Test willingness to pay and the full cost of fulfilling the promise rather than assuming volume will repair poor economics.', 'What value would justify my price, and what does it cost me to deliver it?'],
  ['Negotiation', 'A recurring cost reduction can improve future cash flow without increasing sales.', 'Compare equivalent coverage or service levels before accepting a lower price. Include setup fees, contract terms, and later price changes when estimating the benefit.', 'Which recurring bill could I review using competing offers with comparable terms?'],
  ['Expense control', 'An expense deserves review when its ongoing value no longer justifies its ongoing cost.', 'Some costs protect income or essential needs, while others no longer serve their original purpose. Evaluate the benefit and replacement cost before removing an expense.', 'Which recurring expense has not earned its place in my current plan?'],
  ['Financial awareness', 'Accurate records turn financial questions into comparisons you can examine.', 'A ledger makes amounts, dates, and patterns visible. Complete records improve decisions, while gaps can make income or spending appear lower than it actually is.', 'Is there an expense or inflow missing from today’s record?'],
  ['Business ownership', 'Owning a business means managing the system that creates value, not only its sales.', 'Delivery, collection, operations, and customer retention each affect cash generation. Separate business money from personal money so the performance of each remains visible.', 'Which part of a business system could I improve so it produces more reliable cash flow?'],
  ['Productive assets', 'A productive asset must justify its acquisition and ongoing costs through economic benefit.', 'Equipment, software, and intellectual property can support revenue or reduce costs, but ownership alone does not establish productivity. Estimate usage, maintenance, and useful life before committing capital.', 'What measurable benefit would make a proposed asset worth its full cost?'],
  ['Revenue generation', 'A revenue opportunity begins with a customer willing to pay for a useful result.', 'Interest is not the same as a completed sale or a collected payment. Validate demand, delivery costs, and payment terms before making a large commitment.', 'What small, paid test could confirm that someone values my proposed offer?'],
  ['Preservation of capital', 'Avoiding a loss you cannot absorb preserves the ability to make future choices.', 'A potential return should not obscure the amount at risk. Protecting essential liquidity can be more valuable than pursuing an uncertain opportunity with money needed soon.', 'Which portion of my available capital is already committed to essential obligations?'],
  ['Concentration versus diversification', 'Concentration increases dependence on a few outcomes, while diversification can reduce that dependence.', 'Different holdings or income sources must have meaningfully different risks to provide useful diversification. Diversification can reduce some risks but cannot eliminate all losses.', 'Am I relying on several independent sources of value or several versions of the same exposure?', 'https://www.investor.gov/introduction-investing/getting-started/asset-allocation'],
  ['Time value of money', 'Money available today and money promised later are not economically identical.', 'Timing affects how long funds can be used elsewhere, and delayed receipts carry collection risk. Compare future amounts with their timing and an appropriate opportunity cost.', 'What is the practical cost of waiting longer to receive money I have earned?'],
  ['Buying versus consuming', 'A purchase creates financial value only when its benefits justify its full cost.', 'A useful purchase may provide enjoyment without producing revenue, and that distinction is worth recording. Include upkeep, financing, and resale assumptions when calling a purchase an investment.', 'Am I buying income-producing capacity, necessary use, or consumption with this purchase?'],
  ['Delayed gratification', 'Keeping a dollar uncommitted today can preserve a more valuable choice tomorrow.', 'Waiting is useful when it improves information or protects funds for a better-defined need. Delay also has costs, so compare the benefits of waiting with the benefits of acting now.', 'Which purchase would I evaluate more clearly after one day of waiting?'],
  ['Unit economics', 'An activity scales sustainably only when its underlying economics support the added volume.', 'Compare revenue per unit or customer with the variable costs and acquisition costs attributable to it. Also consider retention, service capacity, and fixed costs when deciding whether growth creates value.', 'Does one additional customer contribute enough to support the work and costs that customer creates?'],
  ['Financial optionality', 'Liquidity and manageable obligations keep more future choices available.', 'A commitment can limit your ability to respond to a new need or opportunity. Assess flexibility alongside expected return, especially when future cash flow is uncertain.', 'What commitment is currently reducing my ability to choose freely next month?'],
];
export const axioms: FinancialAxiom[] = principles.map(([topic, axiom, lesson, question, source]) => ({ topic, axiom, lesson, question, source }));
export function dailyAxiom(date = localDate()): FinancialAxiom {
  const [year, month, day] = date.split('-').map(Number);
  const ordinal = Math.floor(Date.UTC(year, month - 1, day) / 86400000);
  return axioms[((ordinal % axioms.length) + axioms.length) % axioms.length];
}
