import { build } from 'esbuild';

await build({
  entryPoints: ['server/handler.ts'],
  outfile: 'api/index.js',
  bundle: true,
  platform: 'node',
  format: 'esm',
  target: 'node24',
  packages: 'external',
  banner: { js: '// Generated by scripts/build-server.mjs. Edit server/shared sources, then rebuild. No environment values are embedded.' },
});
