import { friendlyError } from './words';
import { useRef, useState, type FormEvent } from 'react';
import { ArrowDown, ArrowRight, Download, Pencil, Plus, Wallet } from 'lucide-react';
import { money, parseCents, scopedTransactions, type Budget, type Scope, type State } from '../shared/model';
import { fundedExpenses, fundingFor, monthlyReview, nextMonth, settingsFor, type ExpenseFunding, type IncomeSource, type MonthReview, type TrackerSettings } from '../shared/allocation';
import { detectLeaks } from '../shared/leaks';
import { Empty, Modal, monthLabel } from './components';
import { dateLabel } from './financialActions';
import { Metric } from './SimpleViews';
const accountName = (state: State, id: string) => { const a = state.accounts.find(a => a.id === id); return a ? `${a.name} •••• ${a.lastFour}` : 'Choose when I pay'; };
export function FundingSection({ state, month, scope, onEdit }: { state: State; month: string; scope: Scope | 'All'; onEdit: (b: Budget) => void }) {
  const rows = fundedExpenses(state, month, scope), unassigned = rows.filter(r => !r.funding?.paymentAccountId).length;
  return <section className="panel expense-funding"><div className="panel-heading"><div><h2>Which account pays each bill?</h2><p>{unassigned} bills still need a payment account.</p></div><Wallet size={21} /></div><p className="panel-note">Choose which account pays each bill. This does not pay the bill.</p><div className="funding-list">{rows.map(r => <article key={r.budget.id}><div><h3>{r.budget.label}</h3><span className="tag">{r.budget.scope}</span><p className={!r.funding?.paymentAccountId ? 'unassigned' : ''}>Paid from: {accountName(state, r.funding?.paymentAccountId ?? '')}</p></div><div><strong>{money(r.amountCents)}</strong><small>{r.date ? `Due ${dateLabel(r.date)}` : 'No due day'}</small><small>Automatic payment: {r.funding ? r.funding.autopay ? 'Yes' : 'No' : 'Not set'}</small></div><button className="button secondary" onClick={() => onEdit(r.budget)}><Pencil size={14} />Edit bill settings</button></article>)}</div></section>;
}
export function FundingForm({ state, budget, month, onSave, onClose, onBudgetEdit }: { state: State; budget: Budget; month: string; onSave: (v: ExpenseFunding) => Promise<void>; onClose: () => void; onBudgetEdit?: () => void }) {
  const hasDetails = budget.dueDay !== undefined || budget.paymentAccountId !== undefined, base = fundedExpenses(state, month).find(r => r.budget.id === budget.id)?.funding, [recurring, setRecurring] = useState(!base || base.month === '*' || base.month.startsWith('from:'));
  const [account, setAccount] = useState(base?.paymentAccountId ?? ''), [amount, setAmount] = useState(((base?.amountCents ?? budget.amountCents) / 100).toFixed(2)), [day, setDay] = useState(base?.dueDay == null ? '' : String(base.dueDay)), [autopay, setAutopay] = useState(base?.autopay ?? false), [busy, setBusy] = useState(false), [error, setError] = useState('');
  async function submit(e: FormEvent) { e.preventDefault(); setBusy(true); setError(''); try { const targetMonth = recurring ? (hasDetails ? `from:${month}` : '*') : month, before = state.expenseFunding.find(f => f.budgetId === budget.id && f.month === targetMonth); await onSave({ id: '', budgetId: budget.id, month: targetMonth, paymentAccountId: account, amountCents: parseCents(amount), dueDay: day ? Number(day) : null, autopay, revision: before?.revision ?? 0, updatedAt: '' }); onClose(); } catch (e) { setError(friendlyError(e)); } finally { setBusy(false); } }
  return <Modal title={`Bill settings for ${budget.label}`} subtitle={`${budget.scope} planned expense · ${monthLabel(month)}`} onClose={onClose}><form onSubmit={submit}>{hasDetails && <button type="button" className="text-button" onClick={onBudgetEdit}>Edit amount, account and due day in Plan<ArrowRight size={14} /></button>}<label htmlFor="funding-account">Paid from<select id="funding-account" disabled={hasDetails} value={account} onChange={e => setAccount(e.target.value)}><option value="">Choose when I pay</option>{state.accounts.map(a => <option key={a.id} value={a.id}>{a.name} •••• {a.lastFour} · {a.scope}</option>)}</select></label><label htmlFor="funding-amount">Monthly amount ($)<input id="funding-amount" readOnly={hasDetails} inputMode="decimal" required value={amount} onChange={e => setAmount(e.target.value)} /></label><label htmlFor="funding-day">Due day of month (optional)<input id="funding-day" readOnly={hasDetails} type="number" min="1" max="31" value={day} onChange={e => setDay(e.target.value)} /><span className="field-hint">A day beyond the end of a month falls on that month’s last day.</span></label><label htmlFor="funding-autopay">Automatic payment<select id="funding-autopay" value={String(autopay)} onChange={e => setAutopay(e.target.value === 'true')}><option value="false">No</option><option value="true">Yes</option></select></label><label className="checkbox-label"><input type="checkbox" checked={recurring} onChange={e => setRecurring(e.target.checked)} />Use this every month</label><p className="panel-note">{recurring ? 'Used each month unless you set a different plan.' : `Applies to ${monthLabel(month)} only.`} Save a spending entry when the bill is paid.</p>{error && <p className="form-error" role="alert">{error}</p>}<div className="modal-footer"><button type="button" className="button secondary" onClick={onClose}>Cancel</button><button className="button primary" disabled={busy}>Save bill settings</button></div></form></Modal>;
}
export function SettingsForm({ state, onSave, onClose }: { state: State; onSave: (s: TrackerSettings) => Promise<void>; onClose: () => void }) {
  const settings = settingsFor(state), [time, setTime] = useState(settings.reminderTime), [threshold, setThreshold] = useState((settings.smallPurchaseThresholdCents / 100).toFixed(2)), [busy, setBusy] = useState(false), [error, setError] = useState('');
  async function submit(e: FormEvent) { e.preventDefault(); setBusy(true); try { await onSave({ ...settings, reminderTime: time, smallPurchaseThresholdCents: parseCents(threshold) }); onClose(); } catch (e) { setError(friendlyError(e)); } finally { setBusy(false); } }
  return <Modal title="Tracker settings" onClose={onClose}><form onSubmit={submit}><label htmlFor="reminder-time">Daily reminder time<input id="reminder-time" type="time" value={time} required onChange={e => setTime(e.target.value)} /></label><p className="panel-note">Shown in the app after this time. Uses this device’s local time.</p><label htmlFor="small-threshold">Small purchases under ($)<input id="small-threshold" inputMode="decimal" required value={threshold} onChange={e => setThreshold(e.target.value)} /></label><p className="panel-note">Expenses below this amount count as small purchases.</p>{error && <p className="form-error" role="alert">{error}</p>}<div className="modal-footer"><button className="button secondary" type="button" onClick={onClose}>Cancel</button><button className="button primary" disabled={busy}>Save settings</button></div></form></Modal>;
}
export function IncomeSourceForm({ state, edit, onSave, onClose }: { state: State; edit?: IncomeSource; onSave: (s: IncomeSource) => Promise<void>; onClose: () => void }) {
  const id = useRef(edit?.id ?? crypto.randomUUID()), [name, setName] = useState(edit?.name ?? ''), [scope, setScope] = useState<Scope>(edit?.scope ?? 'Personal'), [category, setCategory] = useState(edit?.category ?? 'Employment'), [account, setAccount] = useState(edit?.defaultAccountId ?? ''), [busy, setBusy] = useState(false), [error, setError] = useState('');
  async function submit(e: FormEvent) { e.preventDefault(); setBusy(true); try { await onSave({ id: id.current, name, scope, category, defaultAccountId: account, revision: edit?.revision ?? 0, updatedAt: '' }); onClose(); } catch (e) { setError(friendlyError(e)); } finally { setBusy(false); } }
  return <Modal title={edit ? 'Edit payer' : 'Add payer'} subtitle="Save a name and account for next time" onClose={onClose}><form onSubmit={submit}><label htmlFor="source-name">Name<input id="source-name" required maxLength={200} value={name} onChange={e => setName(e.target.value)} /></label><label htmlFor="source-scope">Personal or Business<select id="source-scope" value={scope} onChange={e => setScope(e.target.value as Scope)}><option>Personal</option><option>Business</option></select></label><label htmlFor="source-category">Group<select id="source-category" value={category} onChange={e => setCategory(e.target.value)}>{state.categories.map(c => <option key={c.id}>{c.name}</option>)}</select></label><label htmlFor="source-account">Paid into<select id="source-account" value={account} onChange={e => setAccount(e.target.value)}><option value="">Choose when I get paid</option>{state.accounts.map(a => <option key={a.id} value={a.id}>{a.name} •••• {a.lastFour}</option>)}</select></label><p className="panel-note">These choices fill new entries. Earlier entries stay as they are.</p>{error && <p className="form-error" role="alert">{error}</p>}<div className="modal-footer"><button className="button secondary" type="button" onClick={onClose}>Cancel</button><button className="button primary" disabled={busy}>Save payer</button></div></form></Modal>;
}
export function IncomeAllocation({ state, month, scope = 'All' }: { state: State; month: string; scope?: Scope | 'All' }) {
  const report = monthlyReview(state, month, scope);
  return <section className="panel income-allocation"><div className="panel-heading"><div><h2>Money received</h2><p>{monthLabel(month)} · {scope}</p></div><ArrowRight size={20} /></div><div className="account-totals"><div><span>Personal income</span><strong>{money(report.personal.income)}</strong></div><div><span>Business income</span><strong>{money(report.business.income)}</strong></div></div><div className="allocation-columns">{[{ title: 'Paid by', rows: report.incomeSources }, { title: 'Paid into', rows: report.incomeAccounts.map(r => ({ ...r, name: accountName(state, r.name) })) }].map(group => <div key={group.title}><h3>{group.title}</h3>{group.rows.length ? <div className="plan-lines">{group.rows.map(r => <div key={r.name}><span>{r.name}</span><strong>{money(r.amountCents)}</strong></div>)}</div> : <p className="panel-note">No income recorded this month.</p>}</div>)}</div></section>;
}
export function MoneyFlow({ state, month, scope, onAddSource, onEditSource }: { state: State; month: string; scope: Scope | 'All'; onAddSource: () => void; onEditSource: (s: IncomeSource) => void }) {
  const rows = scopedTransactions(state, month, scope);
  return <><details className="simple-disclosure"><summary>People who pay me</summary><section className="panel"><div className="panel-heading"><div><h2>Saved names</h2><p>Choose a name to edit.</p></div><button className="button secondary" onClick={onAddSource}><Plus size={15} />Add payer</button></div><div className="source-list">{state.incomeSources.filter(s => scope === 'All' || s.scope === scope).map(s => <div key={s.id}><span><strong>{s.name}</strong><small>{s.scope} · {accountName(state, s.defaultAccountId)}</small></span><button className="text-button" onClick={() => onEditSource(s)}><Pencil size={14} />Edit payer</button></div>)}</div></section></details><details className="simple-disclosure"><summary>Where my income goes</summary><IncomeAllocation state={state} month={month} scope={scope} /></details><section className="panel"><div className="panel-heading"><div><h2>Money in & out</h2><p>Your recorded movements</p></div><ArrowDown size={21} /></div><p className="panel-note">A card purchase counts as spending. Paying the card moves money between accounts.</p>{rows.length ? <ol className="flow-list">{rows.map(t => <li key={t.id}><div className="flow-date">{dateLabel(t.date)} · {t.time}<span className="tag">{t.scope}</span></div><div className="flow-path">{t.type === 'Income' ? <><div className="flow-node"><small>Paid by</small><strong>{t.merchant}</strong></div><ArrowRight aria-label="received by" size={19} /><div className="flow-node"><small>Paid into</small><strong>{accountName(state, t.accountId)}</strong></div></> : t.type === 'Transfer' ? <><div className="flow-node"><small>From account</small><strong>{accountName(state, t.accountId)}</strong></div><div className="flow-transfer"><ArrowRight size={20} /><span>Moved money</span></div><div className="flow-node"><small>To account</small><strong>{accountName(state, t.toAccountId)}</strong></div></> : <><div className="flow-node"><small>Paid from</small><strong>{accountName(state, t.accountId)}</strong></div><ArrowRight aria-label="paid to" size={19} /><div className="flow-node"><small>{t.category} · {t.classification}</small><strong>{t.merchant}</strong></div></>}<strong className="flow-amount">{money(t.amountCents)}</strong></div>{t.notes && <p>{t.notes}</p>}</li>)}</ol> : <Empty title="Nothing logged this month yet." text="Add money received, spending or a move between accounts." />}</section></>;
}
export function MonthEndReview({ state, month, scope, onSave }: { state: State; month: string; scope: Scope | 'All'; onSave: (r: MonthReview) => Promise<void> }) {
  const report = monthlyReview(state, month, scope), leaks = detectLeaks(state, month, scope), before = state.monthReviews.find(r => r.id === `${month}-${scope}`);
  const [note, setNote] = useState(before?.note ?? ''), [busy, setBusy] = useState(false), [error, setError] = useState(''), [saved, setSaved] = useState(false);
  const fromPrevious = state.monthReviews.filter(r => r.nextMonth === month && (r.scope === scope || r.scope === 'All'));
  async function submit(e: FormEvent) { e.preventDefault(); setBusy(true); setError(''); try { await onSave({ id: `${month}-${scope}`, month, scope, note, nextMonth: nextMonth(month), revision: before?.revision ?? 0, createdAt: '', updatedAt: '' }); setSaved(true); } catch (e) { setError(friendlyError(e)); } finally { setBusy(false); } }
  const values = [{ label: 'Money received', value: report.income }, { label: 'Personal income', value: report.personal.income }, { label: 'Business income', value: report.business.income }, { label: 'Spent', value: report.expenses }, { label: 'Personal spending', value: report.personal.expenses }, { label: 'Business spending', value: report.business.expenses }, { label: 'Left over', value: report.net }, { label: 'Need spending', value: report.needs }, { label: 'Want spending', value: report.wants }, { label: 'Spending in my plan', value: report.planned }, { label: 'Spending outside my plan', value: report.unplanned }, { label: 'Small purchase total', value: report.smallTotal }, { label: 'Money transferred between accounts', value: report.transfers }, { label: 'Monthly savings noted', value: report.monthlySavings }, { label: 'Savings over a year (estimate)', value: report.annualizedSavings }];
  return <><div className="simple-metrics"><Metric label="Money received" value={money(report.income)} /><Metric label="Spent" value={money(report.expenses)} /><Metric label="Left over" value={money(report.net)} /></div><details className="simple-disclosure"><summary>More details</summary><section className="panel"><div className="panel-heading"><div><h2>{monthLabel(month)} · Monthly review</h2><p>{scope} · Your recorded entries</p></div><Wallet size={21} /></div><div className="review-values">{values.filter(v => !['Money received', 'Spent', 'Left over'].includes(v.label)).map(v => <div key={v.label}><span>{v.label}</span><strong>{money(v.value)}</strong></div>)}<div><span>Small purchases</span><strong>{report.smallCount}</strong></div><div><span>Things to review</span><strong>{leaks.length}</strong></div></div><p className="panel-note">Moving money does not count as spending or money received. Savings noted in reminders are estimates; they do not add money to your accounts.</p></section></details><details className="simple-disclosure"><summary>Where I spent most</summary><div className="allocation-columns review-columns">{[{ title: 'Where I spent most', items: report.categories }, { title: 'Places I visit most', items: report.merchants }].map(group => <section className="panel" key={group.title}><h2>{group.title}</h2><div className="pattern-list">{group.items.map(item => <div key={item.name}><span><strong>{item.name}</strong><small>{item.count} recorded purchases</small></span><strong>{money(item.amountCents)}</strong></div>)}</div>{!group.items.length && <p className="panel-note">No expenses recorded.</p>}</section>)}</div></details>{fromPrevious.length > 0 && <section className="panel"><h2>Notes carried into {monthLabel(month)}</h2>{fromPrevious.map(r => <div className="carried-note" key={r.id}><span className="tag">{r.scope}</span><p>{r.note || 'No changes noted.'}</p></div>)}</section>}<section className="panel"><h2>What should change next month?</h2><p className="panel-note">Save decisions for {monthLabel(nextMonth(month))}. Earlier notes stay in Change history.</p><form onSubmit={submit}><label htmlFor="month-review-note">Notes for next month<textarea id="month-review-note" maxLength={6000} value={note} onChange={e => { setNote(e.target.value); setSaved(false); }} placeholder="What would I like to do differently?" /></label>{error && <p className="form-error" role="alert">{error}</p>}<div className="modal-footer">{saved && <span role="status">Notes saved for next month.</span>}<button className="button primary" disabled={busy}>Save review notes</button></div></form></section></>;
}
