import { friendlyError } from './words';
import { useState } from 'react';
import { Search, ShieldCheck } from 'lucide-react';
import { money, summarize, type Scope, type State, type Transaction } from '../shared/model';
import type { FinancialAction } from '../shared/actions';
import { detectLeaks, type FinancialLeak } from '../shared/leaks';
import { Modal, TransactionList, monthLabel } from './components';
export function FinancialLeakPanel({ state, month, scope, onCreate, onDismiss, onEditTransaction, today, compact = false, onOpen }: { state: State; month: string; scope: Scope | 'All'; onCreate: (preset: Partial<FinancialAction>) => void; onDismiss: (leak: FinancialLeak) => Promise<void>; onEditTransaction: (transaction: Transaction) => void; today: string; compact?: boolean; onOpen?: () => void }) {
  const leaks = detectLeaks(state, month, scope), [review, setReview] = useState<FinancialLeak>(), [busy, setBusy] = useState(''), [error, setError] = useState('');
  const shown = compact ? leaks.slice(0, 2) : leaks;
  const create = (leak: FinancialLeak) => { setReview(undefined); onCreate({ title: `Review: ${leak.transactions.find(t => t.date.startsWith(month))?.merchant || leak.title}`, note: `${leak.title}. ${leak.message}`, category: leak.category, scope: leak.scope, priority: 'Medium', reminderDate: today, amountAffectedCents: leak.amountAffectedCents, relatedExpenseId: leak.relatedExpenseId, relatedAccountId: leak.relatedAccountId }); };
  async function dismiss(leak: FinancialLeak) { setBusy(leak.id); setError(''); try { await onDismiss(leak); } catch (e) { setError(friendlyError(e)); } finally { setBusy(''); } }
  return <section className="panel leak-panel"><div className="panel-heading"><div><h2>Worth a look</h2><p>{monthLabel(month)} · Patterns to review, not confirmed mistakes</p></div><Search size={21} /></div>{shown.length ? <div className="leak-list">{shown.map(leak => <article className="leak-item" key={leak.id}><div className="leak-item-title"><h3>{leak.title}</h3><span className="tag">{leak.scope}</span></div><p>{leak.message}</p><div className="leak-buttons"><button className="button secondary" onClick={() => setReview(leak)}>View entries</button><button className="button secondary" onClick={() => create(leak)}>Add reminder</button><button className="text-button" disabled={Boolean(busy)} onClick={() => void dismiss(leak)}>{busy === leak.id ? 'Saving…' : 'Dismiss'}</button></div></article>)}</div> : <div className="leak-empty"><ShieldCheck size={18} /><p>Nothing to review right now.</p></div>}{compact && leaks.length > shown.length && <button className="text-button" onClick={onOpen}>View all {leaks.length} review flags →</button>}{error && <p className="form-error" role="alert">{error}</p>}{review && <Modal title="Review recorded charges" subtitle={review.message} onClose={() => setReview(undefined)} wide><div className="review-evidence">{[...new Set(review.transactions.map(t => t.date.slice(0, 7)))].sort().reverse().map(period => { const rows = review.transactions.filter(t => t.date.startsWith(period)).sort((a, b) => b.date.localeCompare(a.date)); return <section key={period}><div className="day-heading"><h3>{monthLabel(period)}</h3><span>{money(summarize(rows).expenses)} · {rows.length} {rows.length === 1 ? 'charge' : 'charges'}</span></div><TransactionList transactions={rows} state={state} compact onEdit={t => { setReview(undefined); onEditTransaction(t); }} /></section>; })}</div><div className="modal-footer"><button className="button secondary" onClick={() => setReview(undefined)}>Close</button><button className="button primary" onClick={() => create(review)}>Add reminder</button></div></Modal>}</section>;
}
