import { useState } from 'react';
import { BookOpen, Check, ClipboardCheck, Search, ShieldCheck } from 'lucide-react';
import { money, monthBudgets, scopedTransactions, summarize, type Scope, type State, type Transaction } from '../shared/model';
import { transactionFingerprint, type DailyCheckIn, type FinancialAction } from '../shared/actions';
import { dailyAxiom } from '../shared/axioms';
import { detectLeaks, type FinancialLeak } from '../shared/leaks';
import { Empty, Modal, TransactionList, monthLabel } from './components';
import { dateLabel } from './financialActions';
export function DailyFinancialAxiom({ today }: { today: string }) {
  const principle = dailyAxiom(today);
  return <section className="panel axiom-card"><div className="panel-heading"><div><h2>Daily Financial Axiom</h2><p>{dateLabel(today)} · {principle.topic}</p></div><BookOpen size={21} /></div><span className="axiom-label">AXIOM</span><h3>{principle.axiom}</h3><span className="axiom-label">LESSON</span><p>{principle.lesson}</p><div className="axiom-question"><span className="axiom-label">QUESTION</span><p>{principle.question}</p></div>{principle.source && <a className="text-button" href={principle.source} target="_blank" rel="noreferrer">Read the educational reference ↗</a>}</section>;
}
export function FinancialCheckIn({ state, scope, today, onConfirm, onReview }: { state: State; scope: Scope | 'All'; today: string; onConfirm: (input: Pick<DailyCheckIn, 'date' | 'scope' | 'revision' | 'transactionFingerprint'>) => Promise<void>; onReview: () => void }) {
  const [busy, setBusy] = useState(false), [error, setError] = useState('');
  const all = scopedTransactions(state, today.slice(0, 7), scope), transactions = all.filter(t => t.date === today), daily = summarize(transactions), monthly = summarize(all);
  const plan = monthBudgets(state, today.slice(0, 7), scope).reduce((sum, b) => sum + b.amountCents, 0);
  const saved = state.dailyCheckIns.find(c => c.id === `${today}-${scope}`), fingerprint = transactionFingerprint(state, today, scope);
  const confirmed = saved?.transactionFingerprint === fingerprint;
  async function confirm() {
    setBusy(true); setError('');
    try { await onConfirm({ date: today, scope, revision: saved?.revision ?? 0, transactionFingerprint: fingerprint }); } catch (e) { setError((e as Error).message); } finally { setBusy(false); }
  }
  return <section className="panel check-in-card"><div className="panel-heading"><div><h2>Financial check-in</h2><p>Today · {dateLabel(today)} · {scope} accounts</p></div><ClipboardCheck size={21} /></div><div className="check-in-values">{[{ label: 'Money in', value: money(daily.income) }, { label: 'Money out', value: money(daily.expenses) }, { label: 'Net cash flow', value: money(daily.net) }, { label: 'Transactions recorded', value: String(transactions.length) }, { label: 'Current monthly spending', value: money(monthly.expenses) }, { label: 'Remaining monthly budget', value: money(plan - monthly.expenses) }].map(v => <div key={v.label}><span>{v.label}</span><strong>{v.value}</strong></div>)}</div><div className="check-in-question"><div><h3>Is every transaction from today recorded?</h3><p>{confirmed ? `You confirmed today’s entries at ${new Date(saved!.confirmedAt).toLocaleTimeString('en-US', { hour: 'numeric', minute: '2-digit' })}.` : saved ? 'Today’s entries changed after your last check-in. Review them and confirm again.' : 'Check the ledger, then confirm when today’s record is complete.'}</p></div><div className="check-in-buttons"><button className="button primary" disabled={busy || confirmed} onClick={() => void confirm()}><Check size={16} />{busy ? 'Saving…' : confirmed ? 'Confirmed' : 'Yes'}</button><button className="button secondary" onClick={onReview}>Review Transactions</button></div></div>{error && <p className="form-error" role="alert">{error}</p>}</section>;
}
export function FinancialLeakPanel({ state, month, scope, onCreate, onDismiss, onEditTransaction, today, compact = false, onOpen }: { state: State; month: string; scope: Scope | 'All'; onCreate: (preset: Partial<FinancialAction>) => void; onDismiss: (leak: FinancialLeak) => Promise<void>; onEditTransaction: (transaction: Transaction) => void; today: string; compact?: boolean; onOpen?: () => void }) {
  const leaks = detectLeaks(state, month, scope), [review, setReview] = useState<FinancialLeak>(), [busy, setBusy] = useState(''), [error, setError] = useState('');
  const shown = compact ? leaks.slice(0, 2) : leaks;
  const create = (leak: FinancialLeak) => { setReview(undefined); onCreate({ title: `Review: ${leak.transactions.find(t => t.date.startsWith(month))?.merchant || leak.title}`, note: `${leak.title}. ${leak.message}`, category: leak.category, scope: leak.scope, priority: 'Medium', reminderDate: today, amountAffectedCents: leak.amountAffectedCents, relatedExpenseId: leak.relatedExpenseId, relatedAccountId: leak.relatedAccountId }); };
  async function dismiss(leak: FinancialLeak) { setBusy(leak.id); setError(''); try { await onDismiss(leak); } catch (e) { setError((e as Error).message); } finally { setBusy(''); } }
  return <section className="panel leak-panel"><div className="panel-heading"><div><h2>Potential financial leaks</h2><p>{monthLabel(month)} · Recorded patterns to review, not confirmed errors</p></div><Search size={21} /></div>{shown.length ? <div className="leak-list">{shown.map(leak => <article className="leak-item" key={leak.id}><div className="leak-item-title"><h3>{leak.title}</h3><span className="tag">{leak.scope}</span></div><p>{leak.message}</p><div className="leak-buttons"><button className="button secondary" onClick={() => setReview(leak)}>Review Bill</button><button className="button secondary" onClick={() => create(leak)}>Create Reminder</button><button className="text-button" disabled={Boolean(busy)} onClick={() => void dismiss(leak)}>{busy === leak.id ? 'Saving…' : 'Dismiss'}</button></div></article>)}</div> : <div className="leak-empty"><ShieldCheck size={18} /><p>No review flags from the available history. Comparisons need enough recorded history; this doesn’t establish that every charge is correct.</p></div>}{compact && leaks.length > shown.length && <button className="text-button" onClick={onOpen}>View all {leaks.length} review flags →</button>}{error && <p className="form-error" role="alert">{error}</p>}{review && <Modal title="Review recorded charges" subtitle={review.message} onClose={() => setReview(undefined)} wide><div className="review-evidence">{[...new Set(review.transactions.map(t => t.date.slice(0, 7)))].sort().reverse().map(period => { const rows = review.transactions.filter(t => t.date.startsWith(period)).sort((a, b) => b.date.localeCompare(a.date)); return <section key={period}><div className="day-heading"><h3>{monthLabel(period)}</h3><span>{money(summarize(rows).expenses)} · {rows.length} {rows.length === 1 ? 'charge' : 'charges'}</span></div><TransactionList transactions={rows} state={state} compact onEdit={t => { setReview(undefined); onEditTransaction(t); }} /></section>; })}</div><div className="modal-footer"><button className="button secondary" onClick={() => setReview(undefined)}>Close</button><button className="button primary" onClick={() => create(review)}>Create Reminder</button></div></Modal>}</section>;
}
