import { useRef, useState, type FormEvent } from 'react';
import { Bell, Check, ClipboardList, Pencil, Plus, Search } from 'lucide-react';
import { money, parseCents, type Scope, type State } from '../shared/model';
import { actionCategories, actionSummary, dueActions, scopedActions, validateAction, type FinancialAction } from '../shared/actions';
import { Empty, Modal } from './components';
export const dateLabel = (date: string) => new Date(`${date}T12:00:00`).toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' });
export function ActionForm({ state, scope, edit, preset, onClose, onSave }: { state: State; scope: Scope | 'All'; edit?: FinancialAction; preset?: Partial<FinancialAction>; onClose: () => void; onSave: (action: FinancialAction) => Promise<void> }) {
  const base = edit ?? preset;
  const [form, setForm] = useState({ title: base?.title ?? '', note: base?.note ?? '', category: base?.category ?? 'Bill Review', scope: base?.scope ?? (scope === 'All' ? 'Personal' : scope), priority: base?.priority ?? 'Medium', status: base?.status ?? 'Open', reminderDate: base?.reminderDate ?? '', relatedExpenseId: base?.relatedExpenseId ?? '', relatedAccountId: base?.relatedAccountId ?? '' });
  const dollars = (value: number | null | undefined) => value == null ? '' : (value / 100).toFixed(2);
  const [affected, setAffected] = useState(dollars(base?.amountAffectedCents)), [previousCost, setPreviousCost] = useState(dollars(base?.previousCostCents)), [newCost, setNewCost] = useState(dollars(base?.newCostCents)), [monthlySavings, setMonthlySavings] = useState(dollars(base?.monthlySavingsCents));
  const [busy, setBusy] = useState(false), [error, setError] = useState('');
  const id = useRef(edit?.id ?? crypto.randomUUID());
  const set = (key: keyof typeof form, value: string) => setForm(f => ({ ...f, [key]: value }));
  const optional = (text: string, signed = false) => { if (!text.trim()) return null; const negative = signed && text.trim().startsWith('-'); const amount = parseCents(negative ? text.trim().slice(1) : text.trim()); return negative ? -amount : amount; };
  let savings: number | null = null;
  try { savings = previousCost.trim() && newCost.trim() ? optional(previousCost)! - optional(newCost)! : optional(monthlySavings, true); } catch { /* Validation is shown on save, not while typing. */ }
  const expenseOptions = [...new Map(state.budgets.filter(b => b.scope === form.scope).map(b => [b.id, b])).values()];
  async function submit(e: FormEvent) {
    e.preventDefault(); setBusy(true); setError('');
    try {
      const action = validateAction({ ...form, id: id.current, amountAffectedCents: optional(affected), previousCostCents: optional(previousCost), newCostCents: optional(newCost), monthlySavingsCents: previousCost.trim() && newCost.trim() ? null : optional(monthlySavings, true), revision: edit?.revision }, state, edit);
      await onSave(edit ? { ...action, revision: edit.revision } : action); onClose();
    } catch (e) { setError((e as Error).message); } finally { setBusy(false); }
  }
  return <Modal title={edit ? 'Edit financial action' : 'Add financial action'} subtitle="An observation now. A clear next step when you’re ready." onClose={onClose}>
    <form onSubmit={submit} className="action-form">
      <label htmlFor="action-title">Title<input data-autofocus id="action-title" value={form.title} onChange={e => set('title', e.target.value)} placeholder="e.g. Review the Spectrum bill" required maxLength={200} /></label>
      <label htmlFor="action-note">Note<textarea id="action-note" value={form.note} onChange={e => set('note', e.target.value)} placeholder="What changed? What’s the next step?" maxLength={4000} /></label>
      <div className="form-grid"><label htmlFor="action-category">Action category<select id="action-category" value={form.category} onChange={e => set('category', e.target.value)}>{actionCategories.map(c => <option key={c}>{c}</option>)}</select></label><label htmlFor="action-scope">Money space<select id="action-scope" value={form.scope} onChange={e => setForm(f => ({ ...f, scope: e.target.value as Scope, relatedAccountId: '', relatedExpenseId: '' }))}><option>Personal</option><option>Business</option></select></label></div>
      <div className="form-grid"><label htmlFor="action-priority">Priority<select id="action-priority" value={form.priority} onChange={e => set('priority', e.target.value)}>{['Low', 'Medium', 'High'].map(p => <option key={p}>{p}</option>)}</select></label><label htmlFor="action-status">Status<select id="action-status" value={form.status} onChange={e => set('status', e.target.value)}>{['Open', 'In Progress', 'Completed'].map(s => <option key={s}>{s}</option>)}</select></label></div>
      <label htmlFor="action-reminder">Reminder date (optional)<input id="action-reminder" type="date" value={form.reminderDate} onChange={e => set('reminderDate', e.target.value)} /><span className="field-hint">Due and upcoming reminders appear inside this app.</span></label>
      <label htmlFor="related-expense">Related expense (optional)<select id="related-expense" value={form.relatedExpenseId} onChange={e => set('relatedExpenseId', e.target.value)}><option value="">No linked expense</option><optgroup label="Planned expenses">{expenseOptions.map(b => <option key={b.id} value={`budget:${b.id}`}>{b.label}</option>)}</optgroup><optgroup label="Recorded expenses">{state.transactions.filter(t => t.type === 'Expense' && t.scope === form.scope).map(t => <option key={t.id} value={`transaction:${t.id}`}>{t.merchant || t.description} · {dateLabel(t.date)} · {money(t.amountCents)}</option>)}</optgroup></select></label>
      <label htmlFor="related-account">Related account (optional)<select id="related-account" value={form.relatedAccountId} onChange={e => set('relatedAccountId', e.target.value)}><option value="">No linked account</option>{state.accounts.filter(a => a.scope === form.scope).map(a => <option key={a.id} value={a.id}>{a.name} •••• {a.lastFour}</option>)}</select></label>
      <label htmlFor="action-affected">Amount potentially affected ($, optional)<input id="action-affected" inputMode="decimal" value={affected} onChange={e => setAffected(e.target.value)} placeholder="Leave blank if unknown" /></label>
      <fieldset className="action-costs"><legend>Savings outcome (optional)</legend><p>Use comparable monthly costs. These figures don’t change your ledger.</p><div className="form-grid"><label htmlFor="previous-cost">Previous monthly cost ($)<input id="previous-cost" inputMode="decimal" value={previousCost} onChange={e => setPreviousCost(e.target.value)} placeholder="e.g. 90.00" /></label><label htmlFor="new-cost">New monthly cost ($)<input id="new-cost" inputMode="decimal" value={newCost} onChange={e => setNewCost(e.target.value)} placeholder="e.g. 70.00" /></label></div><label htmlFor="monthly-savings">Monthly savings ($)<input id="monthly-savings" inputMode="decimal" readOnly={Boolean(previousCost.trim() && newCost.trim())} value={previousCost.trim() && newCost.trim() ? savings === null ? '' : (savings / 100).toFixed(2) : monthlySavings} onChange={e => setMonthlySavings(e.target.value)} placeholder="Calculated from both costs, or enter directly" /><span className="field-hint">When both costs are entered, savings are calculated automatically.</span></label><div className="savings-preview"><span>Annualized savings</span><strong>{savings === null ? 'Not specified' : money(savings * 12)}</strong></div><small>Monthly savings × 12, assuming the change lasts a full year.</small></fieldset>
      {error && <p className="form-error" role="alert">{error}</p>}<div className="modal-footer"><button type="button" className="button secondary" disabled={busy} onClick={onClose}>Cancel</button><button className="button primary" disabled={busy}><Check size={16} />{busy ? 'Saving…' : 'Save action'}</button></div>
    </form>
  </Modal>;
}
export function FinancialActionsCard({ state, scope, today, onAdd, onEdit, onOpen }: { state: State; scope: Scope | 'All'; today: string; onAdd: () => void; onEdit: (a: FinancialAction) => void; onOpen: () => void }) {
  const summary = actionSummary(state, scope), upcoming = dueActions(state, scope, today);
  return <section className="panel financial-actions-card"><div className="panel-heading"><div><h2>Financial actions</h2><p>Observations with a next step</p></div><ClipboardList size={21} /></div><div className="action-summary"><div><strong>{summary.open}</strong><span>Open</span></div><div><strong>{summary.high}</strong><span>High priority</span></div><div><strong>{money(summary.affected)}</strong><span>Potentially affected</span></div></div>{upcoming.length ? <div className="upcoming-actions">{upcoming.slice(0, 3).map(a => <button key={a.id} onClick={() => onEdit(a)}><Bell size={16} /><span><strong>{a.title}</strong><small>{a.reminderDate ? `${a.reminderDate < today ? 'Overdue' : a.reminderDate === today ? 'Due today' : 'Upcoming'} · ${dateLabel(a.reminderDate)}` : 'High priority'} · {a.status}</small></span><span className={`priority-tag ${a.priority.toLowerCase()}`}>{a.priority}</span></button>)}</div> : <p className="panel-note">No due, upcoming, or high-priority actions in this money space.</p>}<div className="action-card-footer"><button className="text-button" onClick={onAdd}><Plus size={15} />Add action</button><button className="text-button" onClick={onOpen}>Notes & Reminders →</button></div></section>;
}
export function NotesReminders({ state, scope, today, onAdd, onEdit, onSave }: { state: State; scope: Scope | 'All'; today: string; onAdd: () => void; onEdit: (a: FinancialAction) => void; onSave: (a: FinancialAction) => Promise<void> }) {
  const [query, setQuery] = useState(''), [status, setStatus] = useState('Active'), [priority, setPriority] = useState('All'), [busy, setBusy] = useState(''), [error, setError] = useState('');
  const summary = actionSummary(state, scope);
  const actions = scopedActions(state, scope).filter(a => (status === 'All' || (status === 'Active' ? a.status !== 'Completed' : a.status === status)) && (priority === 'All' || a.priority === priority) && `${a.title} ${a.note} ${a.category}`.toLowerCase().includes(query.toLowerCase())).sort((a, b) => Number(b.priority === 'High') - Number(a.priority === 'High') || (a.reminderDate || '9999').localeCompare(b.reminderDate || '9999') || b.createdAt.localeCompare(a.createdAt));
  async function complete(a: FinancialAction) { setBusy(a.id); setError(''); try { await onSave({ ...a, status: 'Completed' }); } catch (e) { setError((e as Error).message); } finally { setBusy(''); } }
  return <><div className="ledger-summary actions-overview"><div><span>Open actions</span><strong>{summary.open}</strong></div><div><span>In progress</span><strong>{summary.inProgress}</strong></div><div><span>Reported monthly savings</span><strong>{money(summary.monthlySavings)}</strong></div><div><span>Annualized estimate</span><strong>{money(summary.annualizedSavings)}</strong></div></div><section className="panel notes-tools"><div className="ledger-tools"><label className="search"><Search size={18} /><input aria-label="Search financial actions" value={query} onChange={e => setQuery(e.target.value)} placeholder="Search notes and actions" /></label><select aria-label="Filter action status" value={status} onChange={e => setStatus(e.target.value)}>{['Active', 'Open', 'In Progress', 'Completed', 'All'].map(s => <option key={s}>{s}</option>)}</select><select aria-label="Filter action priority" value={priority} onChange={e => setPriority(e.target.value)}><option value="All">All priorities</option>{['High', 'Medium', 'Low'].map(p => <option key={p}>{p}</option>)}</select><button className="button primary" onClick={onAdd}><Plus size={16} />Add financial action</button></div><p>Actions stay available across all months. Savings totals use completed actions only; reminders are shown in this app.</p></section>{error && <p className="form-error" role="alert">{error}</p>}{actions.length ? <div className="action-grid">{actions.map(a => {
    const account = state.accounts.find(account => account.id === a.relatedAccountId);
    const [kind, expenseId] = a.relatedExpenseId.split(':');
    const expense = kind === 'budget' ? state.budgets.find(b => b.id === expenseId)?.label : state.transactions.find(t => t.id === expenseId)?.merchant;
    return <article key={a.id} className={`panel action-card ${a.status === 'Completed' ? 'completed' : ''}`}><div className="action-tags"><span className={`priority-tag ${a.priority.toLowerCase()}`}>{a.priority} priority</span><span className="tag">{a.status}</span><span className="tag">{a.scope}</span></div><h2>{a.title}</h2>{a.note && <p className="action-note">{a.note}</p>}<div className="action-details"><span>{a.category}</span>{a.reminderDate && <span><Bell size={13} />{a.status !== 'Completed' && a.reminderDate < today ? 'Overdue · ' : ''}{dateLabel(a.reminderDate)}</span>}{expense && <span>Expense: {expense}</span>}{account && <span>Account: {account.name} •••• {account.lastFour}</span>}{a.amountAffectedCents !== null && <span>Potentially affected: {money(a.amountAffectedCents)}</span>}</div>{a.monthlySavingsCents !== null && <div className="action-savings"><span>{a.status === 'Completed' ? 'Reported savings' : 'Estimated savings'}</span><strong>{money(a.monthlySavingsCents)} / month</strong><small>{money(a.annualizedSavingsCents!)} annualized · assumes 12 months</small></div>}<p className="action-dates">Created {new Date(a.createdAt).toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' })}{a.completedAt && ` · Completed ${new Date(a.completedAt).toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' })}`}</p><div className="action-card-footer"><button className="text-button" onClick={() => onEdit(a)}><Pencil size={14} />Edit action</button>{a.status !== 'Completed' && <button className="button secondary" disabled={Boolean(busy)} onClick={() => void complete(a)}><Check size={14} />{busy === a.id ? 'Saving…' : 'Mark completed'}</button>}</div></article>;
  })}</div> : <section className="panel"><Empty title={status === 'Completed' ? 'Completed actions stay here' : 'A place for your next financial action'} text={query ? 'Try a different search or filter.' : 'Record a bill to review, a service to negotiate, or an opportunity to research.'} action="Add financial action" onClick={onAdd} /></section>}</>;
}
