import { useState, type FormEvent } from 'react';
import { balanceBreakdown, localMinute } from '../shared/allocation';
import { accountReconciliations, reconciliationFingerprint, reconciliationStatus, type BalanceReconciliation } from '../shared/reconciliation';
import { money, parseCents, type Account, type State } from '../shared/model';
import { Modal } from './components';
const amount = (value: number | null) => value === null ? 'Not set' : money(value);
const atLabel = (value: string) => value ? new Date(value).toLocaleString('en-US', { dateStyle: 'medium', timeStyle: 'short' }) : 'Not set';
type Equation = { openingCents: number | null; openingAsOf: string; inflows: number; outflows: number; calculatedCents: number | null };
function BalanceEquation({ account, values }: { account: Account; values: Equation }) {
  const credit = account.type === 'Credit card';
  return <div className="balance-equation"><p className="panel-note">{credit ? 'Opening owed + charges / money out − payments / money in = Calculated owed' : 'Opening balance + money in − money out = Calculated balance'}</p><dl><div><dt>{credit ? 'Opening owed' : 'Opening balance'}</dt><dd>{amount(values.openingCents)}</dd></div><div><dt>{credit ? '+ Charges / money out' : '+ Money in'}</dt><dd>{money(credit ? values.outflows : values.inflows)}</dd></div><div><dt>{credit ? '− Payments / money in' : '− Money out'}</dt><dd>{money(credit ? values.inflows : values.outflows)}</dd></div><div className="calculated-row"><dt>{credit ? 'Calculated owed' : 'Calculated balance'}</dt><dd>{amount(values.calculatedCents)}</dd></div></dl><p className="panel-note">Opening snapshot: {atLabel(values.openingAsOf)}. Movements include all classifications, since that snapshot.</p></div>;
}
function SavedComparison({ state, account, record }: { state: State; account: Account; record: BalanceReconciliation }) {
  const status = reconciliationStatus(state, record);
  return <div className="saved-comparison"><p className={`reconciliation-status ${status === 'Balances match' ? 'matched' : 'review-needed'}`}>{status}</p><p className="panel-note">Observed {atLabel(record.asOf)}</p><dl><div><dt>Calculated at comparison</dt><dd>{amount(record.calculatedBalanceCents)}</dd></div><div><dt>{record.accountType === 'Credit card' ? 'Actual amount owed' : 'Actual bank balance'}</dt><dd>{money(record.actualBalanceCents)}</dd></div><div><dt>Difference (actual − calculated)</dt><dd>{amount(record.differenceCents)}</dd></div></dl>{record.note && <p className="comparison-note">{record.note}</p>}{status.startsWith('Ledger changed') && <p className="panel-note">These saved values remain unchanged. Save a new comparison using the updated ledger.</p>}</div>;
}
export function ReconciliationPanel({ state, account, onCompare }: { state: State; account: Account; onCompare: () => void }) {
  const records = accountReconciliations(state, account.id);
  return <section className="reconciliation-panel" aria-label="Balance reconciliation"><h3>Balance reconciliation</h3><BalanceEquation account={account} values={balanceBreakdown(state, account)} />{records.length ? <SavedComparison state={state} account={account} record={records[0]} /> : <p className="panel-note">Actual bank balance has not been compared yet.</p>}<button className="button secondary" onClick={onCompare}>Compare actual balance</button>{records.length > 0 && <details className="comparison-history"><summary>Comparison history ({records.length})</summary>{records.map(record => <details key={record.id}><summary>{atLabel(record.asOf)} · {reconciliationStatus(state, record)}</summary><SavedComparison state={state} account={account} record={record} /><BalanceEquation account={{ ...account, type: record.accountType }} values={{ openingCents: record.openingBalanceCents, openingAsOf: record.openingAsOf, inflows: record.moneyInCents, outflows: record.moneyOutCents, calculatedCents: record.calculatedBalanceCents }} /></details>)}</details>}<p className="panel-note">A comparison preserves your records. Review discrepancies before making any corrections.</p></section>;
}
export function ReconciliationForm({ state, account, onSave, onClose }: { state: State; account: Account; onSave: (v: unknown) => Promise<void>; onClose: () => void }) {
  const [asOf, setAsOf] = useState(localMinute), [actual, setActual] = useState(''), [note, setNote] = useState(''), [busy, setBusy] = useState(false), [error, setError] = useState('');
  const values = balanceBreakdown(state, account, asOf);
  let actualCents: number | null = null;
  try { if (actual.trim()) actualCents = (actual.trim().startsWith('-') ? -1 : 1) * parseCents(actual.trim().replace(/^-/, '')); } catch { /* Invalid amounts are explained on submit. */ }
  async function submit(e: FormEvent) {
    e.preventDefault(); setError(''); setBusy(true);
    try {
      if (actualCents === null) throw new Error('Enter a dollar amount with up to two decimal places.');
      await onSave({ id: crypto.randomUUID(), accountId: account.id, asOf, actualBalanceCents: actualCents, note, ledgerFingerprint: reconciliationFingerprint(state, account, asOf) }); onClose();
    } catch (e) { setError((e as Error).message); } finally { setBusy(false); }
  }
  return <Modal title="Compare actual balance" subtitle={`${account.name} •••• ${account.lastFour}`} onClose={onClose}><form onSubmit={submit}><label htmlFor="comparison-as-of">Bank balance as of<input id="comparison-as-of" type="datetime-local" required max={localMinute()} min={values.openingAsOf || undefined} value={asOf} onChange={e => setAsOf(e.target.value)} /></label><BalanceEquation account={account} values={values} /><label htmlFor="actual-balance">{account.type === 'Credit card' ? 'Actual amount owed ($)' : 'Actual bank balance ($)'}<input data-autofocus id="actual-balance" inputMode="decimal" required placeholder="0.00" value={actual} onChange={e => setActual(e.target.value)} /><span className="field-hint">Use the bank balance at the observation time. A negative card amount means the bank owes you a credit.</span></label>{actualCents !== null && values.calculatedCents !== null && <p className={`reconciliation-status ${actualCents === values.calculatedCents ? 'matched' : 'review-needed'}`}>Difference (actual − calculated): {money(actualCents - values.calculatedCents)} · {actualCents === values.calculatedCents ? 'Balances match' : 'Discrepancy — review needed'}</p>}{values.calculatedCents === null && <p className="reconciliation-status review-needed">Opening balance needed. You can save this observation, but a balance comparison is unavailable.</p>}<label htmlFor="comparison-note">Review note (optional)<textarea id="comparison-note" rows={3} maxLength={2000} value={note} onChange={e => setNote(e.target.value)} /></label><p className="panel-note">Saving records the comparison and its audit entry. It does not change transactions or reset the opening snapshot.</p>{error && <p className="form-error" role="alert">{error}</p>}<div className="modal-footer"><button className="button secondary" type="button" onClick={onClose}>Cancel</button><button className="button primary" disabled={busy}>{busy ? 'Saving…' : 'Save comparison'}</button></div></form></Modal>;
}
