import { useEffect, useRef, useState, type FormEvent } from 'react';
import { ArrowRight, Check, ChevronDown, Trash2 } from 'lucide-react';
import { localDate, monthBudgets, validateTransaction, type Budget, type State, type Transaction, type TransactionType, type Scope } from '../shared/model';
import { inputCents, quickEntry } from '../shared/simple';
import { fundingFor } from '../shared/allocation';
import { Modal } from './components';
import { friendlyError } from './words';
export default function SimpleEntry({ state, edit, preset, initialType = 'Expense', initialScope = 'All', onClose, onSave, onRemove }: { state: State; edit?: Transaction; preset?: Partial<Transaction>; initialType?: TransactionType; initialScope?: Scope | 'All'; onClose: () => void; onSave: (t: Transaction) => Promise<void>; onRemove: (t: Transaction) => Promise<void> }) {
  const initial = edit ?? preset, accounts = state.accounts.filter(a => !a.hidden || (edit && (a.id === edit.accountId || a.id === edit.toAccountId)));
  const defaultAccount = accounts.find(a => a.id === localStorage.getItem('cash-flow-last-account') && (initialScope === 'All' || a.scope === initialScope)) ?? accounts.find(a => initialScope === 'All' || a.scope === initialScope);
  const [type, setType] = useState<TransactionType>(initial?.type ?? initialType), [amount, setAmount] = useState(initial?.amountCents ? (initial.amountCents / 100).toFixed(2) : '');
  const [accountId, setAccountId] = useState(initial?.accountId ?? defaultAccount?.id ?? ''), [toAccountId, setToAccountId] = useState(initial?.toAccountId ?? ''), [scope, setScope] = useState<Scope>(initial?.scope ?? defaultAccount?.scope ?? 'Personal');
  const [purpose, setPurpose] = useState(initial?.subcategory || ''), [category, setCategory] = useState(initial?.category || 'Miscellaneous'), [merchant, setMerchant] = useState(initial?.merchant ?? '');
  const [classification, setClassification] = useState<'Need' | 'Want'>(initial?.classification || 'Need'), [date, setDate] = useState(initial?.date ?? localDate()), [time, setTime] = useState(initial?.time ?? new Date().toTimeString().slice(0, 5)), [notes, setNotes] = useState(initial?.notes ?? '');
  const [details, setDetails] = useState(false), [suggestions, setSuggestions] = useState(false), [activeOption, setActiveOption] = useState(0), [quick, setQuick] = useState(''), [error, setError] = useState(''), [saving, setSaving] = useState(false), [removing, setRemoving] = useState(false);
  const id = useRef(edit?.id ?? crypto.randomUUID()), lock = useRef(false), amountRef = useRef<HTMLInputElement>(null), purposeRef = useRef<HTMLInputElement>(null);
  const budgets = monthBudgets(state, date.slice(0, 7), scope).sort((a, b) => state.transactions.filter(t => t.subcategory === b.label).length - state.transactions.filter(t => t.subcategory === a.label).length), options = budgets.filter(b => `${b.label} ${b.category}`.toLowerCase().includes(purpose.toLowerCase()));
  useEffect(() => { document.documentElement.dataset.entryOpen = 'true'; document.querySelector('main')?.getAnimations().forEach(a => a.cancel()); return () => { delete document.documentElement.dataset.entryOpen; }; }, []);
  function selectBudget(b?: Budget) { setPurpose(b?.label ?? 'Other'); setCategory(b?.category ?? 'Miscellaneous'); setClassification(b?.classification ?? 'Need'); const account = b?.paymentAccountId ?? (b ? fundingFor(state, b.id, date.slice(0, 7))?.paymentAccountId : ''); if (account) setAccountId(account); setSuggestions(false); }
  function selectStore(value: string) { setMerchant(value); const previous = [...state.transactions].sort((a, b) => b.date.localeCompare(a.date)).find(t => t.type === 'Expense' && t.merchant.toLowerCase() === value.toLowerCase()); if (previous) { setPurpose(previous.subcategory || 'Other'); setCategory(previous.category); setAccountId(previous.accountId); setScope(previous.scope); setClassification(previous.classification || 'Need'); } }
  function parseQuick() { try { const draft = quickEntry(quick, budgets); setAmount((draft.amountCents / 100).toFixed(2)); selectBudget(draft.budget); setMerchant(draft.merchant); setError(''); purposeRef.current?.focus(); } catch (e) { setError(friendlyError(e)); } }
  async function submit(event: FormEvent) {
    event.preventDefault(); if (lock.current) return; setError('');
    if (type === 'Expense' && !purpose.trim()) { setError('Choose what this was for.'); purposeRef.current?.focus(); return; }
    let amountCents: number; try { amountCents = inputCents(amount); if (!amountCents) throw new Error('Enter an amount greater than zero.'); } catch (e) { setError(friendlyError(e)); amountRef.current?.focus(); return; }
    lock.current = true; setSaving(true); const rect = (event.currentTarget as HTMLFormElement).querySelector('button[type="submit"]')?.getBoundingClientRect();
    try {
      const budget = budgets.find(b => b.label.toLowerCase() === purpose.toLowerCase()), destination = accounts.find(a => a.id === toAccountId);
      const result = validateTransaction({ id: id.current, type, amountCents, merchant: merchant.trim() || (type === 'Expense' ? purpose : type === 'Income' ? 'Income' : destination?.type === 'Credit card' ? 'Pay card' : 'Move money'), description: edit?.description ?? '', category: type === 'Income' ? (state.incomeSources.find(s => s.name === merchant)?.category ?? 'Employment') : budget?.category ?? category, subcategory: type === 'Expense' ? budget?.label ?? (purpose === 'Other' ? '' : purpose) : '', accountId, toAccountId, scope, classification, date, time, notes, revision: edit?.revision }, state, edit);
      await onSave({ ...result, revision: edit?.revision ?? 0 }); localStorage.setItem('cash-flow-last-account', accountId); onClose();
      if (rect) window.dispatchEvent(new CustomEvent('cash-flow-saved', { detail: { x: rect.left + rect.width / 2, y: rect.top + rect.height / 2 } }));
    } catch (e) { setError(friendlyError(e)); } finally { lock.current = false; setSaving(false); }
  }
  return <Modal title={edit ? 'Edit entry' : 'Add entry'} onClose={() => { if (!saving) onClose(); }}><form className="transaction-form simple-entry-form" onSubmit={submit}>
    <div className="segmented transaction-types">{(['Expense', 'Income', 'Transfer'] as const).map(t => <button type="button" key={t} aria-pressed={type === t} className={type === t ? 'active' : ''} onClick={() => { setType(t); setError(''); amountRef.current?.focus(); }}>{t === 'Expense' ? 'I spent' : t === 'Income' ? 'I got paid' : 'Move money'}</button>)}</div>
    <label className="amount-label" htmlFor="amount">Amount<span className="amount-input"><span aria-hidden="true">$</span><input ref={amountRef} data-autofocus id="amount" aria-label="Amount" inputMode="decimal" placeholder="0.00" value={amount} onChange={e => setAmount(e.target.value)} onBlur={() => { try { if (amount) setAmount((inputCents(amount) / 100).toFixed(2)); } catch {} }} autoComplete="off" /></span></label>
    {type === 'Expense' && <div className="purpose-field"><label htmlFor="purpose">What for<input id="purpose" ref={purposeRef} role="combobox" aria-autocomplete="list" aria-controls="purpose-list" aria-expanded={suggestions} aria-activedescendant={suggestions ? `purpose-option-${Math.min(activeOption, options.length)}` : undefined} value={purpose} placeholder="Groceries, rent, gas…" autoComplete="off" onFocus={() => { setSuggestions(true); setActiveOption(0); }} onBlur={() => setSuggestions(false)} onChange={e => { setPurpose(e.target.value); setSuggestions(true); setActiveOption(0); }} onKeyDown={e => { if (e.key === 'ArrowDown' || e.key === 'ArrowUp') { e.preventDefault(); setSuggestions(true); setActiveOption(n => Math.max(0, Math.min(options.length, n + (e.key === 'ArrowDown' ? 1 : -1)))); } if ((e.key === 'Enter' || e.key === 'Tab') && suggestions) { if (e.key === 'Enter') e.preventDefault(); const selected = options[Math.min(activeOption, options.length)]; if (purpose.trim() && selected) selectBudget(selected); else if (purpose.trim().toLowerCase() === 'other' || (purpose.trim() && options.length > 0 && activeOption === options.length)) selectBudget(); else setSuggestions(false); } if (e.key === 'Escape') { e.stopPropagation(); setSuggestions(false); } }} /></label>{suggestions && <div id="purpose-list" role="listbox" aria-label="Things in my plan" className="purpose-options">{options.map((b, index) => <button id={`purpose-option-${index}`} tabIndex={-1} role="option" aria-selected={Math.min(activeOption, options.length) === index} type="button" key={b.id} onMouseDown={e => e.preventDefault()} onClick={() => selectBudget(b)}><span>{b.label}</span><small>{b.category}</small></button>)}<button id={`purpose-option-${options.length}`} tabIndex={-1} role="option" aria-selected={Math.min(activeOption, options.length) === options.length} type="button" onMouseDown={e => e.preventDefault()} onClick={() => selectBudget()}>Other<small>Not in my plan</small></button></div>}</div>}
    {type === 'Income' && <label htmlFor="income-source">From whom<input id="income-source" list="income-sources" placeholder="Paycheck, client…" value={merchant} onChange={e => { setMerchant(e.target.value); const source = state.incomeSources.find(s => s.name === e.target.value); if (source) { setAccountId(source.defaultAccountId); setScope(source.scope); } }} /><datalist id="income-sources">{state.incomeSources.map(s => <option key={s.id} value={s.name} />)}</datalist></label>}
    <label htmlFor="account">{type === 'Transfer' ? 'From account' : type === 'Income' ? 'Paid into' : 'Paid from'}<select id="account" value={accountId} required onChange={e => { setAccountId(e.target.value); setScope(accounts.find(a => a.id === e.target.value)!.scope); }}><option value="" disabled>Choose account</option>{accounts.map(a => <option key={a.id} value={a.id}>{a.name} · {a.lastFour}{a.hidden ? ' · Hidden' : ''}</option>)}</select></label>
    {type === 'Transfer' && <label htmlFor="to-account">To account<select id="to-account" value={toAccountId} required onChange={e => setToAccountId(e.target.value)}><option value="" disabled>Choose account</option>{accounts.filter(a => a.id !== accountId).map(a => <option key={a.id} value={a.id}>{a.name} · {a.lastFour}{a.hidden ? ' · Hidden' : ''}</option>)}</select></label>}
    {error && <p className="form-error" role="alert">{error}</p>}<div className="modal-footer"><button className="button primary" type="submit" disabled={saving}>{saving ? 'Saving…' : edit ? 'Save changes' : type === 'Transfer' && accounts.find(a => a.id === toAccountId)?.type === 'Credit card' ? 'Pay card' : 'Save'}<Check size={16} /></button></div>
    <button className="text-button more-options" type="button" aria-expanded={details} onClick={() => setDetails(!details)}>More options<ChevronDown size={15} /></button>
    {details && <div className="extra-details">{!edit && type === 'Expense' && <div className="quick-entry"><input aria-label="Quick entry" placeholder="Try 5 grocery heb" value={quick} onChange={e => setQuick(e.target.value)} onKeyDown={e => { if (e.key === 'Enter') { e.preventDefault(); parseQuick(); } }} /><button type="button" aria-label="Fill from quick entry" onClick={parseQuick}><ArrowRight size={17} /></button></div>}{type === 'Expense' && <label htmlFor="merchant">Store (optional)<input id="merchant" list="stores" value={merchant} onChange={e => selectStore(e.target.value)} maxLength={200} /><datalist id="stores">{[...new Set(state.transactions.filter(t => t.type === 'Expense').map(t => t.merchant))].map(s => <option key={s} value={s} />)}</datalist></label>}<div className="form-grid"><label htmlFor="date">Date<input id="date" type="date" value={date} onChange={e => setDate(e.target.value)} required /></label><label htmlFor="time">Time<input id="time" type="time" value={time} onChange={e => setTime(e.target.value)} required /></label></div><label htmlFor="notes">Note<textarea id="notes" value={notes} maxLength={2000} onChange={e => setNotes(e.target.value)} /></label><div className="form-grid"><label>Personal or Business<select value={scope} onChange={e => setScope(e.target.value as Scope)}><option>Personal</option><option>Business</option></select></label>{type === 'Expense' && <label>Need or Want<select value={classification} onChange={e => setClassification(e.target.value as 'Need' | 'Want')}><option>Need</option><option>Want</option></select></label>}</div></div>}

    {edit && <div className="remove-entry">{removing ? <><p>Remove this entry? Your balances will update.</p><button type="button" className="button secondary" disabled={saving} onClick={async () => { if (lock.current) return; lock.current = true; setSaving(true); try { await onRemove(edit); onClose(); } catch (e) { setError(friendlyError(e)); } finally { lock.current = false; setSaving(false); } }}>Remove entry</button><button className="text-button" type="button" onClick={() => setRemoving(false)}>Keep entry</button></> : <button type="button" className="text-button" onClick={() => setRemoving(true)}><Trash2 size={14} />Remove entry</button>}</div>}
  </form></Modal>;
}
