import { useRef, useState, type FormEvent, type ReactNode } from 'react';
import { Check, ArrowRight } from 'lucide-react';
import { money, monthIncome, scopedTransactions, type Account, type Budget, type Scope, type State } from '../shared/model';
import { currentBalance, fundingFor, localMinute } from '../shared/allocation';
import { accountChecked, inputCents, visibleAccounts } from '../shared/simple';
import { accountReconciliations, reconciliationFingerprint } from '../shared/reconciliation';
import { Modal, monthLabel } from './components';
import { EntryRows } from './SimpleViews';

function SaveForm({ children, onSave, onClose, label = 'Save' }: { children: ReactNode; onSave: () => Promise<void>; onClose: () => void; label?: string }) {
  const [error, setError] = useState(''), [busy, setBusy] = useState(false), lock = useRef(false);
  async function submit(e: FormEvent) { e.preventDefault(); if (lock.current) return; lock.current = true; setBusy(true); setError(''); try { await onSave(); onClose(); } catch (e) { setError((e as Error).message); } finally { setBusy(false); lock.current = false; } }
  return <form onSubmit={submit}>{children}{error && <p className="form-error" role="alert">{error}</p>}<div className="modal-footer"><button className="button primary" disabled={busy}>{busy ? 'Saving…' : label}<Check size={16} /></button></div></form>;
}
export function BudgetEditor({ state, budget, month, scope, onSave, onClose }: { state: State; budget?: Budget; month: string; scope: Scope | 'All'; onSave: (v: unknown) => Promise<void>; onClose: () => void }) {
  const funding = budget ? fundingFor(state, budget.id, month) : undefined;
  const [id] = useState(budget?.id ?? crypto.randomUUID()), [name, setName] = useState(budget?.label ?? ''), [amount, setAmount] = useState(budget ? (budget.amountCents / 100).toFixed(2) : ''), [category, setCategory] = useState(budget?.category ?? state.categories[0]?.name ?? ''), [owner, setOwner] = useState<Scope>(budget?.scope ?? (scope === 'All' ? 'Personal' : scope)), [due, setDue] = useState(String((budget?.dueDay !== undefined ? budget.dueDay : funding?.dueDay) ?? '')), [account, setAccount] = useState(budget?.paymentAccountId ?? funding?.paymentAccountId ?? ''), [classification, setClassification] = useState(budget?.classification ?? 'Need'), [applies, setApplies] = useState('future'), [hidden, setHidden] = useState(false);
  return <Modal title={budget ? `Edit ${budget.label}` : 'Add budget item'} onClose={onClose}><SaveForm onClose={onClose} onSave={() => onSave({ id, label: name, amountCents: inputCents(amount), category, scope: owner, dueDay: due ? Number(due) : null, paymentAccountId: account, classification, applies, startMonth: month, hidden, revision: Math.max(0, ...state.budgets.filter(b => b.id === id).map(b => b.revision ?? 0)) })}><label>Name<input data-autofocus value={name} onChange={e => setName(e.target.value)} required maxLength={100} /></label><label>Monthly amount<input inputMode="decimal" value={amount} onChange={e => setAmount(e.target.value)} required /></label><div className="form-grid"><label>Category<select value={category} onChange={e => setCategory(e.target.value)}>{state.categories.map(c => <option key={c.id}>{c.name}</option>)}</select></label><label>Personal or Business<select disabled={!!budget} value={owner} onChange={e => setOwner(e.target.value as Scope)}><option>Personal</option><option>Business</option></select></label></div><div className="form-grid"><label>Due day (optional)<input type="number" min={1} max={31} value={due} onChange={e => setDue(e.target.value)} placeholder="1–31" /></label><label>Need or Want<select value={classification} onChange={e => setClassification(e.target.value as 'Need' | 'Want')}><option>Need</option><option>Want</option></select></label></div><label>Paid from<select value={account} onChange={e => setAccount(e.target.value)}><option value="">Choose when I pay</option>{visibleAccounts(state, 'All').map(a => <option key={a.id} value={a.id}>{a.name} · {a.lastFour}</option>)}</select></label><label>Apply change<select value={applies} onChange={e => setApplies(e.target.value)}><option value="future">From {monthLabel(month)} on</option><option value="once">Only {monthLabel(month)}</option></select></label>{budget && <label className="check-label"><input type="checkbox" checked={hidden} onChange={e => setHidden(e.target.checked)} />Hide this item; keep its history</label>}</SaveForm></Modal>;
}
export function IncomeEditor({ state, scope, month, onSave, onClose }: { state: State; scope: Scope | 'All'; month: string; onSave: (v: unknown) => Promise<void>; onClose: () => void }) {
  const [owner, setOwner] = useState<Scope>(scope === 'All' ? 'Personal' : scope), current = monthIncome(state, month, owner)[0], [amount, setAmount] = useState(((current?.amountCents ?? 0) / 100).toFixed(2)), [applies, setApplies] = useState('future');
  return <Modal title="Expected income" onClose={onClose}><SaveForm onClose={onClose} onSave={() => onSave({ id: current?.id ?? `income-${owner.toLowerCase()}`, scope: owner, amountCents: inputCents(amount), startMonth: month, applies, revision: Math.max(0, ...state.income.filter(i => i.id === current?.id).map(i => i.revision ?? 0)) })}><label>Personal or Business<select value={owner} onChange={e => { const next = e.target.value as Scope; setOwner(next); setAmount(((monthIncome(state, month, next)[0]?.amountCents ?? 0) / 100).toFixed(2)); }}><option>Personal</option><option>Business</option></select></label><label>Monthly amount<input data-autofocus inputMode="decimal" value={amount} onChange={e => setAmount(e.target.value)} required /></label><label>Apply change<select value={applies} onChange={e => setApplies(e.target.value)}><option value="future">From {monthLabel(month)} on</option><option value="once">Only {monthLabel(month)}</option></select></label></SaveForm></Modal>;
}
export function AccountEditor({ account, scope, onSave, onClose }: { account?: Account; scope: Scope | 'All'; onSave: (v: unknown) => Promise<void>; onClose: () => void }) {
  const [id] = useState(account?.id ?? crypto.randomUUID()), [name, setName] = useState(account?.name ?? ''), [lastFour, setLastFour] = useState(account?.lastFour ?? ''), [type, setType] = useState(account?.type ?? 'Checking'), [owner, setOwner] = useState<Scope>(account?.scope ?? (scope === 'All' ? 'Personal' : scope)), [hidden, setHidden] = useState(account?.hidden ?? false);
  return <Modal title={account ? 'Edit account' : 'Add account'} onClose={onClose}><SaveForm onClose={onClose} onSave={() => onSave({ id, name, lastFour, type, scope: owner, hidden, revision: account?.revision ?? 0 })}><label>Name<input data-autofocus value={name} onChange={e => setName(e.target.value)} required maxLength={100} /></label><label>Last four digits<input inputMode="numeric" pattern="[0-9]{4}" maxLength={4} value={lastFour} onChange={e => setLastFour(e.target.value)} required /></label><label>Type<select value={type} onChange={e => setType(e.target.value as Account['type'])}><option>Checking</option><option>Savings</option><option>Credit card</option></select></label><label>Personal or Business<select value={owner} onChange={e => setOwner(e.target.value as Scope)}><option>Personal</option><option>Business</option></select></label>{account && <label className="check-label"><input type="checkbox" checked={hidden} onChange={e => setHidden(e.target.checked)} />Hide account; keep its history</label>}</SaveForm></Modal>;
}
export function BankCheck({ state, scope, initialAccount, onSave, onClose, onMissing, onEdit }: { state: State; scope: Scope | 'All'; initialAccount?: Account; onSave: (v: unknown) => Promise<void>; onClose: () => void; onMissing: (a: Account) => void; onEdit: (t: State['transactions'][number]) => void }) {
  const accounts = visibleAccounts(state, scope), [selected, setSelected] = useState(initialAccount?.id ?? accounts.find(a => !accountChecked(state, a))?.id ?? accounts[0]?.id), account = state.accounts.find(a => a.id === selected);
  const [actual, setActual] = useState(''), [error, setError] = useState(''), [busy, setBusy] = useState(false), [done, setDone] = useState(false), lock = useRef(false);
  const now = localMinute(), calculated = account ? currentBalance(state, account) : null;
  let value: number | null = null; try { if (actual) value = actual.startsWith('-') ? -inputCents(actual.slice(1)) : inputCents(actual); } catch {}
  const difference = value !== null && calculated !== null ? value - calculated : null;
  async function save(fix: boolean) { if (!account || value === null || lock.current) return; lock.current = true; setBusy(true); setError(''); try { await onSave({ id: crypto.randomUUID(), accountId: account.id, asOf: now, timezoneOffset: new Date().getTimezoneOffset(), actualBalanceCents: value, ledgerFingerprint: reconciliationFingerprint(state, account, now), fix }); const next = accounts.find(a => a.id !== account.id && !accountChecked(state, a)); if (next) { setSelected(next.id); setActual(''); } else setDone(true); } catch (e) { setError((e as Error).message); } finally { lock.current = false; setBusy(false); } }
  const last = account ? accountReconciliations(state, account.id)[0] : undefined;
  const entries = account ? scopedTransactions(state, '', 'All').filter(t => (t.accountId === account.id || t.toAccountId === account.id) && (!last || `${t.date}T${t.time}` >= last.asOf)) : [];
  return <Modal title="Check my bank" onClose={onClose}>{done ? <div className="bank-complete"><Check size={32} /><h2>Done today</h2><p>Your balances match.</p><button className="button primary" onClick={onClose}>Done</button></div> : !account ? <p>No accounts here yet. Add one in Accounts.</p> : <><label>Account<select value={selected} onChange={e => { setSelected(e.target.value); setActual(''); }}>{accounts.map(a => <option key={a.id} value={a.id}>{a.name} · {a.lastFour}{accountChecked(state, a) ? ' · Checked' : ''}</option>)}</select></label><div className="bank-app-balance"><span>{account.type === 'Credit card' ? 'Card balance in this app' : 'Balance in this app'}</span><strong>{calculated === null ? 'Add a starting balance' : money(calculated)}</strong></div><label htmlFor="bank-amount">{account.type === 'Credit card' ? 'Amount owed in your bank app' : 'Balance in your bank app'}<input data-autofocus id="bank-amount" inputMode="decimal" value={actual} onChange={e => setActual(e.target.value)} placeholder="0.00" /></label>{value !== null && <><p className={difference === 0 ? 'positive bank-result' : 'bank-result'}>{difference === 0 ? 'Matches' : difference === null ? 'Use this as your starting balance.' : `Off by ${money(Math.abs(difference))}`}</p>{difference !== 0 && calculated !== null && <><details className="bank-entries"><summary>Entries since your last check ({entries.length})</summary><EntryRows state={state} entries={entries} onEdit={onEdit} empty="No entries since your last check." /></details><button className="button secondary" onClick={() => onMissing(account)}>Add missing entry</button></>}<div className="modal-footer"><button className="button primary" disabled={busy} onClick={() => void save(difference !== 0)}>{busy ? 'Saving…' : difference === 0 ? 'Matches · Next' : calculated === null ? 'Save starting balance' : 'Bank is right, fix balance'}<ArrowRight size={16} /></button></div></>}{error && <p className="form-error" role="alert">{error}</p>}</>}</Modal>;
}
