import { useState, type ReactNode } from 'react';
import { ArrowDownLeft, ArrowUpRight, ArrowLeftRight, ArrowRight, ChevronDown, Plus, Pencil, Check, Wallet, Search, SlidersHorizontal } from 'lucide-react';
import { accountFlows, budgetSpent, currentMonth, localDate, money, monthBudgets, monthIncome, scopedTransactions, summarize, type Account, type Budget, type Scope, type State, type Transaction } from '../shared/model';
import { currentBalance, fundingFor } from '../shared/allocation';
import { accountChecked, balanceSummary, periodEntries, visibleAccounts } from '../shared/simple';
import { WaterWave } from './WaterTheme';
import { Modal, Progress, monthLabel } from './components';
type Props = { state: State; scope: Scope | 'All' };
export function EntryRows({ state, entries, onEdit, empty = 'Nothing logged today yet.' }: { state: State; entries: Transaction[]; onEdit: (t: Transaction) => void; empty?: string }) {
  return <div className="simple-entries">{entries.length ? entries.map(t => { const account = state.accounts.find(a => a.id === t.accountId), destination = state.accounts.find(a => a.id === t.toAccountId); const Icon = t.type === 'Income' ? ArrowDownLeft : t.type === 'Transfer' ? ArrowLeftRight : ArrowUpRight; return <button key={t.id} className={`entry-row ${t.type.toLowerCase()}`} onClick={() => onEdit(t)}><span className="entry-symbol"><Icon size={18} /></span><span className="entry-copy"><strong>{t.merchant || t.subcategory || (t.type === 'Transfer' ? 'Move money' : 'Entry')}</strong><small>{t.type === 'Transfer' ? `${account?.name} → ${destination?.name}` : `${t.subcategory || t.category} · ${account?.type}`} {account?.lastFour && `· ${account.lastFour}`}</small></span><span className="entry-amount">{t.type === 'Income' ? '+' : t.type === 'Transfer' ? '' : '−'}{money(t.amountCents)}<ArrowRight size={13} /></span></button>; }) : <p className="quiet-empty">{empty}</p>}</div>;
}
export function EntriesDialog({ title, entries, state, onEdit, onClose }: { title: string; entries: Transaction[]; state: State; onEdit: (t: Transaction) => void; onClose: () => void }) {
  return <Modal title={title} onClose={onClose}><EntryRows state={state} entries={entries} onEdit={onEdit} empty="Nothing logged for this view yet." /></Modal>;
}
export function Metric({ label, value, note, onClick }: { label: string; value: string; note?: string; onClick?: () => void }) {
  const content = <><span>{label}{onClick && <ArrowUpRight size={15} />}</span><strong>{value}</strong>{note && <small>{note}</small>}</>;
  return onClick ? <button className="simple-metric" onClick={onClick}>{content}</button> : <div className="simple-metric">{content}</div>;
}
export function HomeView({ state, scope, onEdit, onAccounts, onBudget, onBank, onAdd, onEntries }: Props & { onEdit: (t: Transaction) => void; onAccounts: () => void; onBudget: () => void; onBank: (account?: Account) => void; onAdd: (type: Transaction['type']) => void; onEntries: (title: string, entries: Transaction[]) => void }) {
  const month = currentMonth(), entries = scopedTransactions(state, month, scope), totals = summarize(entries), today = periodEntries(state, scope, 'today'), todayAll = entries.filter(t => t.date === localDate()), balance = balanceSummary(state, scope), planned = monthBudgets(state, month, scope).reduce((n, b) => n + b.amountCents, 0), accounts = visibleAccounts(state, scope), done = accounts.length > 0 && accounts.every(a => accountChecked(state, a));
  return <div className="simple-home">
    <section className="cash-surface"><div className="cash-heading"><span>Cash I have</span><span className="eyebrow">{scope === 'All' ? 'All accounts' : scope}</span></div><button className="cash-number" onClick={onAccounts}><span>{money(balance.cash)}</span><ArrowUpRight size={23} /></button><button className="cash-cards" onClick={onAccounts}>Credit cards owed <strong>{money(balance.cards)}</strong></button>{balance.missing.length > 0 && <details className="missing-balances"><summary>{balance.missing.length} {balance.missing.length === 1 ? 'balance' : 'balances'} to add <ChevronDown size={14} /></summary>{balance.missing.map(a => <button className="text-button" key={a.id} onClick={() => onBank(a)}>Add balance for {a.name}<ArrowRight size={14} /></button>)}</details>}<WaterWave /></section>
    <div className="quick-actions"><button onClick={() => onAdd('Expense')}><ArrowUpRight size={18} />Spent</button><button onClick={() => onAdd('Income')}><ArrowDownLeft size={18} />Got paid</button><button onClick={() => onAdd('Transfer')}><ArrowLeftRight size={18} />Move money</button></div>
    <button className="month-strip" onClick={onBudget}><span className="section-caption">This month <ArrowRight size={16} /></span><span className="month-amount"><strong>{money(totals.expenses)}</strong> of {money(planned)} budget</span><Progress value={planned ? totals.expenses / planned * 100 : 0} /><span className="split"><span className={planned < totals.expenses ? 'negative' : ''}>{money(planned - totals.expenses)} left</span><span>Received {money(totals.income)}</span></span></button>
    <section className="simple-section"><div className="section-head"><h2>Today</h2><button className="text-button" onClick={() => onEntries('Spent today', today)}>{money(summarize(today).expenses)} spent<ArrowRight size={14} /></button></div><EntryRows state={state} entries={todayAll} onEdit={onEdit} /></section>
    <button className={`bank-strip ${done ? 'done' : ''}`} onClick={() => onBank()}><span className="entry-symbol">{done ? <Check size={20} /> : <Wallet size={20} />}</span><span><strong>{done ? 'Done today' : 'Check my bank'}</strong><small>{done ? 'Your balances match.' : 'A quick balance check, one account at a time.'}</small></span><ArrowRight size={18} /></button>
  </div>;
}
export function ActivityView({ state, month, scope, onEdit, presetDate = '' }: Props & { month: string; onEdit: (t: Transaction) => void; presetDate?: string }) {
  const [search, setSearch] = useState(''), [type, setType] = useState('All'), [day, setDay] = useState(presetDate);
  const entries = scopedTransactions(state, month, scope), totals = summarize(entries), filtered = entries.filter(t => (type === 'All' || t.type === type) && (!day || t.date === day) && `${t.merchant} ${t.description} ${t.subcategory} ${t.category} ${state.accounts.find(a => a.id === t.accountId)?.name}`.toLowerCase().includes(search.toLowerCase()));
  return <><div className="simple-metrics two"><Metric label="Spent this month" value={money(totals.expenses)} onClick={() => setType('Expense')} /><Metric label="Got paid this month" value={money(totals.income)} onClick={() => setType('Income')} /></div><div className="activity-tools"><label className="search-box"><Search size={18} /><input aria-label="Search activity" placeholder="Find an entry" value={search} onChange={e => setSearch(e.target.value)} /></label><select aria-label="Activity type" value={type} onChange={e => setType(e.target.value)}><option value="All">All entries</option><option value="Expense">Spent</option><option value="Income">Got paid</option><option value="Transfer">Moved</option></select></div>{day && <button className="text-button" onClick={() => setDay('')}>Showing {day} · Show whole month</button>}<div className="activity-days">{[...new Set(filtered.map(t => t.date))].map(date => { const group = filtered.filter(t => t.date === date); return <section key={date} className="simple-section"><div className="section-head"><h2>{new Date(`${date}T12:00:00`).toLocaleDateString(undefined, { weekday: 'short', month: 'short', day: 'numeric' })}</h2><small>{money(summarize(group).expenses)} spent</small></div><EntryRows state={state} entries={group} onEdit={onEdit} /></section>; })}{!filtered.length && <p className="quiet-empty">No entries here yet.</p>}</div></>;
}
export function BudgetList({ state, month, scope, onEdit, onIncome, onAdd, onPay, onEntries }: Props & { month: string; onEdit: (b: Budget) => void; onIncome: () => void; onAdd: () => void; onPay: (b: Budget) => void; onEntries: (title: string, entries: Transaction[]) => void }) {
  const budgets = monthBudgets(state, month, scope), entries = scopedTransactions(state, month, scope), spent = summarize(entries).expenses, total = budgets.reduce((n, b) => n + b.amountCents, 0), expected = monthIncome(state, month, scope).reduce((n, i) => n + i.amountCents, 0);
  return <><div className="simple-metrics"><Metric label="Expected income" value={money(expected)} onClick={onIncome} /><Metric label="Budget total" value={money(total)} note={`${budgets.length} items`} /><Metric label="Left after budget" value={money(expected - total)} /></div><button className="budget-overview" onClick={() => onEntries('Spent this month', entries.filter(t => t.type === 'Expense'))}><span>{money(spent)} spent so far</span><strong className={total < spent ? 'negative' : ''}>{money(total - spent)} left to spend<ArrowRight size={15} /></strong><Progress value={total ? spent / total * 100 : 0} /></button><div className="section-head"><h2>Your budget</h2><button className="text-button" onClick={onAdd}><Plus size={16} />Add item</button></div><div className="budget-groups">{[...new Set(budgets.map(b => b.category))].map(category => { const items = budgets.filter(b => b.category === category), planned = items.reduce((n, b) => n + b.amountCents, 0), used = items.reduce((n, b) => n + budgetSpent(b, entries), 0); return <details key={category} className="simple-disclosure budget-group"><summary><span className="category-dot" /><span className="disclosure-title">{category}<small>{items.length} {items.length === 1 ? 'item' : 'items'}</small></span><span className="disclosure-amount">{money(planned - used)}<small>left of {money(planned)}</small></span><ChevronDown size={18} /></summary><div className="budget-items">{items.map(b => { const used = budgetSpent(b, entries), funding = fundingFor(state, b.id, month), due = b.dueDay !== undefined ? b.dueDay : funding?.dueDay, paid = used >= b.amountCents && used > 0; return <details className="budget-item" key={b.id}><summary><span><strong>{b.label}</strong>{due && <small>{paid ? 'Paid' : `Due ${due}`}</small>}</span><span>{money(b.amountCents - used)} left<ChevronDown size={15} /></span></summary><div className="budget-item-body"><div className="budget-values"><span>Budget<strong>{money(b.amountCents)}</strong></span><button onClick={() => onEntries(b.label, entries.filter(t => budgetSpent(b, [t]) > 0))}>Spent<strong>{money(used)}<ArrowUpRight size={12} /></strong></button><span>Left<strong className={used > b.amountCents ? 'negative' : ''}>{money(b.amountCents - used)}</strong></span></div><Progress value={b.amountCents ? used / b.amountCents * 100 : 0} /><div className="row-actions"><button className="text-button" onClick={() => onEdit(b)}><Pencil size={14} />Edit</button>{due && paid ? <span className="positive"><Check size={14} />Paid</span> : <button className="button secondary" onClick={() => onPay(b)}>{due ? 'Pay bill' : 'Add spending'}<Plus size={14} /></button>}</div></div></details>; })}</div></details>; })}{!budgets.length && <p className="quiet-empty">Start with the things you spend on each month.</p>}</div></>;
}
export function AccountsList({ state, scope, onBank, onEdit, onAdd, onEntries }: Props & { onBank: (a?: Account) => void; onEdit: (a: Account) => void; onAdd: () => void; onEntries: (title: string, entries: Transaction[]) => void }) {
  const balance = balanceSummary(state, scope), entries = scopedTransactions(state, currentMonth(), 'All');
  return <><div className="simple-metrics two"><Metric label="Cash" value={money(balance.cash)} note={balance.missing.some(a => a.type !== 'Credit card') ? 'Some balances still to add' : 'Checking & savings'} /><Metric label="Credit cards owed" value={money(balance.cards)} note={balance.missing.some(a => a.type === 'Credit card') ? 'Some balances still to add' : undefined} /></div><div className="section-head"><button className="button primary" onClick={() => onBank()}>Check my bank<ArrowRight size={16} /></button><button className="text-button" onClick={onAdd}><Plus size={16} />Add account</button></div>{(['Personal', 'Business'] as const).filter(s => scope === 'All' || scope === s).map(s => <details className="simple-disclosure account-group" key={s} open={scope !== 'All' ? true : undefined}><summary><span className="disclosure-title">{s}<small>{visibleAccounts(state, s).length} accounts</small></span><ChevronDown size={18} /></summary><div className="account-rows">{visibleAccounts(state, s).map(a => { const current = currentBalance(state, a), flows = accountFlows(a.id, entries); return <details className="account-row" key={a.id}><summary><span className="entry-symbol"><Wallet size={18} /></span><span className="disclosure-title">{a.name}<small>{a.type} · {a.lastFour}</small></span><span className="disclosure-amount">{current === null ? 'Add balance' : money(current)}</span><ChevronDown size={16} /></summary><div className="account-expanded"><div className="account-flow"><button onClick={() => onEntries(`${a.name} · money in`, entries.filter(t => (t.type === 'Income' && t.accountId === a.id) || (t.type === 'Transfer' && t.toAccountId === a.id)))}>In this month<strong>{money(flows.inflows)}<ArrowUpRight size={13} /></strong></button><button onClick={() => onEntries(`${a.name} · money out`, entries.filter(t => t.type !== 'Income' && t.accountId === a.id))}>Out this month<strong>{money(flows.outflows)}<ArrowUpRight size={13} /></strong></button></div><div className="row-actions"><button className="text-button" onClick={() => onEdit(a)}><Pencil size={14} />Edit account</button><button className="button secondary" onClick={() => onBank(a)}>{current === null ? 'Add starting balance' : 'Check my bank'}<ArrowRight size={14} /></button></div></div></details>; })}{!visibleAccounts(state, s).length && <p className="quiet-empty">No accounts here yet.</p>}</div></details>)}</>;
}
export function SpendingButtons({ state, scope, onEntries }: Props & { onEntries: (title: string, entries: Transaction[]) => void }) {
  return <div className="simple-metrics">{(['today', 'week', 'month'] as const).map(period => { const entries = periodEntries(state, scope, period), title = `Spent ${period === 'today' ? 'today' : `this ${period}`}`; return <Metric key={period} label={title} value={money(summarize(entries).expenses)} onClick={() => onEntries(title, entries)} />; })}</div>;
}
