// Generated by scripts/build-server.mjs. Edit server/shared sources, then rebuild. No environment values are embedded.

// server/app.ts
import "dotenv/config";
import express from "express";
import { createHmac, randomBytes as randomBytes2, randomUUID, timingSafeEqual } from "node:crypto";
import path from "node:path";
import { fileURLToPath } from "node:url";

// server/storage.ts
import { AsyncLocalStorage as AsyncLocalStorage2 } from "node:async_hooks";

// server/sheets.ts
import { JWT } from "google-auth-library";

// server/credentials.ts
import { readFileSync } from "node:fs";
var serviceAccountConfigured = () => Boolean(process.env.FIREBASE_SERVICE_ACCOUNT_JSON || process.env.FIREBASE_SERVICE_ACCOUNT_PATH);
function readFirebaseServiceAccount() {
  let credential;
  try {
    const text3 = process.env.FIREBASE_SERVICE_ACCOUNT_JSON || readFileSync(process.env.FIREBASE_SERVICE_ACCOUNT_PATH, "utf8");
    credential = JSON.parse(text3.replace(/^\uFEFF/, ""));
  } catch {
    throw new Error("The private Firebase credential could not be read. Set its server JSON variable or local file path.");
  }
  const data = credential;
  if (!data || Array.isArray(data) || typeof data.project_id !== "string" || !data.project_id || typeof data.client_email !== "string" || !data.client_email || typeof data.private_key !== "string" || !data.private_key) {
    throw new Error("The private Firebase credential is not a valid service-account JSON object.");
  }
  if (process.env.FIREBASE_PROJECT_ID && data.project_id !== process.env.FIREBASE_PROJECT_ID) throw new Error("The Firebase credential belongs to a different project.");
  return { project_id: data.project_id, client_email: data.client_email, private_key: data.private_key };
}

// server/sheets.ts
import { randomBytes, randomInt } from "node:crypto";

// shared/seed.ts
function initialState() {
  const plans = [
    ["Housing", "Rent", 121e3],
    ["Housing", "Rent Insurance", 1700],
    ["Transportation", "Car Payment", 35e3],
    ["Transportation", "Car Insurance", 16e3],
    ["Transportation", "Gas", 1e4],
    ["Utilities", "Utility", 5e3],
    ["Utilities", "Phone", 4500],
    ["Utilities", "Internet", 7030],
    ["Subscriptions / AI", "YouTube", 1700],
    ["Subscriptions / AI", "LLM", 5e3],
    ["Family", "Hudson Travel", 15e3],
    ["Family", "Mommy", 1e4],
    ["Food", "Grocery", 25e3]
  ];
  return {
    accounts: [
      { id: "capital-one-checking", name: "Capital One Personal Checking", lastFour: "1637", scope: "Personal", type: "Checking", balanceCents: null, balanceUpdatedAt: null },
      { id: "capital-one-savings", name: "Capital One Personal Savings", lastFour: "1767", scope: "Personal", type: "Savings", balanceCents: null, balanceUpdatedAt: null },
      { id: "capital-one-savor", name: "Capital One Savor Credit Card", lastFour: "1567", scope: "Personal", type: "Credit card", balanceCents: null, balanceUpdatedAt: null },
      { id: "chase-savings", name: "Chase Business Savings", lastFour: "0366", scope: "Business", type: "Savings", balanceCents: null, balanceUpdatedAt: null },
      { id: "chase-unlimited", name: "Chase Business Unlimited Credit Card", lastFour: "9398", scope: "Business", type: "Credit card", balanceCents: null, balanceUpdatedAt: null }
    ],
    categories: [...new Set(plans.map(([category]) => category).concat(["Employment", "Business income", "Miscellaneous"]))].map((name, i) => ({ id: `category-${i + 1}`, name })),
    budgets: plans.map(([category, label, amountCents], i) => ({ id: `budget-${i + 1}`, label, category, amountCents, scope: "Personal", month: "*" })),
    income: [{ id: "planned-income", label: "Budgeted monthly income", amountCents: 26e4, scope: "Personal", month: "*" }],
    transactions: [],
    audit: [],
    notesReminders: [],
    dailyCheckIns: [],
    leakReviews: [],
    expenseFunding: [],
    settings: [],
    monthReviews: [],
    balanceReconciliations: [],
    incomeSources: [{ id: "employment", name: "Employment", scope: "Personal", category: "Employment", defaultAccountId: "capital-one-checking", revision: 1, updatedAt: "" }]
  };
}

// server/sheets.ts
var headers = {
  accounts: ["id", "name", "lastFour", "scope", "type", "balanceCents", "balanceUpdatedAt", "balanceIncludedTransactionIds", "balanceAsOf", "hidden", "revision"],
  categories: ["id", "name"],
  budgets: ["id", "label", "category", "amountCents", "scope", "month", "dueDay", "paymentAccountId", "classification", "hidden", "revision", "aliases"],
  income: ["id", "label", "amountCents", "scope", "month", "revision"],
  transactions: ["id", "date", "time", "type", "amountCents", "category", "subcategory", "merchant", "description", "accountId", "toAccountId", "scope", "classification", "notes", "createdAt", "updatedAt", "revision", "voided"],
  audit: ["id", "entity", "entityId", "at", "before", "after"],
  notesReminders: ["id", "title", "note", "category", "relatedExpenseId", "relatedAccountId", "scope", "priority", "status", "reminderDate", "amountAffectedCents", "previousCostCents", "newCostCents", "monthlySavingsCents", "annualizedSavingsCents", "createdAt", "completedAt", "updatedAt", "revision"],
  dailyCheckIns: ["id", "date", "scope", "confirmedAt", "transactionFingerprint", "revision", "completed", "completedAt", "transactionsReviewed"],
  leakReviews: ["id", "month", "dismissedAt"],
  expenseFunding: ["id", "budgetId", "month", "paymentAccountId", "amountCents", "dueDay", "autopay", "updatedAt", "revision"],
  incomeSources: ["id", "name", "scope", "category", "defaultAccountId", "updatedAt", "revision"],
  settings: ["id", "reminderTime", "smallPurchaseThresholdCents", "updatedAt", "revision"],
  monthReviews: ["id", "month", "scope", "note", "nextMonth", "createdAt", "updatedAt", "revision"],
  balanceReconciliations: ["id", "accountId", "accountType", "asOf", "actualBalanceCents", "openingBalanceCents", "openingAsOf", "moneyInCents", "moneyOutCents", "calculatedBalanceCents", "differenceCents", "ledgerFingerprint", "note", "createdAt", "updatedAt", "revision"]
};
var names = Object.keys(headers);
var sheetName = (table) => ({ notesReminders: "Notes_Reminders", dailyCheckIns: "Daily_Checkins", leakReviews: "Leak_Reviews", expenseFunding: "Expense_Funding", incomeSources: "Income_Sources", settings: "Settings", monthReviews: "Month_Reviews", balanceReconciliations: "Balance_Reconciliations" })[table] ?? table;
var columnName = (table, name) => !["accounts", "categories", "budgets", "income", "transactions", "audit"].includes(table) ? name.replace(/[A-Z]/g, (c) => `_${c.toLowerCase()}`) : name;
var sheetHeaders = (table) => headers[table].map((name) => columnName(table, name));
var ids = {};
var initialized;
var queue = Promise.resolve();
var configured = () => Boolean(process.env.GOOGLE_SHEET_ID && process.env.GOOGLE_SERVICE_ACCOUNT_EMAIL && process.env.GOOGLE_PRIVATE_KEY);
var reportsConfigured = () => Boolean(process.env.GOOGLE_SHEET_ID && (configured() || serviceAccountConfigured()));
var client = () => {
  let email = process.env.GOOGLE_SERVICE_ACCOUNT_EMAIL, key = process.env.GOOGLE_PRIVATE_KEY?.replace(/\\n/g, "\n");
  if ((!email || !key) && serviceAccountConfigured()) {
    const credential = readFirebaseServiceAccount();
    email = credential.client_email;
    key = credential.private_key;
  }
  return new JWT({ email, key, scopes: ["https://www.googleapis.com/auth/spreadsheets"] });
};
var auth;
async function request(path2, body) {
  auth ??= client();
  const token = await auth.getAccessToken();
  const response = await fetch(`https://sheets.googleapis.com/v4/spreadsheets/${encodeURIComponent(process.env.GOOGLE_SHEET_ID)}${path2}`, {
    method: body ? "POST" : "GET",
    headers: { Authorization: `Bearer ${token.token}`, "Content-Type": "application/json" },
    body: body ? JSON.stringify(body) : void 0,
    signal: AbortSignal.timeout(3e4)
  });
  if (!response.ok) {
    console.error("Sheets request failed:", response.status);
    throw new Error("Google Sheets could not complete the request. Check the service account access and spreadsheet setup.");
  }
  return response.json();
}
function cells(values) {
  return { values: values.map((value) => ({ userEnteredValue: typeof value === "number" ? { numberValue: value } : typeof value === "boolean" ? { boolValue: value } : { stringValue: value == null ? "" : typeof value === "object" ? JSON.stringify(value) : String(value) } })) };
}
function append(table, records) {
  return { appendCells: { sheetId: ids[table], fields: "userEnteredValue", rows: records.map((record) => cells(headers[table].map((h) => record[h]))) } };
}
async function initialize() {
  const meta = await request("?fields=sheets.properties");
  for (const sheet of meta.sheets ?? []) {
    const table = names.find((table2) => sheetName(table2) === sheet.properties.title);
    if (table) ids[table] = sheet.properties.sheetId;
  }
  const missing = names.filter((n) => ids[n] === void 0);
  if (missing.length) {
    const result = await request(":batchUpdate", { requests: missing.map((table) => ({ addSheet: { properties: { title: sheetName(table), gridProperties: { frozenRowCount: 1 } } } })) });
    result.replies.forEach((reply) => {
      const table = names.find((table2) => sheetName(table2) === reply.addSheet.properties.title);
      ids[table] = reply.addSheet.properties.sheetId;
    });
  }
  const seed = initialState();
  const ranges = names.map((n) => `ranges=${encodeURIComponent(`${sheetName(n)}!A1:Z1`)}`).join("&");
  const existing = await request(`/values:batchGet?${ranges}`);
  const writes = [];
  names.forEach((table, i) => {
    const row = existing.valueRanges[i]?.values?.[0] ?? [];
    const legacyLengths = { dailyCheckIns: [6], accounts: [7, 9], transactions: [17], budgets: [6], income: [5] };
    const legacyLength = legacyLengths[table]?.includes(row.length) ? row.length : 0;
    if (legacyLength && row.length === legacyLength && row.join("|") === sheetHeaders(table).slice(0, legacyLength).join("|")) {
      writes.push({ updateCells: { start: { sheetId: ids[table], rowIndex: 0, columnIndex: legacyLength }, fields: "userEnteredValue", rows: [cells(sheetHeaders(table).slice(legacyLength))] } });
    } else if (row.length && row.join("|") !== sheetHeaders(table).join("|")) throw new Error(`The ${sheetName(table)} sheet has an incompatible header. Existing data has not been overwritten; review the header before retrying.`);
    if (!row.length) {
      writes.push({ appendCells: { sheetId: ids[table], fields: "userEnteredValue", rows: [cells(sheetHeaders(table))] } });
      if (seed[table].length) writes.push(append(table, seed[table]));
    }
  });
  if (writes.length) await request(":batchUpdate", { requests: writes });
}
async function ready() {
  if (!configured()) throw new Error("Google Sheets is not configured.");
  initialized ??= initialize().catch((error) => {
    initialized = void 0;
    throw error;
  });
  await initialized;
}
async function readState() {
  await ready();
  const ranges = names.map((n) => `ranges=${encodeURIComponent(`${sheetName(n)}!A2:Z`)}`).join("&");
  const data = await request(`/values:batchGet?${ranges}&valueRenderOption=UNFORMATTED_VALUE`);
  const state = {};
  names.forEach((table, i) => {
    const rows = data.valueRanges[i]?.values ?? [];
    const records = rows.filter((row) => row[0]).map((row) => Object.fromEntries(headers[table].map((key, j) => {
      let value = row[j] ?? "";
      if (["amountCents", "revision"].includes(key)) value = Number(value);
      if (key.endsWith("Cents") && key !== "amountCents") value = value === "" ? null : Number(value);
      if ((key === "balanceUpdatedAt" || key === "balanceAsOf" || key === "balanceIncludedTransactionIds" || key === "completedAt") && value === "") value = null;
      if (key === "dueDay") value = value === "" ? null : Number(value);
      if (key === "transactionsReviewed") value = value === "" ? void 0 : Number(value);
      if (key === "autopay" || key === "completed") value = value === "" && key === "completed" ? void 0 : value === true || value === "true";
      if (key === "voided" || key === "hidden") value = value === true || value === "true" ? true : void 0;
      if (["accounts", "budgets", "income"].includes(table) && ["revision", "dueDay", "paymentAccountId", "classification", "aliases"].includes(key) && row[j] === void 0) value = void 0;
      if (key === "before" || key === "after") value = value ? JSON.parse(String(value)) : null;
      return [key, value];
    })));
    for (const record of records) for (const key of Object.keys(record)) if (record[key] === void 0) delete record[key];
    if (table === "dailyCheckIns") for (const record of records) {
      record.completed ??= true;
      record.completedAt ||= record.confirmedAt;
      record.transactionsReviewed ??= JSON.parse(String(record.transactionFingerprint)).length;
    }
    const latest = /* @__PURE__ */ new Map();
    for (const record of records) latest.set(String(record.id) + (table === "budgets" || table === "income" ? `:${record.month}` : ""), record);
    state[table] = Array.from(latest.values());
  });
  return state;
}
async function writeRecords(writes) {
  await ready();
  await request(":batchUpdate", { requests: writes.map((w) => append(w.table, w.records)) });
}
function mutate(operation) {
  const result = queue.then(operation);
  queue = result.catch(() => void 0);
  return result;
}
async function exportSnapshot(state) {
  if (!reportsConfigured()) throw new Error("Set the spreadsheet ID and share it with the server service account first.");
  const prefix = `CFT_${(/* @__PURE__ */ new Date()).toISOString().replace(/[-:]/g, "").replace(/\.\d{3}Z$/, "Z")}_${randomBytes(3).toString("hex")}`;
  const metadata = await request("?fields=sheets.properties");
  const used = new Set((metadata.sheets ?? []).map((s) => s.properties.sheetId));
  const exportSheets = names.map((table) => {
    let id = randomInt(1, 2e9);
    while (used.has(id)) id = randomInt(1, 2e9);
    used.add(id);
    return { table, id, title: `${prefix}_${sheetName(table)}` };
  });
  const requests = exportSheets.map(({ table, id, title }) => ({ addSheet: { properties: { sheetId: id, title, gridProperties: { frozenRowCount: 1, rowCount: Math.max(100, state[table].length + 1), columnCount: headers[table].length } } } }));
  for (const { table, id } of exportSheets) requests.push({ updateCells: { start: { sheetId: id, rowIndex: 0, columnIndex: 0 }, fields: "userEnteredValue", rows: [cells(sheetHeaders(table)), ...state[table].map((record) => cells(headers[table].map((h) => record[h])))] } });
  await request(":batchUpdate", { requests });
  return { prefix, tabs: exportSheets.map((s) => s.title), exportedAt: (/* @__PURE__ */ new Date()).toISOString(), records: names.reduce((n, table) => n + state[table].length, 0) };
}

// server/firebase.ts
import { cert, getApps, initializeApp } from "firebase-admin/app";
import { getAuth } from "firebase-admin/auth";
import { getFirestore } from "firebase-admin/firestore";
var firestoreEnabled = () => process.env.STORAGE_BACKEND === "firestore";
function firebaseWebConfig() {
  return { apiKey: process.env.FIREBASE_API_KEY, authDomain: process.env.FIREBASE_AUTH_DOMAIN, projectId: process.env.FIREBASE_PROJECT_ID, appId: process.env.FIREBASE_APP_ID };
}
function validateFirebaseConfiguration() {
  if (!firestoreEnabled()) return;
  if (Object.values(firebaseWebConfig()).some((v) => !v) || !serviceAccountConfigured() || !process.env.FIREBASE_OWNER_EMAIL) throw new Error("Firestore requires the web configuration, private server service-account JSON or file path, and owner email.");
  readFirebaseServiceAccount();
  adminApp();
}
function adminApp() {
  const existing = getApps().find((app) => app.name === "cash-flow-server");
  if (existing) return existing;
  const credential = readFirebaseServiceAccount();
  if (credential.project_id !== process.env.FIREBASE_PROJECT_ID) throw new Error("The Firebase credential belongs to a different project.");
  return initializeApp({ credential: cert({ projectId: credential.project_id, clientEmail: credential.client_email, privateKey: credential.private_key }), projectId: credential.project_id }, "cash-flow-server");
}
function requireOwner(token, email = process.env.FIREBASE_OWNER_EMAIL) {
  if (!email || token.email?.toLowerCase() !== email.toLowerCase() || !token.email_verified || token.firebase.sign_in_provider !== "google.com" || !token.uid) throw new Error("This tracker is private. Sign in with the owner\u2019s Google account.");
  return token.uid;
}
async function authenticateFirebase(authorization) {
  if (!authorization?.startsWith("Bearer ") || authorization.length > 1e4) throw new Error("Please sign in with Google.");
  const token = await getAuth(adminApp()).verifyIdToken(authorization.slice(7), true);
  return requireOwner(token);
}
var firebaseDatabase = () => getFirestore(adminApp());

// server/firestore.ts
import { AsyncLocalStorage } from "node:async_hooks";
import { createHash } from "node:crypto";

// shared/model.ts
var money = (cents3) => new Intl.NumberFormat("en-US", { style: "currency", currency: "USD" }).format(cents3 / 100);
function localDate(date = /* @__PURE__ */ new Date()) {
  return `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, "0")}-${String(date.getDate()).padStart(2, "0")}`;
}
function monthBudgets(state, month, scope) {
  return resolvePlans(state.budgets, month, scope).filter((b) => !b.hidden);
}
function resolvePlans(plans, month, scope) {
  const selected = /* @__PURE__ */ new Map();
  const priority = (p) => p.month === month ? "2" : p.month.startsWith("from:") ? `1${p.month}` : "0";
  for (const p of plans) {
    if (scope !== "All" && p.scope !== scope) continue;
    if (p.month !== "*" && p.month !== month && !(p.month.startsWith("from:") && p.month.slice(5) <= month)) continue;
    const previous = selected.get(p.id);
    if (!previous || (p.revision ?? 0) > (previous.revision ?? 0) || (p.revision ?? 0) === (previous.revision ?? 0) && priority(p) > priority(previous)) selected.set(p.id, p);
  }
  return [...selected.values()];
}
function scopedTransactions(state, month, scope) {
  return state.transactions.filter((t) => t.date.startsWith(month) && (scope === "All" || (t.type === "Transfer" ? state.accounts.some((a) => (a.id === t.accountId || a.id === t.toAccountId) && a.scope === scope) : t.scope === scope))).sort((a, b) => `${b.date}T${b.time}`.localeCompare(`${a.date}T${a.time}`) || b.createdAt.localeCompare(a.createdAt));
}
function accountFlows(accountId, transactions) {
  let inflows = 0, outflows = 0;
  for (const t of transactions) {
    if (t.accountId === accountId) {
      if (t.type === "Income") inflows += t.amountCents;
      else outflows += t.amountCents;
    }
    if (t.type === "Transfer" && t.toAccountId === accountId) inflows += t.amountCents;
  }
  return { inflows, outflows };
}
function validateTransaction(input, state, previous) {
  if (!input || typeof input !== "object") throw new Error("Invalid transaction.");
  const v = input;
  const string = (key, max = 500) => {
    if (typeof v[key] !== "string" || v[key].length > max) throw new Error(`Invalid ${key}.`);
    return v[key].trim();
  };
  const type = string("type");
  if (!["Expense", "Income", "Transfer"].includes(type)) throw new Error("Choose a valid transaction type.");
  const amountCents = v.amountCents;
  if (!Number.isSafeInteger(amountCents) || amountCents <= 0 || amountCents > 99999999999) throw new Error("Amount must be greater than zero, in whole cents.");
  const date = string("date", 10), time = string("time", 5);
  if (!/^\d{4}-\d{2}-\d{2}$/.test(date) || !Number.isFinite(Date.parse(`${date}T12:00:00Z`)) || (/* @__PURE__ */ new Date(`${date}T12:00:00Z`)).toISOString().slice(0, 10) !== date) throw new Error("Choose a valid date.");
  if (!/^([01]\d|2[0-3]):[0-5]\d$/.test(time)) throw new Error("Choose a valid time.");
  const accountId = string("accountId", 100), account = state.accounts.find((a) => a.id === accountId);
  if (!account) throw new Error("Choose an account.");
  const toAccountId = type === "Transfer" ? string("toAccountId", 100) : "";
  if (type === "Transfer" && (!state.accounts.some((a) => a.id === toAccountId) || accountId === toAccountId)) throw new Error("Choose a different destination account.");
  const category = type === "Transfer" ? "Transfer" : string("category", 100);
  if (type !== "Transfer" && !state.categories.some((c) => c.name === category)) throw new Error("Choose a category.");
  const classification = type === "Expense" ? string("classification") : "";
  if (type === "Expense" && !["Need", "Want"].includes(classification)) throw new Error("Choose Need or Want.");
  const scope = string("scope", 10);
  if (!["Personal", "Business"].includes(scope)) throw new Error("Choose Personal or Business independently of the account.");
  const merchant = string("merchant", 200), description = string("description", 500);
  if (!merchant) throw new Error("Enter a merchant, income source, or transfer description.");
  const id = string("id", 100);
  if (!/^[a-zA-Z0-9-]{1,100}$/.test(id)) throw new Error("Invalid transaction ID.");
  if (previous && (id !== previous.id || v.revision !== previous.revision)) throw new Error("This transaction has changed. Reload before editing.");
  if (!previous && state.transactions.some((t) => t.id === id)) throw new Error("Transaction already exists.");
  const now = (/* @__PURE__ */ new Date()).toISOString();
  return { id, date, time, type, amountCents, category, subcategory: type === "Expense" ? string("subcategory", 100) : "", merchant, description, accountId, toAccountId, scope, classification, notes: string("notes", 2e3), createdAt: previous?.createdAt ?? now, updatedAt: now, revision: (previous?.revision ?? 0) + 1 };
}

// shared/actions.ts
var actionCategories = ["Bill Review", "Cost Reduction", "Negotiation", "Subscription", "Insurance", "Banking", "Business", "Income Opportunity", "Financial Leak", "Research", "Other"];
function extendState(input) {
  if (!input || typeof input !== "object") throw new Error("Saved data could not be read.");
  const data = input;
  for (const key of ["accounts", "categories", "budgets", "income", "transactions", "audit"]) if (!Array.isArray(data[key])) throw new Error("Your saved financial data could not be read. Recover it before continuing.");
  for (const key of ["notesReminders", "dailyCheckIns", "leakReviews", "expenseFunding", "incomeSources", "settings", "monthReviews", "balanceReconciliations"]) if (data[key] !== void 0 && !Array.isArray(data[key])) throw new Error("Your saved action data could not be read. Recover it before continuing.");
  return { ...data, notesReminders: data.notesReminders ?? [], dailyCheckIns: data.dailyCheckIns ?? [], leakReviews: data.leakReviews ?? [], expenseFunding: data.expenseFunding ?? [], incomeSources: data.incomeSources ?? [], settings: data.settings ?? [], monthReviews: data.monthReviews ?? [], balanceReconciliations: data.balanceReconciliations ?? [] };
}
function validDate(date) {
  return /^\d{4}-\d{2}-\d{2}$/.test(date) && Number.isFinite(Date.parse(`${date}T12:00:00Z`)) && (/* @__PURE__ */ new Date(`${date}T12:00:00Z`)).toISOString().slice(0, 10) === date;
}
function validateAction(input, state, previous) {
  if (!input || typeof input !== "object") throw new Error("Invalid financial action.");
  const v = input;
  const text3 = (key, max) => {
    if (typeof v[key] !== "string" || v[key].length > max) throw new Error(`Invalid ${key}.`);
    return v[key].trim();
  };
  const id = text3("id", 100), title = text3("title", 200), note = text3("note", 4e3);
  if (!/^[a-zA-Z0-9-]{1,100}$/.test(id) || !title) throw new Error("Give your financial action a title.");
  if (previous && (id !== previous.id || v.revision !== previous.revision)) throw new Error("This action has changed. Reload before editing.");
  if (!previous && state.notesReminders.some((a) => a.id === id)) throw new Error("This action already exists.");
  const category = text3("category", 40), priority = text3("priority", 10), status = text3("status", 20);
  if (!actionCategories.includes(category) || !["Low", "Medium", "High"].includes(priority) || !["Open", "In Progress", "Completed"].includes(status)) throw new Error("Choose a valid category, priority, and status.");
  const scope = text3("scope", 10);
  if (!["Personal", "Business"].includes(scope)) throw new Error("Choose Personal or Business.");
  const relatedExpenseId = text3("relatedExpenseId", 150), relatedAccountId = text3("relatedAccountId", 100);
  if (relatedAccountId && !state.accounts.some((a) => a.id === relatedAccountId)) throw new Error("Choose a valid related account.");
  if (relatedExpenseId) {
    const [kind, expenseId] = relatedExpenseId.split(":");
    const expense = kind === "budget" ? state.budgets.find((b) => b.id === expenseId) : kind === "transaction" ? state.transactions.find((t) => t.id === expenseId && t.type === "Expense") : void 0;
    if (!expense || expense.scope !== scope) throw new Error("Choose a related expense in the same money space.");
  }
  const reminderDate = text3("reminderDate", 10);
  if (reminderDate && !validDate(reminderDate)) throw new Error("Choose a valid reminder date.");
  const cents3 = (key, signed = false) => {
    if (v[key] === null || v[key] === void 0) return null;
    const value = v[key];
    if (!Number.isSafeInteger(value) || Math.abs(value) > 99999999999 || !signed && value < 0) throw new Error("Enter valid amounts in whole cents.");
    return value;
  };
  const amountAffectedCents = cents3("amountAffectedCents"), previousCostCents = cents3("previousCostCents"), newCostCents = cents3("newCostCents");
  const monthlySavingsCents = previousCostCents !== null && newCostCents !== null ? previousCostCents - newCostCents : cents3("monthlySavingsCents", true);
  const now = (/* @__PURE__ */ new Date()).toISOString();
  return { id, title, note, category, priority, status, scope, relatedExpenseId, relatedAccountId, reminderDate, amountAffectedCents, previousCostCents, newCostCents, monthlySavingsCents, annualizedSavingsCents: monthlySavingsCents === null ? null : monthlySavingsCents * 12, createdAt: previous?.createdAt ?? now, updatedAt: now, completedAt: status === "Completed" ? previous?.status === "Completed" ? previous.completedAt : now : null, revision: (previous?.revision ?? 0) + 1 };
}
function transactionFingerprint(state, date, scope) {
  return JSON.stringify(scopedTransactions(state, date.slice(0, 7), scope).filter((t) => t.date === date).map((t) => [t.id, t.revision]).sort((a, b) => String(a[0]).localeCompare(String(b[0]))));
}
function validateCheckIn(input, state) {
  if (!input || typeof input !== "object") throw new Error("Invalid check-in.");
  const v = input, date = String(v.date ?? ""), scope = v.scope;
  if (!validDate(date) || !["Personal", "Business", "All"].includes(scope)) throw new Error("Choose a valid date and money space.");
  const id = `${date}-${scope}`, previous = state.dailyCheckIns.find((c) => c.id === id);
  if (v.revision !== (previous?.revision ?? 0)) throw new Error("This check-in has changed. Review today again.");
  const fingerprint = transactionFingerprint(state, date, scope);
  if (v.transactionFingerprint !== fingerprint) throw new Error("Today\u2019s entries have changed. Review them before confirming.");
  if (fingerprint.length > 45e3) throw new Error("There are too many entries for one check-in.");
  const now = (/* @__PURE__ */ new Date()).toISOString();
  return { id, date, scope, transactionFingerprint: fingerprint, confirmedAt: now, completedAt: now, completed: true, transactionsReviewed: JSON.parse(fingerprint).length, revision: (previous?.revision ?? 0) + 1 };
}

// shared/backup.ts
var stateTables = ["accounts", "categories", "budgets", "income", "transactions", "audit", "notesReminders", "dailyCheckIns", "leakReviews", "expenseFunding", "incomeSources", "settings", "monthReviews", "balanceReconciliations"];
function validateBackup(input) {
  const extended = extendState(input);
  const state = Object.fromEntries(stateTables.map((table) => [table, extended[table]]));
  let count = 0;
  for (const table of stateTables) {
    if (!Array.isArray(state[table])) throw new Error(`The backup is missing ${table}.`);
    const ids2 = /* @__PURE__ */ new Set();
    for (const record of state[table]) {
      count++;
      if (!record || typeof record !== "object" || typeof record.id !== "string" || !record.id || record.id.length > 300) throw new Error(`Invalid record in ${table}.`);
      const key = JSON.stringify([record.id, table === "budgets" || table === "income" ? record.month : ""]);
      if (ids2.has(key)) throw new Error(`Duplicate record in ${table}.`);
      ids2.add(key);
    }
  }
  if (count > 400) throw new Error("This backup has more than 400 records. A reviewed batch migration is required; nothing was imported.");
  const inspect = (value, key = "") => {
    if (key.endsWith("Cents") && value !== null && !Number.isSafeInteger(value)) throw new Error("The backup contains an invalid amount in cents.");
    if (typeof value === "number" && !Number.isFinite(value)) throw new Error("The backup contains an invalid number.");
    if (value && typeof value === "object") for (const [childKey, child] of Object.entries(value)) inspect(child, childKey);
  };
  inspect(state);
  for (const account of state.accounts) {
    if (!["Checking", "Savings", "Credit card"].includes(account.type) || !["Personal", "Business"].includes(account.scope) || typeof account.name !== "string" || !/^\d{4}$/.test(account.lastFour)) throw new Error("The backup contains an invalid account.");
    if (account.balanceCents !== null && !Number.isSafeInteger(account.balanceCents)) throw new Error("An opening balance is invalid.");
    if (account.hidden !== void 0 && typeof account.hidden !== "boolean") throw new Error("The backup contains an invalid account visibility.");
    if (account.revision !== void 0 && (!Number.isSafeInteger(account.revision) || account.revision < 0)) throw new Error("The backup contains an invalid account version.");
    if (account.balanceIncludedTransactionIds) {
      const included = JSON.parse(account.balanceIncludedTransactionIds);
      if (!Array.isArray(included) || included.some((id) => typeof id !== "string")) throw new Error("The opening balance snapshot is invalid.");
    }
  }
  for (const category of state.categories) if (typeof category.name !== "string" || !category.name) throw new Error("The backup contains an invalid category.");
  for (const record of [...state.budgets, ...state.income]) {
    if (typeof record.label !== "string" || !["Personal", "Business"].includes(record.scope) || !Number.isSafeInteger(record.amountCents) || record.amountCents < 0 || record.month !== "*" && !/^(from:)?\d{4}-(0[1-9]|1[0-2])$/.test(record.month)) throw new Error("The backup contains an invalid monthly plan.");
  }
  for (const budget of state.budgets) {
    if (budget.hidden !== void 0 && typeof budget.hidden !== "boolean") throw new Error("The backup contains an invalid budget visibility.");
    if (budget.dueDay != null && (!Number.isInteger(budget.dueDay) || budget.dueDay < 1 || budget.dueDay > 31)) throw new Error("The backup contains an invalid bill due day.");
    if (budget.paymentAccountId && !state.accounts.some((a) => a.id === budget.paymentAccountId)) throw new Error("The backup contains an unknown bill account.");
    if (budget.classification !== void 0 && !["Need", "Want"].includes(budget.classification)) throw new Error("The backup contains an invalid budget classification.");
    if (budget.aliases !== void 0) {
      if (typeof budget.aliases !== "string" || budget.aliases.length > 1e4) throw new Error("The backup contains invalid previous budget names.");
      const names2 = JSON.parse(budget.aliases || "[]");
      if (!Array.isArray(names2) || names2.some((pair) => !Array.isArray(pair) || pair.length !== 2 || pair.some((value) => typeof value !== "string" || value.length > 100))) throw new Error("The backup contains invalid previous budget names.");
    }
  }
  for (const plan of [...state.budgets, ...state.income]) if (plan.revision !== void 0 && (!Number.isSafeInteger(plan.revision) || plan.revision < 0)) throw new Error("The backup contains an invalid plan version.");
  for (const transaction of state.transactions) {
    validateTransaction(transaction, state, transaction);
    if (!Number.isSafeInteger(transaction.revision) || transaction.revision < 1 || !Number.isFinite(Date.parse(transaction.createdAt)) || !Number.isFinite(Date.parse(transaction.updatedAt))) throw new Error("A transaction has invalid history metadata.");
  }
  return state;
}

// server/firestore.ts
function documentId(table, record) {
  return createHash("sha256").update(JSON.stringify([record.id, table === "budgets" || table === "income" ? record.month : ""])).digest("hex");
}
var FirestoreStore = class {
  constructor(db, uid) {
    this.db = db;
    this.uid = uid;
    if (!uid || uid.includes("/")) throw new Error("Invalid authenticated user.");
  }
  db;
  uid;
  scope = new AsyncLocalStorage();
  root() {
    return this.db.collection("cashFlowUsers").doc(this.uid);
  }
  meta() {
    return this.root().collection("metadata").doc("state");
  }
  collection(table) {
    return this.root().collection(table);
  }
  async info() {
    const meta = await this.meta().get();
    return { initialized: meta.exists, revision: meta.data()?.revision ?? 0 };
  }
  async snapshot(transaction) {
    const meta = await transaction.get(this.meta());
    if (!meta.exists) throw new Error("Import your reviewed backup before adding cloud records.");
    if (meta.data()?.schemaVersion !== 1) throw new Error("This cloud schema requires a newer tracker.");
    const snapshots = await Promise.all(stateTables.map((table) => transaction.get(this.collection(table))));
    const order = meta.data().recordOrder ?? {};
    const state = Object.fromEntries(stateTables.map((table, index) => {
      const positions = new Map((order[table] ?? []).map((id, position) => [id, position]));
      const records = snapshots[index].docs.map((doc) => doc.data());
      records.sort((a, b) => Number(positions.get(documentId(table, a)) ?? Number.MAX_SAFE_INTEGER) - Number(positions.get(documentId(table, b)) ?? Number.MAX_SAFE_INTEGER));
      return [table, records];
    }));
    return { state, revision: meta.data().revision };
  }
  async readState(includeCancelled = false) {
    const current = this.scope.getStore();
    const state = current ? current.state : await this.db.runTransaction(async (transaction) => (await this.snapshot(transaction)).state, { readOnly: true });
    return includeCancelled ? state : { ...state, transactions: state.transactions.filter((transaction) => !transaction.voided) };
  }
  async mutate(operation) {
    return this.db.runTransaction(async (transaction) => {
      const { state, revision: revision2 } = await this.snapshot(transaction);
      const result = await this.scope.run({ transaction, state }, operation);
      transaction.update(this.meta(), { revision: revision2 + 1, updatedAt: (/* @__PURE__ */ new Date()).toISOString(), recordOrder: Object.fromEntries(stateTables.map((table) => [table, state[table].map((record) => documentId(table, record))])) });
      return result;
    });
  }
  async writeRecords(writes) {
    const current = this.scope.getStore();
    if (!current) throw new Error("Firestore writes require an atomic mutation.");
    for (const write of writes) for (const value of write.records) {
      const record = value;
      const ref = this.collection(write.table).doc(documentId(write.table, record));
      if (write.table === "audit") current.transaction.create(ref, value);
      else current.transaction.set(ref, value);
      const rows = current.state[write.table];
      const index = rows.findIndex((row) => documentId(write.table, row) === documentId(write.table, record));
      if (index < 0) rows.push(record);
      else rows[index] = record;
    }
  }
  async initialize(input) {
    const state = validateBackup(input);
    await this.db.runTransaction(async (transaction) => {
      if ((await transaction.get(this.meta())).exists) throw new Error("Cloud records already exist. Nothing was replaced.");
      const existing = await Promise.all(stateTables.map((table) => transaction.get(this.collection(table).limit(1))));
      if (existing.some((snapshot) => !snapshot.empty)) throw new Error("Cloud records already exist without a setup marker. Review them before importing.");
      for (const table of stateTables) for (const record of state[table]) transaction.create(this.collection(table).doc(documentId(table, record)), record);
      transaction.create(this.meta(), { schemaVersion: 1, revision: 1, initializedAt: (/* @__PURE__ */ new Date()).toISOString(), recordOrder: Object.fromEntries(stateTables.map((table) => [table, state[table].map((record) => documentId(table, record))])), importedCounts: Object.fromEntries(stateTables.map((table) => [table, state[table].length])), importHash: createHash("sha256").update(JSON.stringify(state)).digest("hex") });
    });
    return state;
  }
};

// server/storage.ts
var context = new AsyncLocalStorage2();
var backend = () => firestoreEnabled() ? "firestore" : configured() ? "sheets" : "local";
var configured2 = () => backend() !== "local";
var withCloudUser = (uid, operation) => context.run(new FirestoreStore(firebaseDatabase(), uid), operation);
function cloudStore() {
  const store = context.getStore();
  if (!store) throw new Error("An authenticated cloud user is required.");
  return store;
}
var readState2 = async (includeCancelled = false) => {
  const state = await (firestoreEnabled() ? cloudStore().readState(includeCancelled) : readState());
  return includeCancelled ? state : { ...state, transactions: state.transactions.filter((transaction) => !transaction.voided) };
};
var mutate2 = (operation) => firestoreEnabled() ? cloudStore().mutate(operation) : mutate(operation);
var writeRecords2 = (writes) => firestoreEnabled() ? cloudStore().writeRecords(writes) : writeRecords(writes);

// shared/allocation.ts
var settingsFor = (state) => state.settings.find((s) => s.id === "app") ?? { id: "app", reminderTime: "18:00", smallPurchaseThresholdCents: 1e3, revision: 0, updatedAt: "" };
function nextMonth(month) {
  const d = /* @__PURE__ */ new Date(`${month}-15T12:00:00`);
  d.setMonth(d.getMonth() + 1);
  return localDate(d).slice(0, 7);
}
function localMinute(date = /* @__PURE__ */ new Date()) {
  return `${localDate(date)}T${String(date.getHours()).padStart(2, "0")}:${String(date.getMinutes()).padStart(2, "0")}`;
}
function balanceSnapshotIds(transactions, asOf) {
  return JSON.stringify(transactions.filter((t) => `${t.date}T${t.time}` === asOf).map((t) => t.id).sort());
}
function validSnapshot(asOf) {
  return typeof asOf === "string" && validDate(asOf.slice(0, 10)) && /^\d{4}-\d{2}-\d{2}T([01]\d|2[0-3]):[0-5]\d$/.test(asOf);
}
function balanceBreakdown(state, account, now = localMinute()) {
  const asOf = account.balanceAsOf || (account.balanceUpdatedAt ? localMinute(new Date(account.balanceUpdatedAt)) : "");
  const included = account.balanceIncludedTransactionIds ? JSON.parse(account.balanceIncludedTransactionIds) : state.transactions.filter((t) => t.createdAt <= (account.balanceUpdatedAt ?? "")).map((t) => t.id);
  const known = new Set(included);
  const eligible = state.transactions.filter((t) => {
    const at = `${t.date}T${t.time}`;
    return at <= now && (at > asOf || at === asOf && !known.has(t.id));
  });
  const flows = accountFlows(account.id, eligible), change = flows.inflows - flows.outflows;
  const comparable = account.balanceCents !== null && now >= asOf;
  return { openingCents: account.balanceCents, openingAsOf: asOf, inflows: flows.inflows, outflows: flows.outflows, transactions: eligible.filter((t) => t.accountId === account.id || t.toAccountId === account.id), calculatedCents: comparable ? account.balanceCents + (account.type === "Credit card" ? -change : change) : null };
}
function currentBalance(state, account, now = localMinute()) {
  return balanceBreakdown(state, account, now).calculatedCents;
}
var monthOK = (s) => typeof s === "string" && /^\d{4}-(0[1-9]|1[0-2])$/.test(s);
function object(input) {
  if (!input || typeof input !== "object") throw new Error("Invalid record.");
  return input;
}
function text(v, key, max = 200) {
  if (typeof v[key] !== "string" || v[key].length > max) throw new Error(`Invalid ${key}.`);
  return v[key].trim();
}
function revision(v, previous) {
  if (v.revision !== (previous?.revision ?? 0)) throw new Error("This record changed. Refresh before saving.");
  return (previous?.revision ?? 0) + 1;
}
function cents(value, positive = false) {
  if (!Number.isSafeInteger(value) || value < (positive ? 1 : 0) || value > 99999999999) throw new Error("Enter a valid amount in cents.");
  return value;
}
function validateFunding(input, state) {
  const v = object(input), budgetId = text(v, "budgetId", 100), month = text(v, "month", 12);
  if (!state.budgets.some((b) => b.id === budgetId) || month !== "*" && !monthOK(month.startsWith("from:") ? month.slice(5) : month)) throw new Error("Choose a valid planned expense and month.");
  const id = `funding-${budgetId}-${month === "*" ? "default" : month}`, before = state.expenseFunding.find((f) => f.id === id), paymentAccountId = text(v, "paymentAccountId", 100);
  if (paymentAccountId && !state.accounts.some((a) => a.id === paymentAccountId)) throw new Error("Choose a payment account.");
  if (v.dueDay !== null && (!Number.isInteger(v.dueDay) || Number(v.dueDay) < 1 || Number(v.dueDay) > 31)) throw new Error("Choose a due day between 1 and 31.");
  if (typeof v.autopay !== "boolean") throw new Error("Choose an autopay setting.");
  return { id, budgetId, month, paymentAccountId, amountCents: cents(v.amountCents), dueDay: v.dueDay, autopay: v.autopay, revision: revision(v, before), updatedAt: (/* @__PURE__ */ new Date()).toISOString() };
}
function validateSettings(input, state) {
  const v = object(input), reminderTime = text(v, "reminderTime", 5);
  if (!/^([01]\d|2[0-3]):[0-5]\d$/.test(reminderTime)) throw new Error("Choose a valid reminder time.");
  return { id: "app", reminderTime, smallPurchaseThresholdCents: cents(v.smallPurchaseThresholdCents, true), revision: revision(v, state.settings.find((s) => s.id === "app")), updatedAt: (/* @__PURE__ */ new Date()).toISOString() };
}
function validateIncomeSource(input, state) {
  const v = object(input), id = text(v, "id", 100), name = text(v, "name"), scope = text(v, "scope", 10), category = text(v, "category", 100), defaultAccountId = text(v, "defaultAccountId", 100);
  if (!/^[a-zA-Z0-9-]{1,100}$/.test(id) || !name || !["Personal", "Business"].includes(scope) || !state.categories.some((c) => c.name === category) || defaultAccountId && !state.accounts.some((a) => a.id === defaultAccountId)) throw new Error("Choose a source name, classification, category, and valid destination.");
  return { id, name, scope, category, defaultAccountId, revision: revision(v, state.incomeSources.find((s) => s.id === id)), updatedAt: (/* @__PURE__ */ new Date()).toISOString() };
}
function validateMonthReview(input, state) {
  const v = object(input), month = text(v, "month", 7), scope = text(v, "scope", 10), note = text(v, "note", 6e3);
  if (!monthOK(month) || !["Personal", "Business", "All"].includes(scope)) throw new Error("Choose a valid review month and classification.");
  const id = `${month}-${scope}`, before = state.monthReviews.find((r) => r.id === id), now = (/* @__PURE__ */ new Date()).toISOString();
  return { id, month, scope, note, nextMonth: nextMonth(month), createdAt: before?.createdAt ?? now, updatedAt: now, revision: revision(v, before) };
}

// shared/reconciliation.ts
function reconciliationFingerprint(state, account, asOf) {
  const b = balanceBreakdown(state, account, asOf);
  return JSON.stringify([
    account.type,
    account.balanceCents,
    b.openingAsOf,
    account.balanceUpdatedAt,
    account.balanceIncludedTransactionIds ?? null,
    b.transactions.map((t) => [t.id, t.date, t.time, t.type, t.amountCents, t.accountId, t.toAccountId]).sort((a, c) => String(a[0]).localeCompare(String(c[0])))
  ]);
}
function validateReconciliation(input, state, now = localMinute()) {
  if (!input || typeof input !== "object") throw new Error("Invalid balance comparison.");
  const v = input;
  const id = String(v.id ?? ""), account = state.accounts.find((a) => a.id === v.accountId);
  if (!/^[a-zA-Z0-9-]{1,100}$/.test(id) || !account) throw new Error("Choose a valid account.");
  if (state.balanceReconciliations.some((r) => r.id === id)) throw new Error("This comparison is already saved. Create a new comparison.");
  if (!validSnapshot(v.asOf) || v.asOf > now) throw new Error("Choose a valid observation date and time, no later than now.");
  const b = balanceBreakdown(state, account, v.asOf);
  if (b.openingAsOf && v.asOf < b.openingAsOf) throw new Error("The observation must be on or after the opening balance snapshot.");
  if (!Number.isSafeInteger(v.actualBalanceCents) || Math.abs(Number(v.actualBalanceCents)) > 99999999999) throw new Error("Enter a valid actual balance in whole cents.");
  if (typeof v.note !== "string" || v.note.length > 2e3) throw new Error("Keep the review note under 2,000 characters.");
  const fingerprint = reconciliationFingerprint(state, account, v.asOf);
  if (fingerprint !== v.ledgerFingerprint) throw new Error("The account or its entries changed. Review the updated calculation before saving.");
  if (fingerprint.length > 45e3) throw new Error("There are too many movements for one comparison. Save a reviewed opening snapshot first.");
  const timestamp = (/* @__PURE__ */ new Date()).toISOString(), actual = v.actualBalanceCents;
  const record = { id, accountId: account.id, accountType: account.type, asOf: v.asOf, actualBalanceCents: actual, openingBalanceCents: b.openingCents, openingAsOf: b.openingAsOf, moneyInCents: b.inflows, moneyOutCents: b.outflows, calculatedBalanceCents: b.calculatedCents, differenceCents: b.calculatedCents === null ? null : actual - b.calculatedCents, ledgerFingerprint: fingerprint, note: v.note.trim(), createdAt: timestamp, updatedAt: timestamp, revision: 1 };
  if (JSON.stringify(record).length > 45e3) throw new Error("There are too many movements for one comparison. Save a reviewed opening snapshot first.");
  return record;
}

// shared/leaks.ts
function evidenceKey(text3) {
  let hash = 14695981039346656037n;
  for (const character of text3) hash = BigInt.asUintN(64, (hash ^ BigInt(character.codePointAt(0))) * 1099511628211n);
  return hash.toString(16);
}
var normalized = (text3) => text3.trim().toLowerCase().replace(/\s+/g, " ");
function precedingMonths(month) {
  const date = /* @__PURE__ */ new Date(`${month}-15T12:00:00`);
  return [1, 2, 3].map((offset) => {
    const d = new Date(date);
    d.setMonth(d.getMonth() - offset);
    return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, "0")}`;
  });
}
function detectLeaks(state, month, scope) {
  const months = precedingMonths(month), allowed = /* @__PURE__ */ new Set([month, ...months]);
  const expenses = state.transactions.filter((t) => t.type === "Expense" && allowed.has(t.date.slice(0, 7)) && (scope === "All" || t.scope === scope));
  const groups = /* @__PURE__ */ new Map();
  for (const t of expenses) {
    if (!t.merchant.trim()) continue;
    const key = JSON.stringify([t.scope, normalized(t.merchant), t.category, normalized(t.subcategory)]);
    groups.set(key, [...groups.get(key) ?? [], t]);
  }
  const results = [];
  const add = (rule, key, title, message, evidence, amount, category = "Bill Review") => {
    const current = evidence.filter((t) => t.date.startsWith(month));
    if (!current.length) return;
    const version = evidence.map((t) => `${t.id}:${t.revision}`).sort().join("|");
    const id = `${month}:${rule}:${evidenceKey(key)}:${evidenceKey(version)}`;
    if (state.leakReviews.some((r) => r.id === id)) return;
    const first = current[0];
    results.push({ id, month, scope: first.scope, title, message, category, transactions: evidence, amountAffectedCents: amount, relatedExpenseId: `transaction:${first.id}`, relatedAccountId: first.accountId });
  };
  for (const [key, rows] of groups) {
    const current = rows.filter((t) => t.date.startsWith(month));
    if (!current.length) continue;
    const first = current[0], name = first.merchant.trim(), total = current.reduce((n, t) => n + t.amountCents, 0);
    const history = months.map((m) => rows.filter((t) => t.date.startsWith(m)));
    const recurringCategory = ["Housing", "Utilities", "Transportation", "Subscriptions / AI"].includes(first.category);
    if (recurringCategory && history.every((t) => t.length > 0)) {
      const average = Math.round(history.flat().reduce((n, t) => n + t.amountCents, 0) / 3);
      if (total - average >= Math.max(500, Math.ceil(average * 0.2))) add("bill-increase", key, "Recurring cost increased", `${name} averaged ${money(average)} per month across the previous 3 months; ${money(total)} is recorded this month. Review the change.`, rows, total - average);
    }
    const amounts = [...new Set(current.map((t) => t.amountCents))].sort((a, b) => a - b);
    if (recurringCategory && amounts.length > 1) add("different-amounts", key, "Different charges for the same service", `${name} has ${current.length} recorded charges this month, ranging from ${money(amounts[0])} to ${money(amounts.at(-1))}. Confirm what each charge covers.`, current, total);
    if (first.category === "Subscriptions / AI") {
      const repeated = amounts.filter((amount) => current.filter((t) => t.amountCents === amount).length > 1);
      if (repeated.length) add("subscription-repeat", key, "Repeated subscription charges", `${name} has repeated charges for ${repeated.map(money).join(", ")} this month. They may be expected; review the billing dates and services.`, current, total, "Subscription");
    }
    const historicalMonths = history.filter((t) => t.length).length;
    const planned = monthBudgets(state, month, first.scope).some((b) => b.category === first.category && b.label === first.subcategory);
    if (recurringCategory && historicalMonths >= 2 && !planned) add("unplanned-recurring", key, "Recurring spending outside the plan", `${name} appears this month and in ${historicalMonths} of the previous 3 months without a matching planned expense. Review whether it belongs in your plan.`, rows, total, "Financial Leak");
  }
  for (const space of ["Personal", "Business"]) {
    if (scope !== "All" && scope !== space) continue;
    const scoped = expenses.filter((t) => t.scope === space), current = scoped.filter((t) => t.date.startsWith(month));
    const threshold = settingsFor(state).smallPurchaseThresholdCents;
    const small = current.filter((t) => t.classification === "Want" && t.amountCents < threshold);
    if (small.length >= 5) {
      const total = small.reduce((n, t) => n + t.amountCents, 0);
      add("small-wants", space, "Repeated small discretionary purchases", `${small.length} want purchases under ${money(threshold)} total ${money(total)} this month. Review the pattern and decide whether to act.`, small, total, "Financial Leak");
    }
    for (const category of new Set(current.map((t) => t.category))) {
      const historical = months.map((m) => scoped.filter((t) => t.date.startsWith(m) && t.category === category));
      if (!historical.every((rows2) => rows2.length)) continue;
      const rows = current.filter((t) => t.category === category), total = rows.reduce((n, t) => n + t.amountCents, 0);
      const average = Math.round(historical.flat().reduce((n, t) => n + t.amountCents, 0) / 3);
      if (total - average >= Math.max(1e3, Math.ceil(average * 0.3))) add("category-increase", `${space}:${category}`, "Category spending above recent average", `${category} averaged ${money(average)} per month across the previous 3 months; ${money(total)} is recorded this month. Compare the entries before changing your plan.`, [...rows, ...historical.flat()], total - average, "Financial Leak");
    }
  }
  return results;
}

// shared/undo.ts
function undoEntry(state, id, revision2, now = Date.now()) {
  const current = state.transactions.find((transaction) => transaction.id === id);
  if (!current || current.revision !== revision2) throw new Error("This entry changed. Refresh before editing it.");
  const saved = [...state.audit].reverse().find((audit) => audit.entityId === id && (audit.entity === "transaction" || audit.entity === "transaction undo"));
  if (!saved || saved.entity !== "transaction" || saved.after?.revision !== revision2) throw new Error("This save can no longer be undone. Open the entry to edit it.");
  const elapsed = now - Date.parse(saved.at);
  if (!Number.isFinite(elapsed) || elapsed < 0 || elapsed > 15e3) throw new Error("Undo has expired. Open the entry to edit it.");
  if (state.accounts.some((account) => [current.accountId, current.toAccountId].includes(account.id) && account.balanceUpdatedAt && Date.parse(account.balanceUpdatedAt) > Date.parse(saved.at))) throw new Error("A bank balance changed after this save. Open the entry to review it.");
  const previous = saved.before;
  const restored = previous ? validateTransaction({ ...previous, revision: revision2 }, state, current) : null;
  const stored = restored ?? { ...current, voided: true, revision: revision2 + 1, updatedAt: new Date(now).toISOString() };
  return { current, restored, stored };
}

// shared/simple.ts
var visibleAccounts = (state, scope) => state.accounts.filter((a) => !a.hidden && (scope === "All" || a.scope === scope));
function planPeriod(input) {
  if (typeof input.startMonth !== "string" || !/^\d{4}-(0[1-9]|1[0-2])$/.test(input.startMonth)) throw new Error("Choose a month.");
  if (!["future", "once"].includes(String(input.applies))) throw new Error("Choose when this change applies.");
  return input.applies === "once" ? input.startMonth : `from:${input.startMonth}`;
}
function cents2(value) {
  if (!Number.isSafeInteger(value) || Number(value) < 0 || Number(value) > 99999999999) throw new Error("Enter a valid amount.");
  return Number(value);
}
function text2(value, max) {
  if (typeof value !== "string" || !value.trim() || value.length > max) throw new Error("Enter a name.");
  return value.trim();
}
function validateBudgetChange(input, state) {
  const v = input, month = planPeriod(v), id = text2(v.id, 100);
  if (!/^[\w-]+$/.test(id)) throw new Error("Invalid item.");
  const versions = state.budgets.filter((b) => b.id === id), revision2 = Math.max(0, ...versions.map((b) => b.revision ?? 0));
  if (v.revision !== revision2) throw new Error("This budget changed. Reopen it and try again.");
  const before = resolvePlans(versions, String(v.startMonth), "All")[0];
  const scope = v.scope;
  if (!["Personal", "Business"].includes(scope) || before && scope !== before.scope) throw new Error("Choose Personal or Business.");
  const label = text2(v.label, 100), category = text2(v.category, 100);
  if (!state.categories.some((c) => c.name === category)) throw new Error("Choose a category.");
  if (v.dueDay !== null && (!Number.isInteger(v.dueDay) || Number(v.dueDay) < 1 || Number(v.dueDay) > 31)) throw new Error("Choose a due day from 1 to 31.");
  const paymentAccountId = String(v.paymentAccountId || "");
  if (paymentAccountId && !state.accounts.some((a) => a.id === paymentAccountId && !a.hidden)) throw new Error("Choose a payment account.");
  if (!["Need", "Want"].includes(String(v.classification))) throw new Error("Choose Need or Want.");
  const aliases = before ? JSON.parse(before.aliases || "[]") : [];
  if (before && (before.label !== label || before.category !== category)) aliases.push([before.category, before.label]);
  if (JSON.stringify(aliases).length > 1e4) throw new Error("This item has too many previous names.");
  return { id, month, scope, label, category, amountCents: cents2(v.amountCents), dueDay: v.dueDay, paymentAccountId, classification: v.classification, hidden: v.hidden === true, aliases: JSON.stringify(aliases), revision: revision2 + 1 };
}
function validateIncomeChange(input, state) {
  const v = input, month = planPeriod(v), scope = v.scope;
  if (!["Personal", "Business"].includes(scope)) throw new Error("Choose Personal or Business.");
  const id = String(v.id), previous = state.income.filter((i) => i.id === id), revision2 = Math.max(0, ...previous.map((i) => i.revision ?? 0));
  if (!/^[\w-]{1,100}$/.test(id) || previous.some((i) => i.scope !== scope) || v.revision !== revision2) throw new Error("This income plan changed. Reopen it.");
  return { id, scope, month, label: "Expected income", amountCents: cents2(v.amountCents), revision: revision2 + 1 };
}
function validateAccountChange(input, state) {
  const v = input, before = state.accounts.find((a) => a.id === v.id);
  if (!/^[\w-]{1,100}$/.test(String(v.id)) || v.revision !== (before?.revision ?? 0)) throw new Error("This account changed. Reopen it.");
  if (!["Personal", "Business"].includes(String(v.scope)) || !["Checking", "Savings", "Credit card"].includes(String(v.type)) || !/^\d{4}$/.test(String(v.lastFour))) throw new Error("Choose an account type and enter its last four digits.");
  if (before && (before.balanceCents !== null || state.transactions.some((t) => t.accountId === before.id || t.toAccountId === before.id)) && (v.type !== before.type || v.scope !== before.scope)) throw new Error("Keep the type and owner of an account with recorded money.");
  if (v.hidden && before && currentBalance(state, before) !== null && currentBalance(state, before) !== 0) throw new Error("Move or settle this account\u2019s balance before hiding it.");
  return { ...before ?? { balanceCents: null, balanceUpdatedAt: null }, id: String(v.id), name: text2(v.name, 100), lastFour: String(v.lastFour), scope: v.scope, type: v.type, hidden: v.hidden === true, revision: (before?.revision ?? 0) + 1 };
}
function removeEntry(state, id, revision2) {
  const before = state.transactions.find((t) => t.id === id);
  if (!before || before.revision !== revision2 || before.voided) throw new Error("This entry changed. Reopen it before removing it.");
  return { ...before, voided: true, revision: revision2 + 1, updatedAt: (/* @__PURE__ */ new Date()).toISOString() };
}
function accountChecked(state, account, now = localMinute()) {
  return state.balanceReconciliations.some((r) => r.accountId === account.id && r.asOf.slice(0, 10) === now.slice(0, 10) && r.differenceCents === 0 && r.ledgerFingerprint === reconciliationFingerprint(state, account, now));
}
function bankObservationNow(timezoneOffset, timestamp = Date.now()) {
  if (!Number.isInteger(timezoneOffset) || Math.abs(timezoneOffset) > 840) throw new Error("Invalid device time zone.");
  return new Date(timestamp - timezoneOffset * 6e4).toISOString().slice(0, 16);
}
function bankCheck(input, state, now) {
  const v = input, account = state.accounts.find((a) => a.id === v.accountId && !a.hidden);
  if (!account) throw new Error("Choose an account.");
  const observedNow = now ?? (v.timezoneOffset !== void 0 ? bankObservationNow(v.timezoneOffset) : localMinute());
  const asOf = typeof v.asOf === "string" ? v.asOf : observedNow;
  const comparison = validateReconciliation({ ...v, asOf, note: v.fix ? "Bank is right, fix balance" : "Check my bank" }, state, observedNow);
  let accounts = [], records = [comparison];
  if (v.fix === true) {
    const after = { ...account, balanceCents: comparison.actualBalanceCents, balanceAsOf: asOf, balanceUpdatedAt: comparison.updatedAt, balanceIncludedTransactionIds: balanceSnapshotIds(state.transactions, asOf) };
    accounts = [after];
    const next2 = { ...state, accounts: state.accounts.map((a) => a.id === after.id ? after : a) };
    records.push(validateReconciliation({ ...v, id: `${comparison.id}-fixed`, asOf, note: "Balance corrected", ledgerFingerprint: reconciliationFingerprint(next2, after, asOf) }, next2, observedNow));
  } else if (comparison.differenceCents !== 0) throw new Error("The balances differ. Add a missing entry or choose Bank is right, fix balance.");
  const next = { ...state, accounts: state.accounts.map((a) => accounts.find((b) => b.id === a.id) ?? a), balanceReconciliations: [...state.balanceReconciliations, ...records] };
  const checks = ["Personal", "Business", "All"].flatMap((scope) => {
    const relevant = visibleAccounts(next, scope);
    if (!relevant.length || !relevant.every((a) => accountChecked(next, a, asOf))) return [];
    const date = asOf.slice(0, 10), previous = next.dailyCheckIns.find((c) => c.date === date && c.scope === scope);
    return [validateCheckIn({ date, scope, revision: previous?.revision ?? 0, transactionFingerprint: transactionFingerprint(next, date, scope) }, next)];
  });
  return { accounts, balanceReconciliations: records, dailyCheckIns: checks };
}

// server/app.ts
function createApp({ hosted = process.env.VERCEL === "1" } = {}) {
  const app = express();
  app.disable("x-powered-by");
  app.set("trust proxy", "loopback");
  app.use(express.json({ limit: "2mb" }));
  const production = process.env.NODE_ENV === "production";
  const secret = process.env.SESSION_SECRET || randomBytes2(32).toString("hex");
  let configurationError = "", allowedOrigin;
  try {
    if (hosted && !firestoreEnabled()) throw new Error("Set STORAGE_BACKEND=firestore in Vercel before opening the tracker.");
    if (hosted || process.env.APP_ORIGIN) {
      let address;
      try {
        address = new URL(process.env.APP_ORIGIN || "");
      } catch {
        throw new Error("Set APP_ORIGIN to the HTTPS website address.");
      }
      if (hosted && address.protocol !== "https:" || !["http:", "https:"].includes(address.protocol) || address.pathname !== "/" || address.search || address.hash || address.username || address.password) throw new Error("Set APP_ORIGIN to the website origin with no path.");
      allowedOrigin = address.origin;
    }
    validateFirebaseConfiguration();
    if (backend() === "sheets" && (!process.env.APP_PASSWORD || !process.env.SESSION_SECRET || process.env.SESSION_SECRET.length < 32)) throw new Error("Set APP_PASSWORD and a SESSION_SECRET of at least 32 characters before using Google Sheets.");
  } catch (error) {
    if (!hosted) throw error;
    configurationError = "Cloud setup is incomplete. Check the Vercel environment variables and Firebase service-account credential, then redeploy.";
  }
  const sign = (s) => createHmac("sha256", secret).update(s).digest("hex");
  const equal = (a, b) => a.length === b.length && timingSafeEqual(Buffer.from(a), Buffer.from(b));
  function signedIn(req) {
    const cookie = req.headers.cookie?.split("; ").find((c) => c.startsWith("cft_session="))?.slice(12) ?? "";
    const [expires, signature] = cookie.split(".");
    return Boolean(expires && signature && Number(expires) > Date.now() && equal(signature, sign(expires)));
  }
  app.use("/api", (req, res, next) => {
    res.setHeader("Cache-Control", "no-store");
    res.setHeader("X-Content-Type-Options", "nosniff");
    if (configurationError) {
      res.status(503).json({ error: configurationError });
      return;
    }
    if (!["GET", "HEAD"].includes(req.method)) {
      if (!req.is("application/json")) {
        res.status(415).json({ error: "JSON is required." });
        return;
      }
      if (req.headers.origin && req.headers.origin !== (allowedOrigin ?? `${req.protocol}://${req.get("host")}`)) {
        res.status(403).json({ error: "Request origin is not allowed." });
        return;
      }
    }
    next();
  });
  app.get("/api/status", async (req, res) => {
    let authenticated = signedIn(req);
    if (firestoreEnabled()) {
      authenticated = false;
      if (req.headers.authorization) try {
        await authenticateFirebase(req.headers.authorization);
        authenticated = true;
      } catch {
      }
    }
    res.json({ configured: configured2(), backend: backend(), authenticated, aiEnabled: Boolean(process.env.GEMINI_API_KEY), sheetsExportEnabled: firestoreEnabled() && reportsConfigured(), firebase: firestoreEnabled() ? firebaseWebConfig() : void 0 });
  });
  const attempts = /* @__PURE__ */ new Map();
  app.post("/api/login", (req, res) => {
    if (firestoreEnabled()) {
      res.status(409).json({ error: "Use Google sign-in for Firestore." });
      return;
    }
    const ip = req.ip ?? "local";
    const entry = attempts.get(ip);
    if (entry && entry.until > Date.now() && entry.count >= 10) {
      res.status(429).json({ error: "Too many attempts. Try again in 15 minutes." });
      return;
    }
    const password = req.body?.password;
    if (!process.env.APP_PASSWORD || typeof password !== "string" || !equal(sign(password), sign(process.env.APP_PASSWORD))) {
      attempts.set(ip, { count: entry && entry.until > Date.now() ? entry.count + 1 : 1, until: Date.now() + 9e5 });
      res.status(401).json({ error: "That password did not match." });
      return;
    }
    attempts.delete(ip);
    const expires = String(Date.now() + 12 * 60 * 60 * 1e3);
    res.cookie("cft_session", `${expires}.${sign(expires)}`, { httpOnly: true, sameSite: "strict", secure: production, maxAge: 12 * 60 * 60 * 1e3, path: "/" });
    res.json({ ok: true });
  });
  app.post("/api/logout", (_req, res) => {
    res.clearCookie("cft_session", { path: "/" });
    res.json({ ok: true });
  });
  app.use("/api", async (req, res, next) => {
    if (!configured2()) {
      res.status(503).json({ error: "Cloud storage is not configured." });
      return;
    }
    if (firestoreEnabled()) {
      try {
        const uid = await authenticateFirebase(req.headers.authorization);
        withCloudUser(uid, next);
      } catch {
        res.status(401).json({ error: "Please sign in with the owner\u2019s Google account." });
      }
      return;
    }
    if (!signedIn(req)) {
      res.status(401).json({ error: "Please sign in again." });
      return;
    }
    next();
  });
  app.get("/api/cloud/info", async (_req, res) => {
    if (!firestoreEnabled()) {
      res.status(409).json({ error: "Firestore is not enabled." });
      return;
    }
    res.json(await cloudStore().info());
  });
  app.post("/api/cloud/import", async (req, res) => {
    if (!firestoreEnabled()) {
      res.status(409).json({ error: "Firestore is not enabled." });
      return;
    }
    if (req.body?.confirmed !== true) throw new Error("Review your backup and confirm the import first.");
    res.json(await cloudStore().initialize(req.body.state));
  });
  app.post("/api/sheets/export", async (_req, res) => {
    if (!firestoreEnabled()) {
      res.status(409).json({ error: "Snapshot exports require Firestore storage." });
      return;
    }
    res.json(await exportSnapshot(await readState2()));
  });
  app.get("/api/state", async (_req, res) => res.json(await readState2()));
  const planChanges = { "budget-items": { table: "budgets", validate: validateBudgetChange }, "planned-income": { table: "income", validate: validateIncomeChange }, "account-details": { table: "accounts", validate: validateAccountChange } };
  for (const [route, change] of Object.entries(planChanges)) app.post(`/api/${route}`, async (req, res) => {
    res.json(await mutate2(async () => {
      const state = await readState2(), after = change.validate(req.body, state);
      const before = state[change.table].filter((r) => r.id === after.id);
      await writeRecords2([{ table: change.table, records: [after] }, { table: "audit", records: [{ id: randomUUID(), entity: route, entityId: after.id, at: (/* @__PURE__ */ new Date()).toISOString(), before, after }] }]);
      return after;
    }));
  });
  app.post("/api/bank-check", async (req, res) => {
    res.json(await mutate2(async () => {
      const state = await readState2(), result = bankCheck(req.body, state);
      await writeRecords2([{ table: "accounts", records: result.accounts }, { table: "balanceReconciliations", records: result.balanceReconciliations }, { table: "dailyCheckIns", records: result.dailyCheckIns }, { table: "audit", records: [{ id: randomUUID(), entity: "bank check", entityId: String(req.body.accountId), at: (/* @__PURE__ */ new Date()).toISOString(), before: state.accounts.find((a) => a.id === req.body.accountId), after: result }] }]);
      return result;
    }));
  });
  app.post("/api/transactions/:id/remove", async (req, res) => {
    res.json(await mutate2(async () => {
      const state = await readState2(), after = removeEntry(state, String(req.params.id), req.body.revision);
      await writeRecords2([{ table: "transactions", records: [after] }, { table: "audit", records: [{ id: randomUUID(), entity: "entry removed", entityId: after.id, at: after.updatedAt, before: state.transactions.find((t) => t.id === after.id), after }] }]);
      return after;
    }));
  });
  app.post("/api/transactions", async (req, res) => {
    const result = await mutate2(async () => {
      const state = await readState2(true);
      const previous = state.transactions.find((t) => t.id === req.body?.id);
      if (previous?.voided) throw new Error("This save was undone. Start a new entry instead.");
      if (previous && !req.body?.revision) throw new Error("Transaction already exists.");
      const transaction = validateTransaction(req.body, state, previous);
      const audit = { id: randomUUID(), entity: "transaction", entityId: transaction.id, at: transaction.updatedAt, before: previous ?? null, after: transaction };
      await writeRecords2([{ table: "transactions", records: [transaction] }, { table: "audit", records: [audit] }]);
      return transaction;
    });
    res.json(result);
  });
  app.post("/api/transactions/:id/undo", async (req, res) => {
    const result = await mutate2(async () => {
      const state = await readState2();
      const { current, restored, stored } = undoEntry(state, String(req.params.id), req.body?.revision);
      await writeRecords2([{ table: "transactions", records: [stored] }, { table: "audit", records: [{ id: randomUUID(), entity: "transaction undo", entityId: current.id, at: (/* @__PURE__ */ new Date()).toISOString(), before: current, after: restored }] }]);
      return { transaction: restored };
    });
    res.json(result);
  });
  app.post("/api/accounts/:id/balance", async (req, res) => {
    const result = await mutate2(async () => {
      const state = await readState2();
      const before = state.accounts.find((a) => a.id === req.params.id);
      if (!before) throw new Error("Account was not found.");
      const balance = req.body?.balanceCents;
      if (!Number.isSafeInteger(balance) || Math.abs(balance) > 99999999999) throw new Error("Enter a valid balance in cents.");
      const asOf = req.body.balanceAsOf ?? null;
      if (asOf !== null && !validSnapshot(asOf)) throw new Error("Choose a valid date and time for this balance snapshot.");
      const after = { ...before, balanceAsOf: asOf, balanceIncludedTransactionIds: asOf === null ? null : balanceSnapshotIds(state.transactions, asOf), balanceCents: balance, balanceUpdatedAt: (/* @__PURE__ */ new Date()).toISOString() };
      await writeRecords2([{ table: "accounts", records: [after] }, { table: "audit", records: [{ id: randomUUID(), entity: "account", entityId: after.id, at: after.balanceUpdatedAt, before, after }] }]);
      return after;
    });
    res.json(result);
  });
  app.post("/api/budgets/:id", async (req, res) => {
    const result = await mutate2(async () => {
      const state = await readState2();
      const before = state.budgets.find((b) => b.id === req.params.id && b.month === req.body?.month) ?? state.budgets.find((b) => b.id === req.params.id && b.month === "*");
      if (!before) throw new Error("Budget was not found.");
      const { amountCents, month } = req.body;
      if (!Number.isSafeInteger(amountCents) || amountCents < 0 || amountCents > 99999999999 || typeof month !== "string" || !/^\d{4}-(0[1-9]|1[0-2])$/.test(month)) throw new Error("Enter a valid monthly budget.");
      const after = { ...before, amountCents, month };
      await writeRecords2([{ table: "budgets", records: [after] }, { table: "audit", records: [{ id: randomUUID(), entity: "budget", entityId: after.id, at: (/* @__PURE__ */ new Date()).toISOString(), before, after }] }]);
      return after;
    });
    res.json(result);
  });
  app.post("/api/actions", async (req, res) => {
    const result = await mutate2(async () => {
      const state = await readState2(), before = state.notesReminders.find((a) => a.id === req.body?.id);
      const after = validateAction(req.body, state, before);
      await writeRecords2([{ table: "notesReminders", records: [after] }, { table: "audit", records: [{ id: randomUUID(), entity: "financial action", entityId: after.id, at: after.updatedAt, before: before ?? null, after }] }]);
      return after;
    });
    res.json(result);
  });
  app.post("/api/check-ins", async (req, res) => {
    const result = await mutate2(async () => {
      const state = await readState2(), after = validateCheckIn(req.body, state), before = state.dailyCheckIns.find((c) => c.id === after.id);
      await writeRecords2([{ table: "dailyCheckIns", records: [after] }, { table: "audit", records: [{ id: randomUUID(), entity: "daily check-in", entityId: after.id, at: after.confirmedAt, before: before ?? null, after }] }]);
      return after;
    });
    res.json(result);
  });
  app.post("/api/leak-reviews", async (req, res) => {
    const result = await mutate2(async () => {
      const state = await readState2();
      const before = state.leakReviews.find((r) => r.id === req.body?.id);
      if (before) return before;
      if (typeof req.body?.month !== "string" || !/^\d{4}-(0[1-9]|1[0-2])$/.test(req.body.month)) throw new Error("Choose a valid review month.");
      const leak = detectLeaks(state, req.body.month, "All").find((l) => l.id === req.body.id);
      if (!leak) throw new Error("This review has changed. Refresh before dismissing.");
      const after = { id: leak.id, month: leak.month, dismissedAt: (/* @__PURE__ */ new Date()).toISOString() };
      await writeRecords2([{ table: "leakReviews", records: [after] }, { table: "audit", records: [{ id: randomUUID(), entity: "leak review", entityId: after.id, at: after.dismissedAt, before: null, after }] }]);
      return after;
    });
    res.json(result);
  });
  const extensions = { "balance-reconciliations": { table: "balanceReconciliations", validate: validateReconciliation }, "expense-funding": { table: "expenseFunding", validate: validateFunding }, "income-sources": { table: "incomeSources", validate: validateIncomeSource }, settings: { table: "settings", validate: validateSettings }, "month-reviews": { table: "monthReviews", validate: validateMonthReview } };
  for (const [route, extension] of Object.entries(extensions)) app.post(`/api/${route}`, async (req, res) => {
    const result = await mutate2(async () => {
      const state = await readState2(), after = extension.validate(req.body, state);
      const before = state[extension.table].find((r) => r.id === after.id) ?? null;
      await writeRecords2([{ table: extension.table, records: [after] }, { table: "audit", records: [{ id: randomUUID(), entity: route, entityId: after.id, at: after.updatedAt, before, after }] }]);
      return after;
    });
    res.json(result);
  });
  app.post("/api/ai/draft", async (req, res) => {
    if (!process.env.GEMINI_API_KEY) {
      res.status(503).json({ error: "Gemini is not configured. Use the quick-entry form." });
      return;
    }
    if (typeof req.body?.text !== "string" || !req.body.text.trim() || req.body.text.length > 2e3) throw new Error("Enter a description of up to 2,000 characters.");
    const state = await readState2();
    const response = await fetch(`https://generativelanguage.googleapis.com/v1beta/models/${encodeURIComponent(process.env.GEMINI_MODEL || "gemini-2.5-flash")}:generateContent`, {
      method: "POST",
      headers: { "Content-Type": "application/json", "x-goog-api-key": process.env.GEMINI_API_KEY },
      body: JSON.stringify({
        systemInstruction: { parts: [{ text: `Interpret a transaction as a DRAFT. Never invent missing amounts, merchants, accounts, dates or classifications. Return JSON: type (Expense/Income/Transfer), amount (a dollar string with 2 decimals), merchant, category, subcategory, accountId, toAccountId, classification (Need/Want), scope (Personal/Business, independent of the account), date, time, notes, uncertainties (array of strings). Omit unknown fields and list them in uncertainties. Today's local date: ${req.body.date}. Categories: ${JSON.stringify(state.categories)}. Accounts: ${JSON.stringify(state.accounts.map(({ id, name, lastFour, scope }) => ({ id, name, lastFour, scope })))}. Budget items: ${JSON.stringify(state.budgets.map(({ label, category }) => ({ label, category })))}.` }] },
        contents: [{ role: "user", parts: [{ text: req.body.text }] }],
        generationConfig: { responseMimeType: "application/json", temperature: 0.1 }
      }),
      signal: AbortSignal.timeout(3e4)
    });
    if (!response.ok) throw new Error("Gemini could not create a draft. You can still enter the transaction manually.");
    const data = await response.json();
    const content = data.candidates?.[0]?.content?.parts?.find((p) => p.text)?.text;
    if (!content) throw new Error("Gemini did not return a draft.");
    res.json(JSON.parse(content));
  });
  app.use("/api", (_req, res) => res.status(404).json({ error: "Unknown endpoint." }));
  if (!hosted) {
    const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
    app.use(express.static(path.join(root, "dist")));
    app.get("/{*path}", (_req, res) => res.sendFile(path.join(root, "dist", "index.html")));
  }
  app.use((error, _req, res, _next) => {
    console.error(error.message);
    res.status(400).json({ error: error.message || "The request could not be completed." });
  });
  return app;
}

// server/handler.ts
var handler_default = createApp({ hosted: true });
export {
  handler_default as default
};
